In [1]:
import pandas as pd

In [2]:
df14 = pd.read_csv('constituency_wise_results_2014.csv')
df14

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors
0,Andhra Pradesh,Adilabad,GODAM NAGESH,M,49.0,ST,TRS,Car,425762,5085,430847,1386282
1,Andhra Pradesh,Adilabad,NARESH,M,37.0,ST,INC,Hand,257994,1563,259557,1386282
2,Andhra Pradesh,Adilabad,RAMESH RATHOD,M,48.0,ST,TDP,Bicycle,182879,1319,184198,1386282
3,Andhra Pradesh,Adilabad,RATHOD SADASHIV,M,55.0,ST,BSP,Elephant,94363,57,94420,1386282
4,Andhra Pradesh,Adilabad,NETHAWATH RAMDAS,M,44.0,ST,IND,Auto- Rickshaw,41028,4,41032,1386282
...,...,...,...,...,...,...,...,...,...,...,...,...
8350,Puducherry,Puducherry,PUVALA NAGESWARA RAO,M,60.0,GEN,IND,Sewing Machine,465,0,465,901357
8351,Puducherry,Puducherry,K. MANJINI,M,41.0,GEN,IND,Coconut,767,0,767,901357
8352,Puducherry,Puducherry,R. VALAVAN,M,40.0,GEN,IND,Carrom Board,497,0,497,901357
8353,Puducherry,Puducherry,V. VIJAYA,F,29.0,GEN,IND,Green Chilli,746,0,746,901357
8354,Puducherry,Puducherry,None of the Above,NaN,NaN,NaN,NOTA,NOTA,22267,1,22268,901357

In [3]:
df19 = pd.read_csv('constituency_wise_results_2019.csv')
df19

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors
0,Andhra Pradesh,Aruku,KISHORE CHANDRA DEO,MALE,72.0,ST,TDP,Bicycle,336163,1938,338101,1451418
1,Andhra Pradesh,Aruku,Dr. KOSURI KASI VISWANADHA VEERA VENKATA SATYA...,MALE,54.0,ST,BJP,Lotus,17578,289,17867,1451418
2,Andhra Pradesh,Aruku,GODDETI. MADHAVI,FEMALE,26.0,ST,YSRCP,Ceiling Fan,557561,4629,562190,1451418
3,Andhra Pradesh,Aruku,SHRUTI DEVI VYRICHERLA,FEMALE,46.0,ST,INC,Hand,17656,74,17730,1451418
4,Andhra Pradesh,Aruku,GANGULAIAH VAMPURU.,MALE,49.0,ST,JnP,Glass Tumbler,42245,549,42794,1451418
...,...,...,...,...,...,...,...,...,...,...,...,...
8592,Puducherry,Puducherry,TIRAVITAMANKAI@LOURDHUMARY,FEMALE,57.0,GENERAL,IND,Slate,870,0,870,973410
8593,Puducherry,Puducherry,IMS. BALAJI,MALE,32.0,GENERAL,IND,Bat,2546,0,2546,973410
8594,Puducherry,Puducherry,RAMESH.D,MALE,49.0,SC,IND,Mike,1653,0,1653,973410
8595,Puducherry,Puducherry,V. RAMAMURTHI,MALE,74.0,GENERAL,IND,Whistle,641,1,642,973410
8596,Puducherry,Puducherry,NOTA,NaN,NaN,NaN,NOTA,NaN,12192,7,12199,973410

In [4]:
df14.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8355 entries, 0 to 8354
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   state           8355 non-null   object
 1   pc_name         8355 non-null   object
 2   candidate       8355 non-null   object
 3   sex             7845 non-null   object
 4   age             7845 non-null   float64
 5   category        7845 non-null   object
 6   party           8355 non-null   object
 7   party_symbol    8355 non-null   object
 8   general_votes   8355 non-null   int64
 9   postal_votes    8355 non-null   int64
 10  total_votes     8355 non-null   int64
 11  total_electors  8355 non-null   int64
dtypes: float64(1), int64(4), object(7)
memory usage: 783.4+ KB

In [5]:
df19.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8597 entries, 0 to 8596
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   state           8597 non-null   object
 1   pc_name         8597 non-null   object
 2   candidate       8597 non-null   object
 3   sex             8054 non-null   object
 4   age             8054 non-null   float64
 5   category        8054 non-null   object
 6   party           8597 non-null   object
 7   party_symbol    8054 non-null   object
 8   general_votes   8597 non-null   int64
 9   postal_votes    8597 non-null   int64
 10  total_votes     8597 non-null   int64
 11  total_electors  8597 non-null   int64
dtypes: float64(1), int64(4), object(7)
memory usage: 806.1+ KB

### Odisha, Chhattisgarh, Telangana is missing in df14
### None is missing in df19

In [6]:
df14.state.unique(), len(df14.state.unique())

(array(['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Goa',
        'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu & Kashmir',
        'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
        'Meghalaya', 'Mizoram', 'Nagaland', 'Punjab', 'Rajasthan',
        'Sikkim', 'Tamil Nadu', 'Tripura', 'Uttar Pradesh', 'West Bengal',
        'Jharkhand', 'Uttarakhand', 'Andaman & Nicobar Islands',
        'Chandigarh', 'Dadra & Nagar Haveli', 'Daman & Diu',
        'NCT OF Delhi', 'Lakshadweep', 'Puducherry'], dtype=object),
 33)

In [7]:
df19.state.unique(), len(df19.state.unique())

(array(['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Goa',
        'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu & Kashmir',
        'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
        'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab',
        'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Tripura', 'Uttar Pradesh',
        'West Bengal', 'Chhattisgarh', 'Jharkhand', 'Uttarakhand',
        'Telangana', 'Andaman & Nicobar Islands', 'Chandigarh',
        'Dadra & Nagar Haveli', 'Daman & Diu', 'NCT OF Delhi',
        'Lakshadweep', 'Puducherry'], dtype=object),
 36)

In [8]:
df14[df14['state']=="Andhra Pradesh"]

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors
0,Andhra Pradesh,Adilabad,GODAM NAGESH,M,49.0,ST,TRS,Car,425762,5085,430847,1386282
1,Andhra Pradesh,Adilabad,NARESH,M,37.0,ST,INC,Hand,257994,1563,259557,1386282
2,Andhra Pradesh,Adilabad,RAMESH RATHOD,M,48.0,ST,TDP,Bicycle,182879,1319,184198,1386282
3,Andhra Pradesh,Adilabad,RATHOD SADASHIV,M,55.0,ST,BSP,Elephant,94363,57,94420,1386282
4,Andhra Pradesh,Adilabad,NETHAWATH RAMDAS,M,44.0,ST,IND,Auto- Rickshaw,41028,4,41032,1386282
...,...,...,...,...,...,...,...,...,...,...,...,...
635,Andhra Pradesh,Chittoor,UDAYA C.S,F,34.0,SC,PPOI,Television,3793,10,3803,1451851
636,Andhra Pradesh,Chittoor,P. PUSHPA RAJ,M,57.0,SC,JaSPa,Chappals,5628,112,5740,1451851
637,Andhra Pradesh,Chittoor,G.SAMANYAKIRAN,F,35.0,SC,YSRCP,Ceiling Fan,548184,2540,550724,1451851
638,Andhra Pradesh,Chittoor,S. ANJAPPA,M,43.0,SC,IND,Bat,4314,7,4321,1451851
639,Andhra Pradesh,Chittoor,None of the Above,NaN,NaN,NaN,NOTA,NOTA,6940,56,6996,1451851

In [9]:
df19[(df19["state"]=="Andhra Pradesh") | (df19["state"]=="Telangana")]

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors
0,Andhra Pradesh,Aruku,KISHORE CHANDRA DEO,MALE,72.0,ST,TDP,Bicycle,336163,1938,338101,1451418
1,Andhra Pradesh,Aruku,Dr. KOSURI KASI VISWANADHA VEERA VENKATA SATYA...,MALE,54.0,ST,BJP,Lotus,17578,289,17867,1451418
2,Andhra Pradesh,Aruku,GODDETI. MADHAVI,FEMALE,26.0,ST,YSRCP,Ceiling Fan,557561,4629,562190,1451418
3,Andhra Pradesh,Aruku,SHRUTI DEVI VYRICHERLA,FEMALE,46.0,ST,INC,Hand,17656,74,17730,1451418
4,Andhra Pradesh,Aruku,GANGULAIAH VAMPURU.,MALE,49.0,ST,JnP,Glass Tumbler,42245,549,42794,1451418
...,...,...,...,...,...,...,...,...,...,...,...,...
8325,Telangana,Khammam,BHANALA LAXMANA CHARY,MALE,53.0,GENERAL,IND,Sewing Machine,4704,0,4704,1513809
8326,Telangana,Khammam,MUTYAM ARJUNA RAJU,MALE,30.0,GENERAL,IND,Bangles,2220,0,2220,1513809
8327,Telangana,Khammam,LAXMA NAIK BANOTH,MALE,62.0,ST,IND,Air Conditioner,732,2,734,1513809
8328,Telangana,Khammam,SANJEEVA RAO NAKIRIKANTI,MALE,49.0,SC,IND,SHIP,2024,0,2024,1513809
8329,Telangana,Khammam,NOTA,NaN,NaN,NaN,NOTA,NaN,15802,30,15832,1513809

In [10]:
df19[df19["state"]=="Telangana"]

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors
7870,Telangana,Adilabad,Godam Nagesh,MALE,54.0,ST,TRS,Car,318665,149,318814,1489790
7871,Telangana,Adilabad,RATHOD RAMESH,MALE,52.0,ST,INC,Hand,314057,181,314238,1489790
7872,Telangana,Adilabad,SOYAM BAPU RAO,MALE,52.0,ST,BJP,Lotus,376892,482,377374,1489790
7873,Telangana,Adilabad,KUMRAM VANDANA,FEMALE,35.0,ST,NPRP,Tractor Chalata Kisan,8005,2,8007,1489790
7874,Telangana,Adilabad,Dharavath Narendhar Naik,MALE,27.0,ST,JnP,Glass Tumbler,5233,8,5241,1489790
...,...,...,...,...,...,...,...,...,...,...,...,...
8325,Telangana,Khammam,BHANALA LAXMANA CHARY,MALE,53.0,GENERAL,IND,Sewing Machine,4704,0,4704,1513809
8326,Telangana,Khammam,MUTYAM ARJUNA RAJU,MALE,30.0,GENERAL,IND,Bangles,2220,0,2220,1513809
8327,Telangana,Khammam,LAXMA NAIK BANOTH,MALE,62.0,ST,IND,Air Conditioner,732,2,734,1513809
8328,Telangana,Khammam,SANJEEVA RAO NAKIRIKANTI,MALE,49.0,SC,IND,SHIP,2024,0,2024,1513809
8329,Telangana,Khammam,NOTA,NaN,NaN,NaN,NOTA,NaN,15802,30,15832,1513809

In 2014, Andhra Pradesh underwent bifurcation. For simplicity, all constituencies from that year should be attributed to Telangana state. This includes constituencies such as Adilabad, Hyderabad, Warangal, etc., which should be considered part of Telangana rather than Andhra Pradesh for the year 2014.

In [11]:
for pc in df19[df19["state"] == "Telangana"].pc_name.unique():
    df14.loc[df14["pc_name"] == pc, "state"] = "Telangana"

In [12]:
df14[df14["state"]=="Telangana"]

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors
0,Telangana,Adilabad,GODAM NAGESH,M,49.0,ST,TRS,Car,425762,5085,430847,1386282
1,Telangana,Adilabad,NARESH,M,37.0,ST,INC,Hand,257994,1563,259557,1386282
2,Telangana,Adilabad,RAMESH RATHOD,M,48.0,ST,TDP,Bicycle,182879,1319,184198,1386282
3,Telangana,Adilabad,RATHOD SADASHIV,M,55.0,ST,BSP,Elephant,94363,57,94420,1386282
4,Telangana,Adilabad,NETHAWATH RAMDAS,M,44.0,ST,IND,Auto- Rickshaw,41028,4,41032,1386282
...,...,...,...,...,...,...,...,...,...,...,...,...
277,Telangana,Khammam,RAMESH KOMMU,M,42.0,SC,IND,Gas Stove,1273,1,1274,1440267
278,Telangana,Khammam,RAMU KANDULA,M,35.0,SC,IND,Coconut,1021,0,1021,1440267
279,Telangana,Khammam,LINGALA RAVI KUMAR,M,38.0,SC,IND,Gas Cylinder,9459,1,9460,1440267
280,Telangana,Khammam,SANAPA POMMAIAH,M,50.0,ST,IND,BUCKET,889,0,889,1440267
281,Telangana,Khammam,None of the Above,NaN,NaN,NaN,NOTA,NOTA,4978,13,4991,1440267

1. List top 5 / bottom 5 constituencies of 2014 and 2019 in terms of voter turnout
ratio?

2. List top 5 / bottom 5 states of 2014 and 2019 in terms of voter turnout ratio?

3. Which constituencies have elected the same party for two consecutive elections,
rank them by % of votes to that winning party in 2019

4. Which constituencies have voted for different parties in two elections (list top 10
based on difference (2019-2014) in winner vote percentage in two elections)

5. Top 5 candidates based on margin difference with runners in 2014 and 2019.

6. % Split of votes of parties between 2014 vs 2019 at national level

7. % Split of votes of parties between 2014 vs 2019 at state level.

8. List top 5 constituencies for two major national parties where they have gained vote
share in 2019 as compared to 2014.

9. List top 5 constituencies for two major national parties where they have lost vote
share in 2019 as compared to 2014.

10. Which constituency has voted the most for NOTA?

11. Which constituencies have elected candidates whose party has less than 10% vote
share at state level in 2019?

## Cleaning and adding Voter Turnout Ratio to data frame of 2014 AKA df14

### Two states can have same name pc_name like ['Maharajganj', 'Aurangabad', 'Hamirpur']

In [13]:
# Total vote per pc_name
Total_vote_pc = dict()
# filtering all parliament constituency
for pc in df14.pc_name.unique():
    pcdf = df14[df14["pc_name"]==pc]
    # filtering to check if parliament constituency is in two states 
    for state in pcdf.state.unique():
        total = 0
        s_pcdf = pcdf[pcdf["state"]==state]
        for i in range(len(s_pcdf)):
            total += s_pcdf.iloc[i,10]
        Total_vote_pc[(pc, state)] = total
Total_vote_pc

{('Adilabad ', 'Telangana'): 1045839,
 ('Peddapalle ', 'Telangana'): 1022184,
 ('Karimnagar ', 'Telangana'): 1125184,
 ('Nizamabad', 'Telangana'): 1033924,
 ('Zahirabad', 'Telangana'): 1094806,
 ('Medak', 'Telangana'): 1191011,
 ('Malkajgiri', 'Telangana'): 1620444,
 ('Secundrabad', 'Telangana'): 1003769,
 ('Hyderabad', 'Telangana'): 971421,
 ('CHELVELLA', 'Andhra Pradesh'): 1315862,
 ('Mahbubnagar', 'Telangana'): 1014800,
 ('Nagarkurnool', 'Telangana'): 1108968,
 ('Nalgonda', 'Telangana'): 1189399,
 ('Bhongir ', 'Telangana'): 1211732,
 ('Warangal', 'Telangana'): 1174631,
 ('Mahabubabad  ', 'Telangana'): 1124372,
 ('Khammam ', 'Telangana'): 1183849,
 ('Aruku ', 'Andhra Pradesh'): 909614,
 ('Srikakulam', 'Andhra Pradesh'): 1052115,
 ('Vizianagaram', 'Andhra Pradesh'): 1120316,
 ('Visakhapatnam', 'Andhra Pradesh'): 1163558,
 ('Anakapalli', 'Andhra Pradesh'): 1148072,
 ('Kakinada', 'Andhra Pradesh'): 1099999,
 ('Amalapuram ', 'Andhra Pradesh'): 1120927,
 ('Rajahmundry', 'Andhra Pradesh'): 1154381,
 ('Narsapuram', 'Andhra Pradesh'): 1088947,
 ('Eluru ', 'Andhra Pradesh'): 1201697,
 ('Machilipatnam ', 'Andhra Pradesh'): 1141065,
 ('Vijayawada', 'Andhra Pradesh'): 1195765,
 ('Guntur', 'Andhra Pradesh'): 1244926,
 ('Narasaraopet', 'Andhra Pradesh'): 1282058,
 ('Bapatla ', 'Andhra Pradesh'): 1184634,
 ('Ongole ', 'Andhra Pradesh'): 1208225,
 ('Nandyal', 'Andhra Pradesh'): 1204956,
 ('Kurnool', 'Andhra Pradesh'): 1065732,
 ('Anantapur', 'Andhra Pradesh'): 1212145,
 ('Hindupur', 'Andhra Pradesh'): 1177257,
 ('Kadapa', 'Andhra Pradesh'): 1200662,
 ('Nellore', 'Andhra Pradesh'): 1187648,
 ('Tirupati ', 'Andhra Pradesh'): 1213062,
 ('Rajampet', 'Andhra Pradesh'): 1158317,
 ('Chittoor ', 'Andhra Pradesh'): 1198915,
 ('ARUNACHAL WEST', 'Arunachal Pradesh'): 335665,
 ('ARUNACHAL EAST', 'Arunachal Pradesh'): 261291,
 ('Karimganj ', 'Assam'): 886920,
 ('Silchar', 'Assam'): 799830,
 ('Autonomous District', 'Assam'): 543280,
 ('Dhubri', 'Assam'): 1369624,
 ('Kokrajhar', 'Assam'): 1223869,
 ('Barpeta', 'Assam'): 1205863,
 ('Gauhati', 'Assam'): 1511729,
 ('Mangaldoi', 'Assam'): 1233237,
 ('Tezpur', 'Assam'): 980688,
 ('Nowgong', 'Assam'): 1230074,
 ('Kaliabor', 'Assam'): 1166490,
 ('Jorhat', 'Assam'): 931336,
 ('Dibrugarh', 'Assam'): 890968,
 ('Lakhimpur', 'Assam'): 1111975,
 ('Valmiki Nagar', 'Bihar'): 900127,
 ('Paschim Champaran', 'Bihar'): 854800,
 ('Purvi Champaran', 'Bihar'): 822671,
 ('Sheohar', 'Bihar'): 842894,
 ('Sitamarhi', 'Bihar'): 900588,
 ('Madhubani', 'Bihar'): 860453,
 ('Jhanjharpur', 'Bihar'): 941249,
 ('Supaul', 'Bihar'): 970528,
 ('Araria', 'Bihar'): 975811,
 ('Kishanganj', 'Bihar'): 928490,
 ('Katihar', 'Bihar'): 977830,
 ('Purnia', 'Bihar'): 1017732,
 ('Madhepura', 'Bihar'): 1034799,
 ('Darbhanga', 'Bihar'): 828342,
 ('Muzaffarpur', 'Bihar'): 948887,
 ('Vaishali', 'Bihar'): 925937,
 ('Gopalganj (SC)', 'Bihar'): 903583,
 ('Siwan', 'Bihar'): 884021,
 ('Maharajganj', 'Bihar'): 846654,
 ('Maharajganj', 'Uttar Pradesh'): 1056078,
 ('Saran', 'Bihar'): 863254,
 ('Hajipur (SC)', 'Bihar'): 904706,
 ('Ujiarpur', 'Bihar'): 858920,
 ('Samastipur (SC)', 'Bihar'): 863199,
 ('Begusarai', 'Bihar'): 1077855,
 ('Khagaria', 'Bihar'): 896231,
 ('Bhagalpur', 'Bihar'): 974016,
 ('Banka', 'Bihar'): 899353,
 ('Munger', 'Bihar'): 914350,
 ('Nalanda', 'Bihar'): 921761,
 ('Patna Sahib', 'Bihar'): 882262,
 ('Pataliputra', 'Bihar'): 978649,
 ('Arrah', 'Bihar'): 893213,
 ('Buxar', 'Bihar'): 888204,
 ('Sasaram (SC)', 'Bihar'): 846788,
 ('Karakat', 'Bihar'): 789927,
 ('Jahanabad', 'Bihar'): 811516,
 ('Aurangabad', 'Bihar'): 786274,
 ('Aurangabad', 'Maharashtra'): 982933,
 ('Gaya (SC)', 'Bihar'): 809378,
 ('Nawada', 'Bihar'): 884441,
 ('Jamui (SC)', 'Bihar'): 775639,
 ('North Goa', 'Goa'): 406631,
 ('South Goa', 'Goa'): 410369,
 ('Kachchh', 'Gujarat'): 946240,
 ('Banaskantha', 'Gujarat'): 886634,
 ('Patan', 'Gujarat'): 955799,
 ('Mahesana', 'Gujarat'): 1004258,
 ('Sabarkantha', 'Gujarat'): 1094002,
 ('Gandhinagar', 'Gujarat'): 1135495,
 ('Ahmedabad East', 'Gujarat'): 985525,
 ('Ahmedabad West', 'Gujarat'): 964609,
 ('Surendranagar', 'Gujarat'): 944677,
 ('Rajkot', 'Gujarat'): 1057069,
 ('Porbandar', 'Gujarat'): 809433,
 ('Jamnagar', 'Gujarat'): 852643,
 ('Junagadh', 'Gujarat'): 941378,
 ('Amreli', 'Gujarat'): 808816,
 ('Bhavnagar', 'Gujarat'): 917402,
 ('Anand', 'Gujarat'): 970894,
 ('Kheda', 'Gujarat'): 955906,
 ('Panchmahal', 'Gujarat'): 933461,
 ('Dahod', 'Gujarat'): 900381,
 ('Vadodara', 'Gujarat'): 1161577,
 ('Chhota Udaipur', 'Gujarat'): 1100542,
 ('Bharuch', 'Gujarat'): 1060211,
 ('Bardoli', 'Gujarat'): 1206179,
 ('Surat', 'Gujarat'): 947922,
 ('Navsari', 'Gujarat'): 1160747,
 ('Valsad', 'Gujarat'): 1122203,
 ('Ambala', 'Haryana'): 1218995,
 ('Kurukshetra', 'Haryana'): 1135892,
 ('Sirsa', 'Haryana'): 1279105,
 ('Hisar', 'Haryana'): 1155914,
 ('Karnal', 'Haryana'): 1193500,
 ('Sonipat', 'Haryana'): 985638,
 ('Rohtak', 'Haryana'): 1044331,
 ('Bhiwani-Mahendragarh', 'Haryana'): 1030431,
 ('Gurgaon', 'Haryana'): 1320620,
 ('Faridabad', 'Haryana'): 1130725,
 ('Kangra', 'Himachal Pradesh'): 799445,
 ('Mandi', 'Himachal Pradesh'): 726094,
 ('Hamirpur', 'Himachal Pradesh'): 835205,
 ('Hamirpur', 'Uttar Pradesh'): 975240,
 ('Shimla', 'Himachal Pradesh'): 737756,
 ('Baramulla', 'Jammu & Kashmir'): 465992,
 ('Srinagar', 'Jammu & Kashmir'): 312212,
 ('Anantnag', 'Jammu & Kashmir'): 375279,
 ('Ladakh', 'Jammu & Kashmir'): 118029,
 ('Udhampur', 'Jammu & Kashmir'): 1041758,
 ('Jammu', 'Jammu & Kashmir'): 1253593,
 ('Chikkodi', 'Karnataka'): 1071103,
 ('Belgaum', 'Karnataka'): 1078528,
 ('Bagalkot', 'Karnataka'): 1079310,
 ('Bijapur', 'Karnataka'): 966757,
 ('Gulbarga', 'Karnataka'): 997638,
 ('Raichur', 'Karnataka'): 968889,
 ('Bidar', 'Karnataka'): 959384,
 ('Koppal', 'Karnataka'): 1006508,
 ('Bellary', 'Karnataka'): 1045772,
 ('Haveri', 'Karnataka'): 1115968,
 ('Dharwad', 'Karnataka'): 1041226,
 ('Uttara Kannada', 'Karnataka'): 1001038,
 ('Davanagere', 'Karnataka'): 1114868,
 ('Shimoga', 'Karnataka'): 1129008,
 ('Udupi Chikmagalur', 'Karnataka'): 1034108,
 ('Hassan', 'Karnataka'): 1147172,
 ('Dakshina Kannada', 'Karnataka'): 1207474,
 ('Chitradurga', 'Karnataka'): 1096499,
 ('Tumkur', 'Karnataka'): 1101484,
 ('Mandya', 'Karnataka'): 1192638,
 ('Mysore', 'Karnataka'): 1159594,
 ('Chamarajanagar', 'Karnataka'): 1133029,
 ('Bangalore Rural', 'Karnataka'): 1455244,
 ('Bangalore North', 'Karnataka'): 1356718,
 ('Bangalore central', 'Karnataka'): 1074589,
 ('Bangalore South', 'Karnataka'): 1113726,
 ('Chikkballapur', 'Karnataka'): 1263274,
 ('Kolar', 'Karnataka'): 1127315,
 ('Kasaragod', 'Kerala'): 974215,
 ('Kannur', 'Kerala'): 947117,
 ('Vadakara', 'Kerala'): 959342,
 ('Wayanad', 'Kerala'): 915006,
 ('Kozhikode', 'Kerala'): 943009,
 ('Malappuram', 'Kerala'): 853467,
 ('Ponnani', 'Kerala'): 871592,
 ('Palakkad', 'Kerala'): 910322,
 ('Alathur ', 'Kerala'): 927228,
 ('Thrissur', 'Kerala'): 920505,
 ('Chalakudy', 'Kerala'): 884033,
 ('Ernakulam', 'Kerala'): 850834,
 ('Idukki', 'Kerala'): 819766,
 ('Kottayam', 'Kerala'): 831636,
 ('Alappuzha', 'Kerala'): 997464,
 ('Mavelikkara ', 'Kerala'): 889060,
 ('Pathanamthitta', 'Kerala'): 869452,
 ('Kollam', 'Kerala'): 879056,
 ('Attingal', 'Kerala'): 859350,
 ('Thiruvananthapuram', 'Kerala'): 873441,
 ('MORENA', 'Madhya Pradesh'): 854279,
 ('BHIND', 'Madhya Pradesh'): 729084,
 ('GWALIOR', 'Madhya Pradesh'): 990912,
 ('GUNA', 'Madhya Pradesh'): 976629,
 ('SAGAR', 'Madhya Pradesh'): 891929,
 ('TIKAMGARH', 'Madhya Pradesh'): 766321,
 ('DAMOH', 'Madhya Pradesh'): 912080,
 ('KHAJURAHO', 'Madhya Pradesh'): 874477,
 ('SATNA', 'Madhya Pradesh'): 913444,
 ('REWA', 'Madhya Pradesh'): 830002,
 ('SIDHI', 'Madhya Pradesh'): 989396,
 ('SHAHDOL', 'Madhya Pradesh'): 968518,
 ('JABALPUR', 'Madhya Pradesh'): 1002184,
 ('MANDLA', 'Madhya Pradesh'): 1218518,
 ('BALAGHAT', 'Madhya Pradesh'): 1113364,
 ('CHHINDWARA', 'Madhya Pradesh'): 1107498,
 ('HOSHANGABAD', 'Madhya Pradesh'): 1031175,
 ('VIDISHA', 'Madhya Pradesh'): 1073473,
 ('BHOPAL', 'Madhya Pradesh'): 1130182,
 ('RAJGARH', 'Madhya Pradesh'): 1010724,
 ('DEWAS', 'Madhya Pradesh'): 1143970,
 ('UJJAIN', 'Madhya Pradesh'): 1016405,
 ('MANDSOUR', 'Madhya Pradesh'): 1161349,
 ('RATLAM', 'Madhya Pradesh'): 1082690,
 ('DHAR', 'Madhya Pradesh'): 1076816,
 ('INDORE', 'Madhya Pradesh'): 1316817,
 ('KHARGONE', 'Madhya Pradesh'): 1152525,
 ('KHANDWA', 'Madhya Pradesh'): 1257327,
 ('BETUL', 'Madhya Pradesh'): 1047719,
 ('Nandurbar ', 'Maharashtra'): 1116676,
 ('Dhule', 'Maharashtra'): 983083,
 ('Jalgaon', 'Maharashtra'): 990332,
 ('Raver', 'Maharashtra'): 1009213,
 ('Buldhana', 'Maharashtra'): 978626,
 ('Akola', 'Maharashtra'): 978491,
 ('Amravati ', 'Maharashtra'): 1004061,
 ('Wardha', 'Maharashtra'): 1013445,
 ('Ramtek ', 'Maharashtra'): 1050316,
 ('Nagpur ', 'Maharashtra'): 1085038,
 ('Bhandara - gondiya', 'Maharashtra'): 1197196,
 ('Gadchiroli-Chimur', 'Maharashtra'): 1027129,
 ('Chandrapur', 'Maharashtra'): 1109743,
 ('Yavatmal-Washim', 'Maharashtra'): 1032949,
 ('Hingoli ', 'Maharashtra'): 1051164,
 ('Nanded', 'Maharashtra'): 1013350,
 ('Parbhani', 'Maharashtra'): 1162233,
 ('Jalna', 'Maharashtra'): 1066259,
 ('Dindori ', 'Maharashtra'): 970182,
 ('Nashik', 'Maharashtra'): 937405,
 ('Palghar ', 'Maharashtra'): 992618,
 ('Bhiwandi', 'Maharashtra'): 875605,
 ('Kalyan', 'Maharashtra'): 824196,
 ('Thane', 'Maharashtra'): 1054189,
 ('Mumbai North', 'Maharashtra'): 946562,
 ('Mumbai North West', 'Maharashtra'): 895517,
 ('Mumbai North East', 'Maharashtra'): 861761,
 ('Mumbai North central', 'Maharashtra'): 845292,
 ('Mumbai South central', 'Maharashtra'): 768627,
 ('Mumbai   South', 'Maharashtra'): 779741,
 ('Raigad', 'Maharashtra'): 987766,
 ('Maval', 'Maharashtra'): 1174335,
 ('Pune', 'Maharashtra'): 993278,
 ('Baramati', 'Maharashtra'): 1066556,
 ('Shirur', 'Maharashtra'): 1089506,
 ('Ahmadnagar ', 'Maharashtra'): 1062318,
 ('Shirdi', 'Maharashtra'): 932645,
 ('Beed', 'Maharashtra'): 1232200,
 ('Osmanabad', 'Maharashtra'): 1118151,
 ('Latur ', 'Maharashtra'): 1057156,
 ('Solapur ', 'Maharashtra'): 951201,
 ('Madha', 'Maharashtra'): 1079619,
 ('Sangli', 'Maharashtra'): 1046659,
 ('Satara', 'Maharashtra'): 976681,
 ('Ratnagiri - sindhudurg', 'Maharashtra'): 896256,
 ('Kolhapur', 'Maharashtra'): 1260289,
 ('Hatkanangle', 'Maharashtra'): 1188871,
 ('Inner manipur', 'Manipur'): 640870,
 ('Outer manipur', 'Manipur'): 771766,
 ('Shillong', 'Meghalaya'): 619987,
 ('Tura ', 'Meghalaya'): 458071,
 ('MIZORAM', 'Mizoram'): 433201,
 ('Nagaland', 'Nagaland'): 1038910,
 ('Gurdaspur', 'Punjab'): 1042699,
 ('Amritsar', 'Punjab'): 1007196,
 ('Khadoor Sahib', 'Punjab'): 1040518,
 ('Jalandhar', 'Punjab'): 1040762,
 ('Hoshiarpur', 'Punjab'): 961297,
 ('Anandpur Sahib', 'Punjab'): 1086563,
 ('Ludhiana', 'Punjab'): 1100457,
 ('Fatehgarh Sahib', 'Punjab'): 1030954,
 ('Faridkot', 'Punjab'): 1032107,
 ('Firozpur', 'Punjab'): 1105412,
 ('Bathinda', 'Punjab'): 1176767,
 ('Sangrur', 'Punjab'): 1099467,
 ('Patiala', 'Punjab'): 1120933,
 ('Ganganagar', 'Rajasthan'): 1256806,
 ('Bikaner', 'Rajasthan'): 929751,
 ('Churu', 'Rajasthan'): 1131104,
 ('Jhunjhunu', 'Rajasthan'): 1006465,
 ('Sikar', 'Rajasthan'): 1065750,
 ('Jaipur Rural', 'Rajasthan'): 1013691,
 ('Jaipur', 'Rajasthan'): 1296806,
 ('Alwar', 'Rajasthan'): 1062305,
 ('BHARATPUR', 'Rajasthan'): 962432,
 ('KARAULI-DHOLPUR', 'Rajasthan'): 845941,
 ('Dausa', 'Rajasthan'): 930492,
 ('TONK-SAWAI MADHOPUR', 'Rajasthan'): 1043638,
 ('Ajmer', 'Rajasthan'): 1156314,
 ('Nagaur', 'Rajasthan'): 1004019,
 ('Pali', 'Rajasthan'): 1095587,
 ('Jodhpur', 'Rajasthan'): 1078598,
 ('Barmer', 'Rajasthan'): 1219119,
 ('Jalore', 'Rajasthan'): 1087272,
 ('Udaipur', 'Rajasthan'): 1193202,
 ('Banswara', 'Rajasthan'): 1171188,
 ('Chittorgarh', 'Rajasthan'): 1172629,
 ('Rajsamand', 'Rajasthan'): 982119,
 ('Bhilwara', 'Rajasthan'): 1104090,
 ('Kota', 'Rajasthan'): 1154960,
 ('JHALAWAR-BARAN', 'Rajasthan'): 1146364,
 ('Sikkim', 'Sikkim'): 308967,
 ('Thiruvallur ', 'Tamil Nadu'): 1254440,
 ('Chennai North', 'Tamil Nadu'): 910114,
 ('Chennai South', 'Tamil Nadu'): 1071409,
 ('Chennai central', 'Tamil Nadu'): 814894,
 ('Sriperumbudur', 'Tamil Nadu'): 1286647,
 ('Kancheepuram ', 'Tamil Nadu'): 1128399,
 ('Arakkonam', 'Tamil Nadu'): 1089052,
 ('Vellore', 'Tamil Nadu'): 974770,
 ('Krishnagiri', 'Tamil Nadu'): 1068391,
 ('Dharmapuri', 'Tamil Nadu'): 1101345,
 ('Tiruvannamalai', 'Tamil Nadu'): 1067447,
 ('Arani', 'Tamil Nadu'): 1096046,
 ('Viluppuram', 'Tamil Nadu'): 1067641,
 ('Kallakurichi', 'Tamil Nadu'): 1107241,
 ('Salem', 'Tamil Nadu'): 1150296,
 ('Namakkal', 'Tamil Nadu'): 1058755,
 ('Erode', 'Tamil Nadu'): 1008582,
 ('Tiruppur', 'Tamil Nadu'): 1050190,
 ('Nilgiris ', 'Tamil Nadu'): 933076,
 ('Coimbatore', 'Tamil Nadu'): 1176620,
 ('Pollachi', 'Tamil Nadu'): 1012667,
 ('Dindigul', 'Tamil Nadu'): 1083364,
 ('Karur', 'Tamil Nadu'): 1046534,
 ('Tiruchirappalli', 'Tamil Nadu'): 988250,
 ('Perambalur', 'Tamil Nadu'): 1030826,
 ('Cuddalore ', 'Tamil Nadu'): 984538,
 ('Chidambaram ', 'Tamil Nadu'): 1088423,
 ('Mayiladuthurai', 'Tamil Nadu'): 1025538,
 ('Nagapattinam ', 'Tamil Nadu'): 942202,
 ('Thanjavur', 'Tamil Nadu'): 1012258,
 ('Sivaganga', 'Tamil Nadu'): 1027036,
 ('Madurai', 'Tamil Nadu'): 974809,
 ('Theni ', 'Tamil Nadu'): 1075583,
 ('Virudhunagar', 'Tamil Nadu'): 1010930,
 ('Ramanathapuram', 'Tamil Nadu'): 1001048,
 ('Thoothukkudi', 'Tamil Nadu'): 916778,
 ('Tenkasi ', 'Tamil Nadu'): 1017938,
 ('Tirunelveli', 'Tamil Nadu'): 962330,
 ('Kanniyakumari', 'Tamil Nadu'): 990742,
 ('Tripura West', 'Tripura'): 1072749,
 ('Tripura East', 'Tripura'): 951080,
 ('Saharanpur', 'Uttar Pradesh'): 1194308,
 ('Kairana', 'Uttar Pradesh'): 1119324,
 ('Muzaffarnagar', 'Uttar Pradesh'): 1107434,
 ('Bijnor', 'Uttar Pradesh'): 1060346,
 ('Nagina', 'Uttar Pradesh'): 942196,
 ('Moradabad', 'Uttar Pradesh'): 1127965,
 ('Rampur', 'Uttar Pradesh'): 956389,
 ('Sambhal', 'Uttar Pradesh'): 1057002,
 ('Amroha', 'Uttar Pradesh'): 1095860,
 ('Meerut', 'Uttar Pradesh'): 1113384,
 ('Baghpat', 'Uttar Pradesh'): 1004263,
 ('Ghaziabad', 'Uttar Pradesh'): 1342321,
 ('Gautam Buddha Nagar', 'Uttar Pradesh'): 1199262,
 ('Bulandshahr', 'Uttar Pradesh'): 1009710,
 ('Aligarh', 'Uttar Pradesh'): 1064357,
 ('Hathras', 'Uttar Pradesh'): 1049273,
 ('Mathura', 'Uttar Pradesh'): 1076868,
 ('Agra', 'Uttar Pradesh'): 1070400,
 ('Fatehpur Sikri', 'Uttar Pradesh'): 967968,
 ('Firozabad', 'Uttar Pradesh'): 1104606,
 ('Mainpuri', 'Uttar Pradesh'): 999265,
 ('Etah', 'Uttar Pradesh'): 926281,
 ('Badaun', 'Uttar Pradesh'): 1027594,
 ('Aonla', 'Uttar Pradesh'): 995641,
 ('Bareilly', 'Uttar Pradesh'): 1017891,
 ('Pilibhit', 'Uttar Pradesh'): 1050547,
 ('Shahjahanpur', 'Uttar Pradesh'): 1129841,
 ('Kheri', 'Uttar Pradesh'): 1077868,
 ('Dhaurahra', 'Uttar Pradesh'): 1060271,
 ('Sitapur', 'Uttar Pradesh'): 1026972,
 ('Hardoi', 'Uttar Pradesh'): 972896,
 ('Misrikh', 'Uttar Pradesh'): 998314,
 ('Unnao', 'Uttar Pradesh'): 1201603,
 ('Mohanlalganj', 'Uttar Pradesh'): 1116588,
 ('Lucknow', 'Uttar Pradesh'): 1033883,
 ('Rae Bareli', 'Uttar Pradesh'): 825136,
 ('Amethi', 'Uttar Pradesh'): 874625,
 ('Sultanpur', 'Uttar Pradesh'): 964981,
 ('Pratapgarh', 'Uttar Pradesh'): 894456,
 ('Farrukhabad', 'Uttar Pradesh'): 970677,
 ('Etawah', 'Uttar Pradesh'): 939604,
 ('Kannauj', 'Uttar Pradesh'): 1114460,
 ('Kanpur', 'Uttar Pradesh'): 835079,
 ('Akbarpur', 'Uttar Pradesh'): 971375,
 ('Jalaun', 'Uttar Pradesh'): 1109166,
 ('Jhansi', 'Uttar Pradesh'): 1320804,
 ('Banda', 'Uttar Pradesh'): 858326,
 ('Fatehpur', 'Uttar Pradesh'): 1056688,
 ('Kaushambi', 'Uttar Pradesh'): 910414,
 ('Phulpur', 'Uttar Pradesh'): 960341,
 ('Allahabad', 'Uttar Pradesh'): 891586,
 ('Barabanki', 'Uttar Pradesh'): 1068168,
 ('Faizabad', 'Uttar Pradesh'): 1022716,
 ('Ambedkar Nagar', 'Uttar Pradesh'): 1034404,
 ('Bahraich', 'Uttar Pradesh'): 934263,
 ('Kaiserganj', 'Uttar Pradesh'): 943357,
 ('Shrawasti', 'Uttar Pradesh'): 979638,
 ('Gonda', 'Uttar Pradesh'): 873728,
 ('Domariyaganj', 'Uttar Pradesh'): 935027,
 ('Basti', 'Uttar Pradesh'): 1048534,
 ('Sant Kabir Nagar', 'Uttar Pradesh'): 1011649,
 ('Gorakhpur', 'Uttar Pradesh'): 1040199,
 ('Kushi Nagar', 'Uttar Pradesh'): 950446,
 ('Deoria', 'Uttar Pradesh'): 971557,
 ('Bansgaon', 'Uttar Pradesh'): 877877,
 ('Lalganj', 'Uttar Pradesh'): 898655,
 ('Azamgarh', 'Uttar Pradesh'): 960218,
 ('Ghosi', 'Uttar Pradesh'): 1039656,
 ('Salempur', 'Uttar Pradesh'): 854749,
 ('Ballia', 'Uttar Pradesh'): 942211,
 ('Jaunpur', 'Uttar Pradesh'): 1007143,
 ('Machhlishahr', 'Uttar Pradesh'): 997902,
 ('Ghazipur', 'Uttar Pradesh'): 986673,
 ('Chandauli', 'Uttar Pradesh'): 980572,
 ('Varanasi', 'Uttar Pradesh'): 1030685,
 ('Bhadohi', 'Uttar Pradesh'): 981866,
 ('Mirzapur', 'Uttar Pradesh'): 1007627,
 ('Robertsganj', 'Uttar Pradesh'): 885873,
 ('Cooch behar', 'West Bengal'): 1332409,
 ('Alipurduars', 'West Bengal'): 1223566,
 ('Jalpaiguri', 'West Bengal'): 1302117,
 ('Darjeeling', 'West Bengal'): 1142009,
 ('Raiganj', 'West Bengal'): 1108193,
 ('Balurghat', 'West Bengal'): 1063053,
 ('Maldaha Uttar', 'West Bengal'): 1162985,
 ('Maldaha Dakshin', 'West Bengal'): 1092407,
 ('Jangipur', 'West Bengal'): 1119084,
 ('Baharampur', 'West Bengal'): 1154587,
 ('Murshidabad', 'West Bengal'): 1287763,
 ('Krishnanagar', 'West Bengal'): 1247914,
 ('Ranaghat', 'West Bengal'): 1353196,
 ('Bangaon', 'West Bengal'): 1283688,
 ('Barrackpore', 'West Bengal'): 1051130,
 ('Dum dum', 'West Bengal'): 1132644,
 ('Barasat', 'West Bengal'): 1269331,
 ('Basirhat', 'West Bengal'): 1273771,
 ('Joynagar', 'West Bengal'): 1189048,
 ('Mathurapur', 'West Bengal'): 1270985,
 ('Diamond harbour', 'West Bengal'): 1261296,
 ('Jadavpur', 'West Bengal'): 1272362,
 ('Kolkata Dakshin', 'West Bengal'): 1167986,
 ('Kolkata Uttar', 'West Bengal'): 955778,
 ('Howrah', 'West Bengal'): 1125399,
 ('Uluberia', 'West Bengal'): 1186027,
 ('Srerampur', 'West Bengal'): 1290433,
 ('Hooghly', 'West Bengal'): 1348870,
 ('Arambagh', 'West Bengal'): 1361934,
 ('Tamluk', 'West Bengal'): 1337684,
 ('Kanthi', 'West Bengal'): 1290811,
 ('Ghatal', 'West Bengal'): 1366909,
 ('Jhargram', 'West Bengal'): 1257613,
 ('Medinipur', 'West Bengal'): 1260748,
 ('Purulia', 'West Bengal'): 1204675,
 ('Bankura', 'West Bengal'): 1236319,
 ('Bishnupur', 'West Bengal'): 1272070,
 ('Bardhaman Purba', 'West Bengal'): 1320822,
 ('Burdwan - durgapur', 'West Bengal'): 1331242,
 ('Asansol', 'West Bengal'): 1142395,
 ('Bolpur', 'West Bengal'): 1304756,
 ('Birbhum', 'West Bengal'): 1275819,
 ('Rajmahal', 'Jharkhand'): 951563,
 ('Dumka', 'Jharkhand'): 903060,
 ('Godda', 'Jharkhand'): 1049442,
 ('Chatra', 'Jharkhand'): 712971,
 ('Kodarma', 'Jharkhand'): 1024906,
 ('Giridih', 'Jharkhand'): 969997,
 ('Dhanbad', 'Jharkhand'): 1143902,
 ('Ranchi', 'Jharkhand'): 1049783,
 ('Jamshedpur', 'Jharkhand'): 1049140,
 ('Singhbhum', 'Jharkhand'): 795286,
 ('Khunti', 'Jharkhand'): 736955,
 ('Lohardaga', 'Jharkhand'): 651460,
 ('Palamau', 'Jharkhand'): 977323,
 ('Hazaribagh', 'Jharkhand'): 967152,
 ('Tehri Garhwal', 'Uttarakhand'): 776214,
 ('Garhwal', 'Uttarakhand'): 682024,
 ('Almora', 'Uttarakhand'): 656525,
 ('Nainital-udhamsingh Nagar', 'Uttarakhand'): 1101435,
 ('Hardwar', 'Uttarakhand'): 1175692,
 ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'): 190328,
 ('CHANDIGARH', 'Chandigarh'): 453455,
 ('Dadar & Nagar Haveli', 'Dadra & Nagar Haveli'): 165286,
 ('Daman & diu', 'Daman & Diu'): 87233,
 ('CHANDNI CHOWK                 ', 'NCT OF Delhi'): 981863,
 ('NORTH EAST DELHI              ', 'NCT OF Delhi'): 1317338,
 ('EAST DELHI                    ', 'NCT OF Delhi'): 1196336,
 ('NEW DELHI                     ', 'NCT OF Delhi'): 969812,
 ('NORTH WEST DELHI              ', 'NCT OF Delhi'): 1356036,
 ('WEST DELHI                    ', 'NCT OF Delhi'): 1347971,
 ('SOUTH DELHI                   ', 'NCT OF Delhi'): 1102410,
 ('Lakshadweep', 'Lakshadweep'): 43239,
 ('Puducherry', 'Puducherry'): 740017}

In [14]:
# Initialize the "Total_vote_pc" column with zeros
df14["Total_vote_pc"] = 0

# Iterate over the dictionary items and assign values to the DataFrame
for key, value in Total_vote_pc.items():
    pc_name, state = key
    df14.loc[(df14["state"] == state) & (df14["pc_name"] == pc_name), "Total_vote_pc"] = value

df14

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors,Total_vote_pc
0,Telangana,Adilabad,GODAM NAGESH,M,49.0,ST,TRS,Car,425762,5085,430847,1386282,1045839
1,Telangana,Adilabad,NARESH,M,37.0,ST,INC,Hand,257994,1563,259557,1386282,1045839
2,Telangana,Adilabad,RAMESH RATHOD,M,48.0,ST,TDP,Bicycle,182879,1319,184198,1386282,1045839
3,Telangana,Adilabad,RATHOD SADASHIV,M,55.0,ST,BSP,Elephant,94363,57,94420,1386282,1045839
4,Telangana,Adilabad,NETHAWATH RAMDAS,M,44.0,ST,IND,Auto- Rickshaw,41028,4,41032,1386282,1045839
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8350,Puducherry,Puducherry,PUVALA NAGESWARA RAO,M,60.0,GEN,IND,Sewing Machine,465,0,465,901357,740017
8351,Puducherry,Puducherry,K. MANJINI,M,41.0,GEN,IND,Coconut,767,0,767,901357,740017
8352,Puducherry,Puducherry,R. VALAVAN,M,40.0,GEN,IND,Carrom Board,497,0,497,901357,740017
8353,Puducherry,Puducherry,V. VIJAYA,F,29.0,GEN,IND,Green Chilli,746,0,746,901357,740017
8354,Puducherry,Puducherry,None of the Above,NaN,NaN,NaN,NOTA,NOTA,22267,1,22268,901357,740017

In [15]:
df14["Voter Turnout Ratio"] = df14["Total_vote_pc"]/df14["total_electors"]
df14

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio
0,Telangana,Adilabad,GODAM NAGESH,M,49.0,ST,TRS,Car,425762,5085,430847,1386282,1045839,0.754420
1,Telangana,Adilabad,NARESH,M,37.0,ST,INC,Hand,257994,1563,259557,1386282,1045839,0.754420
2,Telangana,Adilabad,RAMESH RATHOD,M,48.0,ST,TDP,Bicycle,182879,1319,184198,1386282,1045839,0.754420
3,Telangana,Adilabad,RATHOD SADASHIV,M,55.0,ST,BSP,Elephant,94363,57,94420,1386282,1045839,0.754420
4,Telangana,Adilabad,NETHAWATH RAMDAS,M,44.0,ST,IND,Auto- Rickshaw,41028,4,41032,1386282,1045839,0.754420
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8350,Puducherry,Puducherry,PUVALA NAGESWARA RAO,M,60.0,GEN,IND,Sewing Machine,465,0,465,901357,740017,0.821003
8351,Puducherry,Puducherry,K. MANJINI,M,41.0,GEN,IND,Coconut,767,0,767,901357,740017,0.821003
8352,Puducherry,Puducherry,R. VALAVAN,M,40.0,GEN,IND,Carrom Board,497,0,497,901357,740017,0.821003
8353,Puducherry,Puducherry,V. VIJAYA,F,29.0,GEN,IND,Green Chilli,746,0,746,901357,740017,0.821003
8354,Puducherry,Puducherry,None of the Above,NaN,NaN,NaN,NOTA,NOTA,22267,1,22268,901357,740017,0.821003

In [16]:
Top_5_2014 = sorted(df14["Voter Turnout Ratio"].unique())[-5:]
Top_5_2014

[0.8661311646168022,
 0.8671700793703274,
 0.8758643674051725,
 0.8782202790936725,
 0.8835337634808144]

In [17]:
Bottom_5_2014 = sorted(df14["Voter Turnout Ratio"].unique())[:5]
Bottom_5_2014

[0.2586184902628331,
 0.2884225638534734,
 0.3913380126741946,
 0.42881447466590084,
 0.45331404152295]

## Cleaning and adding Voter Turnout Ratio to data frame of 2019 AKA df19

### Two states can have same name pc_name like ['Maharajganj', 'Aurangabad', 'Hamirpur']

In [18]:
# Total vote per pc_name
Total_vote_pc = dict()
# filtering all parliament constituency
for pc in df19.pc_name.unique():
    pcdf = df19[df19["pc_name"]==pc]
    # filtering to check if parliament constituency is in two states 
    for state in pcdf.state.unique():
        total = 0
        s_pcdf = pcdf[pcdf["state"]==state]
        for i in range(len(s_pcdf)):
            total += s_pcdf.iloc[i,10]
        Total_vote_pc[(pc, state)] = total
Total_vote_pc

{('Aruku ', 'Andhra Pradesh'): 1074538,
 ('Srikakulam', 'Andhra Pradesh'): 1157329,
 ('Vizianagaram', 'Andhra Pradesh'): 1217890,
 ('Visakhapatnam', 'Andhra Pradesh'): 1239754,
 ('Anakapalli', 'Andhra Pradesh'): 1238491,
 ('Kakinada', 'Andhra Pradesh'): 1234655,
 ('Amalapuram ', 'Andhra Pradesh'): 1232895,
 ('Rajahmundry', 'Andhra Pradesh'): 1250427,
 ('Narsapuram', 'Andhra Pradesh'): 1177738,
 ('Eluru ', 'Andhra Pradesh'): 1327923,
 ('Machilipatnam ', 'Andhra Pradesh'): 1244570,
 ('Vijayawada', 'Andhra Pradesh'): 1277711,
 ('Guntur', 'Andhra Pradesh'): 1351474,
 ('Narasaraopet', 'Andhra Pradesh'): 1437420,
 ('Bapatla ', 'Andhra Pradesh'): 1266492,
 ('Ongole ', 'Andhra Pradesh'): 1342368,
 ('Nandyal', 'Andhra Pradesh'): 1299093,
 ('Kurnool', 'Andhra Pradesh'): 1188327,
 ('Anantapur', 'Andhra Pradesh'): 1342306,
 ('Hindupur', 'Andhra Pradesh'): 1338514,
 ('Kadapa', 'Andhra Pradesh'): 1228242,
 ('Nellore', 'Andhra Pradesh'): 1287036,
 ('Tirupati ', 'Andhra Pradesh'): 1313515,
 ('Rajampet', 'Andhra Pradesh'): 1224354,
 ('Chittoor ', 'Andhra Pradesh'): 1319472,
 ('ARUNACHAL WEST', 'Arunachal Pradesh'): 358310,
 ('ARUNACHAL EAST', 'Arunachal Pradesh'): 293781,
 ('Karimganj ', 'Assam'): 1060072,
 ('Silchar', 'Assam'): 949696,
 ('Autonomous District', 'Assam'): 617735,
 ('Dhubri', 'Assam'): 1685005,
 ('Kokrajhar', 'Assam'): 1479485,
 ('Barpeta', 'Assam'): 1458549,
 ('Gauhati', 'Assam'): 1763757,
 ('Mangaldoi', 'Assam'): 1506107,
 ('Tezpur', 'Assam'): 1190196,
 ('Nowgong', 'Assam'): 1493475,
 ('Kaliabor', 'Assam'): 1424687,
 ('Jorhat', 'Assam'): 1057965,
 ('Dibrugarh', 'Assam'): 1015748,
 ('Lakhimpur', 'Assam'): 1283589,
 ('Valmiki Nagar', 'Bihar'): 1032090,
 ('Paschim Champaran', 'Bihar'): 1012936,
 ('Purvi Champaran', 'Bihar'): 999400,
 ('Sheohar', 'Bihar'): 1004559,
 ('Sitamarhi', 'Bihar'): 1038849,
 ('Madhubani', 'Bihar'): 963708,
 ('Jhanjharpur', 'Bihar'): 1060562,
 ('Supaul', 'Bihar'): 1110805,
 ('Araria', 'Bihar'): 1169630,
 ('Kishanganj', 'Bihar'): 1101603,
 ('Katihar', 'Bihar'): 1117734,
 ('Purnia', 'Bihar'): 1153940,
 ('Madhepura', 'Bihar'): 1147274,
 ('Darbhanga', 'Bihar'): 964996,
 ('Muzaffarpur', 'Bihar'): 1058086,
 ('Vaishali', 'Bihar'): 1074730,
 ('Gopalganj (SC)', 'Bihar'): 1024876,
 ('Siwan', 'Bihar'): 984810,
 ('Maharajganj', 'Bihar'): 972703,
 ('Maharajganj', 'Uttar Pradesh'): 1226916,
 ('Saran', 'Bihar'): 943020,
 ('Hajipur (SC)', 'Bihar'): 1006817,
 ('Ujiarpur', 'Bihar'): 969284,
 ('Samastipur (SC)', 'Bihar'): 1019025,
 ('Begusarai', 'Bihar'): 1225594,
 ('Khagaria', 'Bihar'): 966813,
 ('Bhagalpur', 'Bihar'): 1042518,
 ('Banka', 'Bihar'): 995806,
 ('Munger', 'Bihar'): 1036268,
 ('Nalanda', 'Bihar'): 1031286,
 ('Patna Sahib', 'Bihar'): 982285,
 ('Pataliputra', 'Bihar'): 1077749,
 ('Arrah', 'Bihar'): 1080684,
 ('Buxar', 'Bihar'): 986861,
 ('Sasaram (SC)', 'Bihar'): 974749,
 ('Karakat', 'Bihar'): 868798,
 ('Jahanabad', 'Bihar'): 822065,
 ('Aurangabad', 'Bihar'): 934901,
 ('Aurangabad', 'Maharashtra'): 1198221,
 ('Gaya (SC)', 'Bihar'): 957248,
 ('Nawada', 'Bihar'): 942462,
 ('Jamui (SC)', 'Bihar'): 949137,
 ('North Goa', 'Goa'): 428628,
 ('South Goa', 'Goa'): 424575,
 ('Kachchh', 'Gujarat'): 1023198,
 ('Banaskantha', 'Gujarat'): 1102081,
 ('Patan', 'Gujarat'): 1126256,
 ('Mahesana', 'Gujarat'): 1081938,
 ('Sabarkantha', 'Gujarat'): 1218353,
 ('Gandhinagar', 'Gujarat'): 1284090,
 ('Ahmedabad East', 'Gujarat'): 1116367,
 ('Ahmedabad West', 'Gujarat'): 997024,
 ('Surendranagar', 'Gujarat'): 1077726,
 ('Rajkot', 'Gujarat'): 1195271,
 ('Porbandar', 'Gujarat'): 949947,
 ('Jamnagar', 'Gujarat'): 1010965,
 ('Junagadh', 'Gujarat'): 1004743,
 ('Amreli', 'Gujarat'): 909167,
 ('Bhavnagar', 'Gujarat'): 1041279,
 ('Anand', 'Gujarat'): 1108661,
 ('Kheda', 'Gujarat'): 1098633,
 ('Panchmahal', 'Gujarat'): 1083676,
 ('Dahod', 'Gujarat'): 1063212,
 ('Vadodara', 'Gujarat'): 1222348,
 ('Chhota Udaipur', 'Gujarat'): 1232459,
 ('Bharuch', 'Gujarat'): 1149725,
 ('Bardoli', 'Gujarat'): 1348038,
 ('Surat', 'Gujarat'): 1068412,
 ('Navsari', 'Gujarat'): 1308018,
 ('Valsad', 'Gujarat'): 1260377,
 ('Ambala', 'Haryana'): 1316235,
 ('Kurukshetra', 'Haryana'): 1230202,
 ('Sirsa', 'Haryana'): 1369486,
 ('Hisar', 'Haryana'): 1179869,
 ('Karnal', 'Haryana'): 1300722,
 ('Sonipat', 'Haryana'): 1129532,
 ('Rohtak', 'Haryana'): 1220571,
 ('Bhiwani-Mahendragarh', 'Haryana'): 1161115,
 ('Gurgaon', 'Haryana'): 1446509,
 ('Faridabad', 'Haryana'): 1327295,
 ('Kangra', 'Himachal Pradesh'): 1006989,
 ('Mandi', 'Himachal Pradesh'): 941371,
 ('Hamirpur', 'Himachal Pradesh'): 988765,
 ('Hamirpur', 'Uttar Pradesh'): 1089778,
 ('Shimla', 'Himachal Pradesh'): 913607,
 ('Baramulla', 'Jammu & Kashmir'): 455550,
 ('Srinagar', 'Jammu & Kashmir'): 186832,
 ('Anantnag', 'Jammu & Kashmir'): 124896,
 ('Ladakh', 'Jammu & Kashmir'): 126426,
 ('Udhampur', 'Jammu & Kashmir'): 1180123,
 ('Jammu', 'Jammu & Kashmir'): 1478795,
 ('Chikkodi', 'Karnataka'): 1217549,
 ('Belgaum', 'Karnataka'): 1205229,
 ('Bagalkot', 'Karnataka'): 1204613,
 ('Bijapur', 'Karnataka'): 1111354,
 ('Gulbarga', 'Karnataka'): 1189361,
 ('Raichur', 'Karnataka'): 1124385,
 ('Bidar', 'Karnataka'): 1117167,
 ('Koppal', 'Karnataka'): 1190347,
 ('Bellary', 'Karnataka'): 1221926,
 ('Haveri', 'Karnataka'): 1266679,
 ('Dharwad', 'Karnataka'): 1213505,
 ('Uttara Kannada', 'Karnataka'): 1153480,
 ('Davanagere', 'Karnataka'): 1194586,
 ('Shimoga', 'Karnataka'): 1283577,
 ('Udupi Chikmagalur', 'Karnataka'): 1151012,
 ('Hassan', 'Karnataka'): 1277552,
 ('Dakshina Kannada', 'Karnataka'): 1345039,
 ('Chitradurga', 'Karnataka'): 1245950,
 ('Tumkur', 'Karnataka'): 1244858,
 ('Mandya', 'Karnataka'): 1379210,
 ('Mysore', 'Karnataka'): 1318041,
 ('Chamarajanagar', 'Karnataka'): 1270658,
 ('Bangalore Rural', 'Karnataka'): 1621906,
 ('Bangalore North', 'Karnataka'): 1559459,
 ('Bangalore central', 'Karnataka'): 1197234,
 ('Bangalore South', 'Karnataka'): 1188491,
 ('Chikkballapur', 'Karnataka'): 1386963,
 ('Kolar', 'Karnataka'): 1258551,
 ('Kasaragod', 'Kerala'): 1100051,
 ('Kannur', 'Kerala'): 1053842,
 ('Vadakara', 'Kerala'): 1065619,
 ('Wayanad', 'Kerala'): 1092197,
 ('Kozhikode', 'Kerala'): 1076193,
 ('Malappuram', 'Kerala'): 1034618,
 ('Ponnani', 'Kerala'): 1017265,
 ('Palakkad', 'Kerala'): 1028249,
 ('Alathur ', 'Kerala'): 1018743,
 ('Thrissur', 'Kerala'): 1041869,
 ('Chalakudy', 'Kerala'): 990224,
 ('Ernakulam', 'Kerala'): 967203,
 ('Idukki', 'Kerala'): 919297,
 ('Kottayam', 'Kerala'): 910339,
 ('Alappuzha', 'Kerala'): 1088728,
 ('Mavelikkara ', 'Kerala'): 971035,
 ('Pathanamthitta', 'Kerala'): 1026553,
 ('Kollam', 'Kerala'): 968123,
 ('Attingal', 'Kerala'): 1004888,
 ('Thiruvananthapuram', 'Kerala'): 1010180,
 ('MORENA', 'Madhya Pradesh'): 1137290,
 ('BHIND', 'Madhya Pradesh'): 960687,
 ('GWALIOR', 'Madhya Pradesh'): 1196096,
 ('GUNA', 'Madhya Pradesh'): 1178423,
 ('SAGAR', 'Madhya Pradesh'): 1037175,
 ('TIKAMGARH', 'Madhya Pradesh'): 1096712,
 ('DAMOH', 'Madhya Pradesh'): 1164226,
 ('KHAJURAHO', 'Madhya Pradesh'): 1257783,
 ('SATNA', 'Madhya Pradesh'): 1113656,
 ('REWA', 'Madhya Pradesh'): 1013251,
 ('SIDHI', 'Madhya Pradesh'): 1282705,
 ('SHAHDOL', 'Madhya Pradesh'): 1237858,
 ('JABALPUR', 'Madhya Pradesh'): 1263573,
 ('MANDLA', 'Madhya Pradesh'): 1517255,
 ('BALAGHAT', 'Madhya Pradesh'): 1372018,
 ('CHHINDWARA', 'Madhya Pradesh'): 1248031,
 ('HOSHANGABAD', 'Madhya Pradesh'): 1265869,
 ('VIDISHA', 'Madhya Pradesh'): 1250244,
 ('BHOPAL', 'Madhya Pradesh'): 1407954,
 ('RAJGARH', 'Madhya Pradesh'): 1260329,
 ('DEWAS', 'Madhya Pradesh'): 1398946,
 ('UJJAIN', 'Madhya Pradesh'): 1252511,
 ('MANDSOUR', 'Madhya Pradesh'): 1370667,
 ('RATLAM', 'Madhya Pradesh'): 1400509,
 ('DHAR', 'Madhya Pradesh'): 1344132,
 ('INDORE', 'Madhya Pradesh'): 1629108,
 ('KHARGONE', 'Madhya Pradesh'): 1427607,
 ('KHANDWA', 'Madhya Pradesh'): 1468138,
 ('BETUL', 'Madhya Pradesh'): 1357857,
 ('Nandurbar ', 'Maharashtra'): 1281738,
 ('Dhule', 'Maharashtra'): 1085038,
 ('Jalgaon', 'Maharashtra'): 1088277,
 ('Raver', 'Maharashtra'): 1092971,
 ('Buldhana', 'Maharashtra'): 1120359,
 ('Akola', 'Maharashtra'): 1119440,
 ('Amravati ', 'Maharashtra'): 1112385,
 ('Wardha', 'Maharashtra'): 1072570,
 ('Ramtek ', 'Maharashtra'): 1196744,
 ('Nagpur ', 'Maharashtra'): 1186051,
 ('Bhandara - gondiya', 'Maharashtra'): 1244931,
 ('Gadchiroli-Chimur', 'Maharashtra'): 1142698,
 ('Chandrapur', 'Maharashtra'): 1238474,
 ('Yavatmal-Washim', 'Maharashtra'): 1174220,
 ('Hingoli ', 'Maharashtra'): 1157516,
 ('Nanded', 'Maharashtra'): 1129350,
 ('Parbhani', 'Maharashtra'): 1252782,
 ('Jalna', 'Maharashtra'): 1208139,
 ('Dindori ', 'Maharashtra'): 1137631,
 ('Nashik', 'Maharashtra'): 1121232,
 ('Palghar ', 'Maharashtra'): 1201941,
 ('Bhiwandi', 'Maharashtra'): 1005172,
 ('Kalyan', 'Maharashtra'): 890313,
 ('Thane', 'Maharashtra'): 1170518,
 ('Mumbai North', 'Maharashtra'): 989759,
 ('Mumbai North West', 'Maharashtra'): 941497,
 ('Mumbai North East', 'Maharashtra'): 908993,
 ('Mumbai North central', 'Maharashtra'): 901784,
 ('Mumbai South central', 'Maharashtra'): 797250,
 ('Mumbai   South', 'Maharashtra'): 801611,
 ('Raigad', 'Maharashtra'): 1025467,
 ('Maval', 'Maharashtra'): 1368872,
 ('Pune', 'Maharashtra'): 1035236,
 ('Baramati', 'Maharashtra'): 1304728,
 ('Shirur', 'Maharashtra'): 1293117,
 ('Ahmadnagar ', 'Maharashtra'): 1203797,
 ('Shirdi', 'Maharashtra'): 1029362,
 ('Beed', 'Maharashtra'): 1352399,
 ('Osmanabad', 'Maharashtra'): 1204730,
 ('Latur ', 'Maharashtra'): 1176542,
 ('Solapur ', 'Maharashtra'): 1084514,
 ('Madha', 'Maharashtra'): 1216319,
 ('Sangli', 'Maharashtra'): 1189958,
 ('Satara', 'Maharashtra'): 1115434,
 ('Ratnagiri - sindhudurg', 'Maharashtra'): 901102,
 ('Kolhapur', 'Maharashtra'): 1330852,
 ('Hatkanangle', 'Maharashtra'): 1252211,
 ('Inner manipur', 'Manipur'): 759301,
 ('Outer manipur', 'Manipur'): 858029,
 ('Shillong', 'Meghalaya'): 784190,
 ('Tura ', 'Meghalaya'): 583041,
 ('MIZORAM', 'Mizoram'): 499621,
 ('Nagaland', 'Nagaland'): 1006357,
 ('Bargarh', 'Odisha'): 1247912,
 ('Sundargarh ', 'Odisha'): 1100129,
 ('Sambalpur', 'Odisha'): 1124455,
 ('Keonjhar ', 'Odisha'): 1176292,
 ('Mayurbhanj ', 'Odisha'): 1150357,
 ('Balasore', 'Odisha'): 1157871,
 ('Bhadrak ', 'Odisha'): 1225156,
 ('Jajpur ', 'Odisha'): 1092084,
 ('Dhenkanal', 'Odisha'): 1131522,
 ('Bolangir', 'Odisha'): 1306705,
 ('Kalahandi', 'Odisha'): 1228292,
 ('Nabarangpur ', 'Odisha'): 1159700,
 ('Kandhamal', 'Odisha'): 941985,
 ('Cuttack', 'Odisha'): 1059490,
 ('Kendrapara ', 'Odisha'): 1238214,
 ('Jagatsinghpur ', 'Odisha'): 1229190,
 ('Puri', 'Odisha'): 1135620,
 ('Bhubaneswar', 'Odisha'): 1005215,
 ('Aska', 'Odisha'): 1013862,
 ('Berhampur', 'Odisha'): 989910,
 ('Koraput ', 'Odisha'): 1080161,
 ('Gurdaspur', 'Punjab'): 1103887,
 ('Amritsar', 'Punjab'): 859513,
 ('Khadoor Sahib', 'Punjab'): 1046032,
 ('Jalandhar', 'Punjab'): 1018998,
 ('Hoshiarpur', 'Punjab'): 990791,
 ('Anandpur Sahib', 'Punjab'): 1081727,
 ('Ludhiana', 'Punjab'): 1046955,
 ('Fatehgarh Sahib', 'Punjab'): 985948,
 ('Faridkot', 'Punjab'): 974947,
 ('Firozpur', 'Punjab'): 1172033,
 ('Bathinda', 'Punjab'): 1200810,
 ('Sangrur', 'Punjab'): 1105888,
 ('Patiala', 'Punjab'): 1177903,
 ('Ganganagar', 'Rajasthan'): 1451765,
 ('Bikaner (SC)', 'Rajasthan'): 1099598,
 ('Churu', 'Rajasthan'): 1328422,
 ('Jhunjhunu', 'Rajasthan'): 1198927,
 ('Sikar', 'Rajasthan'): 1326969,
 ('Jaipur Rural', 'Rajasthan'): 1276693,
 ('Jaipur', 'Rajasthan'): 1456404,
 ('Alwar', 'Rajasthan'): 1265674,
 ('BHARATPUR', 'Rajasthan'): 1146797,
 ('KARAULI-DHOLPUR', 'Rajasthan'): 998044,
 ('Dausa', 'Rajasthan'): 1062834,
 ('TONK-SAWAI MADHOPUR', 'Rajasthan'): 1233458,
 ('Ajmer', 'Rajasthan'): 1262214,
 ('Nagaur', 'Rajasthan'): 1203124,
 ('Pali', 'Rajasthan'): 1359799,
 ('Jodhpur', 'Rajasthan'): 1346243,
 ('Barmer', 'Rajasthan'): 1422271,
 ('Jalore', 'Rajasthan'): 1361619,
 ('Udaipur', 'Rajasthan'): 1454518,
 ('Banswara', 'Rajasthan'): 1439671,
 ('Chittorgarh', 'Rajasthan'): 1458760,
 ('Rajsamand', 'Rajasthan'): 1239845,
 ('Bhilwara', 'Rajasthan'): 1310513,
 ('Kota', 'Rajasthan'): 1367034,
 ('JHALAWAR-BARAN', 'Rajasthan'): 1369868,
 ('Sikkim', 'Sikkim'): 351746,
 ('Thiruvallur ', 'Tamil Nadu'): 1408189,
 ('Chennai North', 'Tamil Nadu'): 955545,
 ('Chennai South', 'Tamil Nadu'): 1125857,
 ('Chennai central', 'Tamil Nadu'): 785450,
 ('Sriperumbudur', 'Tamil Nadu'): 1406782,
 ('Kancheepuram ', 'Tamil Nadu'): 1237612,
 ('Arakkonam', 'Tamil Nadu'): 1178060,
 ('Vellore', 'Tamil Nadu'): 1026055,
 ('Krishnagiri', 'Tamil Nadu'): 1161369,
 ('Dharmapuri', 'Tamil Nadu'): 1223205,
 ('Tiruvannamalai', 'Tamil Nadu'): 1151729,
 ('Arani', 'Tamil Nadu'): 1143907,
 ('Viluppuram', 'Tamil Nadu'): 1135540,
 ('Kallakurichi', 'Tamil Nadu'): 1204375,
 ('Salem', 'Tamil Nadu'): 1255459,
 ('Namakkal', 'Tamil Nadu'): 1133774,
 ('Erode', 'Tamil Nadu'): 1067863,
 ('Tiruppur', 'Tamil Nadu'): 1119584,
 ('Nilgiris ', 'Tamil Nadu'): 1010719,
 ('Coimbatore', 'Tamil Nadu'): 1250885,
 ('Pollachi', 'Tamil Nadu'): 1081875,
 ('Dindigul', 'Tamil Nadu'): 1160046,
 ('Karur', 'Tamil Nadu'): 1103165,
 ('Tiruchirappalli', 'Tamil Nadu'): 1048062,
 ('Perambalur', 'Tamil Nadu'): 1102767,
 ('Cuddalore ', 'Tamil Nadu'): 1043202,
 ('Chidambaram ', 'Tamil Nadu'): 1153192,
 ('Mayiladuthurai', 'Tamil Nadu'): 1097243,
 ('Nagapattinam ', 'Tamil Nadu'): 1002208,
 ('Thanjavur', 'Tamil Nadu'): 1059223,
 ('Sivaganga', 'Tamil Nadu'): 1084468,
 ('Madurai', 'Tamil Nadu'): 1016026,
 ('Theni ', 'Tamil Nadu'): 1173489,
 ('Virudhunagar', 'Tamil Nadu'): 1074735,
 ('Ramanathapuram', 'Tamil Nadu'): 1066146,
 ('Thoothukkudi', 'Tamil Nadu'): 991263,
 ('Tenkasi ', 'Tamil Nadu'): 1065088,
 ('Tirunelveli', 'Tamil Nadu'): 1040350,
 ('Kanniyakumari', 'Tamil Nadu'): 1048377,
 ('Tripura West', 'Tripura'): 1107755,
 ('Tripura East', 'Tripura'): 1045417,
 ('Saharanpur', 'Uttar Pradesh'): 1231746,
 ('Kairana', 'Uttar Pradesh'): 1124047,
 ('Muzaffarnagar', 'Uttar Pradesh'): 1160071,
 ('Bijnor', 'Uttar Pradesh'): 1100763,
 ('Nagina', 'Uttar Pradesh'): 1009456,
 ('Moradabad', 'Uttar Pradesh'): 1282206,
 ('Rampur', 'Uttar Pradesh'): 1060921,
 ('Sambhal', 'Uttar Pradesh'): 1183469,
 ('Amroha', 'Uttar Pradesh'): 1169182,
 ('Meerut', 'Uttar Pradesh'): 1216413,
 ('Baghpat', 'Uttar Pradesh'): 1044894,
 ('Ghaziabad', 'Uttar Pradesh'): 1524456,
 ('Gautam Buddha Nagar', 'Uttar Pradesh'): 1392952,
 ('Bulandshahr', 'Uttar Pradesh'): 1123629,
 ('Aligarh', 'Uttar Pradesh'): 1163184,
 ('Hathras', 'Uttar Pradesh'): 1150294,
 ('Mathura', 'Uttar Pradesh'): 1102731,
 ('Agra', 'Uttar Pradesh'): 1145323,
 ('Fatehpur Sikri', 'Uttar Pradesh'): 1037151,
 ('Firozabad', 'Uttar Pradesh'): 1075866,
 ('Mainpuri', 'Uttar Pradesh'): 976518,
 ('Etah', 'Uttar Pradesh'): 999607,
 ('Badaun', 'Uttar Pradesh'): 1081111,
 ('Aonla', 'Uttar Pradesh'): 1052795,
 ('Bareilly', 'Uttar Pradesh'): 1068342,
 ('Pilibhit', 'Uttar Pradesh'): 1186589,
 ('Shahjahanpur', 'Uttar Pradesh'): 1186157,
 ('Kheri', 'Uttar Pradesh'): 1136660,
 ('Dhaurahra', 'Uttar Pradesh'): 1063840,
 ('Sitapur', 'Uttar Pradesh'): 1064521,
 ('Hardoi', 'Uttar Pradesh'): 1057558,
 ('Misrikh', 'Uttar Pradesh'): 1026668,
 ('Unnao', 'Uttar Pradesh'): 1237076,
 ('Mohanlalganj', 'Uttar Pradesh'): 1269594,
 ('Lucknow', 'Uttar Pradesh'): 1116445,
 ('Rae Bareli', 'Uttar Pradesh'): 958556,
 ('Amethi', 'Uttar Pradesh'): 942453,
 ('Sultanpur', 'Uttar Pradesh'): 1000316,
 ('Pratapgarh', 'Uttar Pradesh'): 914665,
 ('Farrukhabad', 'Uttar Pradesh'): 1002953,
 ('Etawah', 'Uttar Pradesh'): 1027815,
 ('Kannauj', 'Uttar Pradesh'): 1140496,
 ('Kanpur', 'Uttar Pradesh'): 842994,
 ('Akbarpur', 'Uttar Pradesh'): 1025314,
 ('Jalaun', 'Uttar Pradesh'): 1129955,
 ('Jhansi', 'Uttar Pradesh'): 1380890,
 ('Banda', 'Uttar Pradesh'): 1034549,
 ('Fatehpur', 'Uttar Pradesh'): 1043655,
 ('Kaushambi', 'Uttar Pradesh'): 974438,
 ('Phulpur', 'Uttar Pradesh'): 978236,
 ('Allahabad', 'Uttar Pradesh'): 889056,
 ('Barabanki', 'Uttar Pradesh'): 1155341,
 ('Faizabad', 'Uttar Pradesh'): 1087121,
 ('Ambedkar Nagar', 'Uttar Pradesh'): 1090152,
 ('Bahraich', 'Uttar Pradesh'): 989848,
 ('Kaiserganj', 'Uttar Pradesh'): 981400,
 ('Shrawasti', 'Uttar Pradesh'): 997007,
 ('Gonda', 'Uttar Pradesh'): 923816,
 ('Domariyaganj', 'Uttar Pradesh'): 985269,
 ('Basti', 'Uttar Pradesh'): 1054539,
 ('Sant Kabir Nagar', 'Uttar Pradesh'): 1063390,
 ('Gorakhpur', 'Uttar Pradesh'): 1184635,
 ('Kushi Nagar', 'Uttar Pradesh'): 1053117,
 ('Deoria', 'Uttar Pradesh'): 1015363,
 ('Bansgaon', 'Uttar Pradesh'): 969136,
 ('Lalganj', 'Uttar Pradesh'): 960568,
 ('Azamgarh', 'Uttar Pradesh'): 1029112,
 ('Ghosi', 'Uttar Pradesh'): 1140781,
 ('Salempur', 'Uttar Pradesh'): 922518,
 ('Ballia', 'Uttar Pradesh'): 989732,
 ('Jaunpur', 'Uttar Pradesh'): 1040652,
 ('Machhlishahr', 'Uttar Pradesh'): 1034925,
 ('Ghazipur', 'Uttar Pradesh'): 1105627,
 ('Chandauli', 'Uttar Pradesh'): 1084961,
 ('Varanasi', 'Uttar Pradesh'): 1060476,
 ('Bhadohi', 'Uttar Pradesh'): 1039390,
 ('Mirzapur', 'Uttar Pradesh'): 1108965,
 ('Robertsganj', 'Uttar Pradesh'): 988287,
 ('Cooch behar', 'West Bengal'): 1524683,
 ('Alipurduars', 'West Bengal'): 1380217,
 ('Jalpaiguri', 'West Bengal'): 1500922,
 ('Darjeeling', 'West Bengal'): 1267270,
 ('Raiganj', 'West Bengal'): 1277109,
 ('Balurghat', 'West Bengal'): 1197849,
 ('Maldaha Uttar', 'West Bengal'): 1354706,
 ('Maldaha Dakshin', 'West Bengal'): 1279202,
 ('Jangipur', 'West Bengal'): 1304504,
 ('Baharampur', 'West Bengal'): 1299997,
 ('Murshidabad', 'West Bengal'): 1453755,
 ('Krishnanagar', 'West Bengal'): 1366443,
 ('Ranaghat', 'West Bengal'): 1484035,
 ('Bangaon', 'West Bengal'): 1407758,
 ('Barrackpore', 'West Bengal'): 1104517,
 ('Dum dum', 'West Bengal'): 1204660,
 ('Barasat', 'West Bengal'): 1395429,
 ('Basirhat', 'West Bengal'): 1433339,
 ('Jaynagar', 'West Bengal'): 1356102,
 ('Mathurapur', 'West Bengal'): 1401953,
 ('Diamond harbour', 'West Bengal'): 1409002,
 ('Jadavpur', 'West Bengal'): 1436894,
 ('Kolkata Dakshin', 'West Bengal'): 1206645,
 ('Kolkata Uttar', 'West Bengal'): 950613,
 ('Howrah', 'West Bengal'): 1222293,
 ('Uluberia', 'West Bengal'): 1311099,
 ('Srerampur', 'West Bengal'): 1401705,
 ('Hooghly', 'West Bengal'): 1457842,
 ('Arambagh', 'West Bengal'): 1471981,
 ('Tamluk', 'West Bengal'): 1446499,
 ('Kanthi', 'West Bengal'): 1424247,
 ('Ghatal', 'West Bengal'): 1488818,
 ('Jhargram', 'West Bengal'): 1406214,
 ('Medinipur', 'West Bengal'): 1409815,
 ('Purulia', 'West Bengal'): 1355236,
 ('Bankura', 'West Bengal'): 1371855,
 ('Bishnupur', 'West Bengal'): 1420648,
 ('Bardhaman Purba', 'West Bengal'): 1439286,
 ('Bardhaman Durgapur', 'West Bengal'): 1433007,
 ('Asansol', 'West Bengal'): 1238135,
 ('Bolpur', 'West Bengal'): 1461269,
 ('Birbhum', 'West Bengal'): 1449423,
 ('SARGUJA', 'Chhattisgarh'): 1280689,
 ('RAIGARH', 'Chhattisgarh'): 1350124,
 ('JANJGIR-CHAMPA', 'Chhattisgarh'): 1247650,
 ('KORBA', 'Chhattisgarh'): 1136903,
 ('BILASPUR', 'Chhattisgarh'): 1209434,
 ('RAJNANDGAON', 'Chhattisgarh'): 1307033,
 ('DURG', 'Chhattisgarh'): 1391996,
 ('RAIPUR', 'Chhattisgarh'): 1396250,
 ('MAHASAMUND', 'Chhattisgarh'): 1222335,
 ('BASTAR', 'Chhattisgarh'): 912846,
 ('KANKER', 'Chhattisgarh'): 1159193,
 ('Rajmahal', 'Jharkhand'): 1047657,
 ('Dumka', 'Jharkhand'): 1025968,
 ('Godda', 'Jharkhand'): 1194036,
 ('Chatra', 'Jharkhand'): 925937,
 ('Kodarma', 'Jharkhand'): 1209541,
 ('Giridih', 'Jharkhand'): 1106918,
 ('Dhanbad', 'Jharkhand'): 1252817,
 ('Ranchi', 'Jharkhand'): 1234926,
 ('Jamshedpur', 'Jharkhand'): 1144226,
 ('Singhbhum', 'Jharkhand'): 879329,
 ('Khunti', 'Jharkhand'): 832377,
 ('Lohardaga', 'Jharkhand'): 817550,
 ('Palamau', 'Jharkhand'): 1209747,
 ('Hazaribagh', 'Jharkhand'): 1080929,
 ('Tehri Garhwal', 'Uttarakhand'): 876069,
 ('Garhwal', 'Uttarakhand'): 742784,
 ('Almora', 'Uttarakhand'): 694472,
 ('Nainital-udhamsingh Nagar', 'Uttarakhand'): 1258570,
 ('Hardwar', 'Uttarakhand'): 1271030,
 ('Adilabad ', 'Telangana'): 1063730,
 ('Peddapalle ', 'Telangana'): 970051,
 ('Karimnagar ', 'Telangana'): 1147697,
 ('Nizamabad', 'Telangana'): 1062768,
 ('Zahirabad', 'Telangana'): 1044365,
 ('Medak', 'Telangana'): 1150223,
 ('Malkajgiri', 'Telangana'): 1563063,

In [19]:
# Initialize the "Total_vote_pc" column with zeros
df19["Total_vote_pc"] = 0

# Iterate over the dictionary items and assign values to the DataFrame
for key, value in Total_vote_pc.items():
    pc_name, state = key
    df19.loc[(df19["state"] == state) & (df19["pc_name"] == pc_name), "Total_vote_pc"] = value

df19

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors,Total_vote_pc
0,Andhra Pradesh,Aruku,KISHORE CHANDRA DEO,MALE,72.0,ST,TDP,Bicycle,336163,1938,338101,1451418,1074538
1,Andhra Pradesh,Aruku,Dr. KOSURI KASI VISWANADHA VEERA VENKATA SATYA...,MALE,54.0,ST,BJP,Lotus,17578,289,17867,1451418,1074538
2,Andhra Pradesh,Aruku,GODDETI. MADHAVI,FEMALE,26.0,ST,YSRCP,Ceiling Fan,557561,4629,562190,1451418,1074538
3,Andhra Pradesh,Aruku,SHRUTI DEVI VYRICHERLA,FEMALE,46.0,ST,INC,Hand,17656,74,17730,1451418,1074538
4,Andhra Pradesh,Aruku,GANGULAIAH VAMPURU.,MALE,49.0,ST,JnP,Glass Tumbler,42245,549,42794,1451418,1074538
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8592,Puducherry,Puducherry,TIRAVITAMANKAI@LOURDHUMARY,FEMALE,57.0,GENERAL,IND,Slate,870,0,870,973410,790760
8593,Puducherry,Puducherry,IMS. BALAJI,MALE,32.0,GENERAL,IND,Bat,2546,0,2546,973410,790760
8594,Puducherry,Puducherry,RAMESH.D,MALE,49.0,SC,IND,Mike,1653,0,1653,973410,790760
8595,Puducherry,Puducherry,V. RAMAMURTHI,MALE,74.0,GENERAL,IND,Whistle,641,1,642,973410,790760
8596,Puducherry,Puducherry,NOTA,NaN,NaN,NaN,NOTA,NaN,12192,7,12199,973410,790760

In [20]:
df19["Voter Turnout Ratio"] = df19["Total_vote_pc"]/df19["total_electors"]
df19

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio
0,Andhra Pradesh,Aruku,KISHORE CHANDRA DEO,MALE,72.0,ST,TDP,Bicycle,336163,1938,338101,1451418,1074538,0.740337
1,Andhra Pradesh,Aruku,Dr. KOSURI KASI VISWANADHA VEERA VENKATA SATYA...,MALE,54.0,ST,BJP,Lotus,17578,289,17867,1451418,1074538,0.740337
2,Andhra Pradesh,Aruku,GODDETI. MADHAVI,FEMALE,26.0,ST,YSRCP,Ceiling Fan,557561,4629,562190,1451418,1074538,0.740337
3,Andhra Pradesh,Aruku,SHRUTI DEVI VYRICHERLA,FEMALE,46.0,ST,INC,Hand,17656,74,17730,1451418,1074538,0.740337
4,Andhra Pradesh,Aruku,GANGULAIAH VAMPURU.,MALE,49.0,ST,JnP,Glass Tumbler,42245,549,42794,1451418,1074538,0.740337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8592,Puducherry,Puducherry,TIRAVITAMANKAI@LOURDHUMARY,FEMALE,57.0,GENERAL,IND,Slate,870,0,870,973410,790760,0.812361
8593,Puducherry,Puducherry,IMS. BALAJI,MALE,32.0,GENERAL,IND,Bat,2546,0,2546,973410,790760,0.812361
8594,Puducherry,Puducherry,RAMESH.D,MALE,49.0,SC,IND,Mike,1653,0,1653,973410,790760,0.812361
8595,Puducherry,Puducherry,V. RAMAMURTHI,MALE,74.0,GENERAL,IND,Whistle,641,1,642,973410,790760,0.812361
8596,Puducherry,Puducherry,NOTA,NaN,NaN,NaN,NOTA,NaN,12192,7,12199,973410,790760,0.812361

In [21]:
Top_5_2019 = sorted(df19["Voter Turnout Ratio"].unique())[-5:]
Top_5_2019

[0.8646008687770022,
 0.864853434009579,
 0.8655311785486032,
 0.8730634667302524,
 0.906615638077959]

In [22]:
Bottom_5_2019 = sorted(df19["Voter Turnout Ratio"].unique())[:5]
Bottom_5_2019

[0.08935318101073203,
 0.14430847682538653,
 0.34570605082345657,
 0.44836717943584325,
 0.4529296791536347]

# 1. List top 5 / bottom 5 constituencies of 2014 & 2019 in terms of voter turnout ratio?

## List top 5 / bottom 5 constituencies of 2014 & 2019

In [23]:
print("Top 5 constituencies of 2014 in terms of voter turnout ratio are:")
for idx, ratio in enumerate(Top_5_2014[::-1]):
    print(idx+1, *df14[df14["Voter Turnout Ratio"] == ratio].pc_name.unique(), f"{ratio:.2f}")
print()
print("Top 5 constituencies of 2019 in terms of voter turnout ratio are:")
for idx, ratio in enumerate(Top_5_2019[::-1]):
    print(idx+1, *df19[df19["Voter Turnout Ratio"] == ratio].pc_name.unique(),f"{ratio:.2f}")

Top 5 constituencies of 2014 in terms of voter turnout ratio are:
1 Dhubri 0.88
2 Nagaland 0.88
3 Tamluk 0.88
4 Bishnupur 0.87
5 Lakshadweep 0.87

Top 5 constituencies of 2019 in terms of voter turnout ratio are:
1 Dhubri 0.91
2 Bishnupur 0.87
3 Barpeta 0.87
4 Jalpaiguri 0.86
5 ARUNACHAL EAST 0.86

In [24]:
print("Bottom 5 constituencies of 2014 in terms of voter turnout ratio are:")
for idx, ratio in enumerate(Bottom_5_2014):
    print(idx+1, *df14[df14["Voter Turnout Ratio"] == ratio].pc_name.unique(), f"{ratio:.2f}")
print()
print("Bottom 5 constituencies of 2019 in terms of voter turnout ratio are:")
for idx, ratio in enumerate(Bottom_5_2019):
    print(idx+1, *df19[df19["Voter Turnout Ratio"] == ratio].pc_name.unique(), f"{ratio:.2f}")

Bottom 5 constituencies of 2014 in terms of voter turnout ratio are:
1 Srinagar 0.26
2 Anantnag 0.29
3 Baramulla 0.39
4 Kalyan 0.43
5 Patna Sahib 0.45

Bottom 5 constituencies of 2019 in terms of voter turnout ratio are:
1 Anantnag 0.09
2 Srinagar 0.14
3 Baramulla 0.35
4 Hyderabad 0.45
5 Kalyan 0.45

# 2. List top 5 / bottom 5 states of 2014 & 2019 in terms of voter turnout ratio?

In [25]:
# Calculating Voter Turnout Ratio for state
state_Voter_Turnout_Ratio_2014 = dict()
for state in df14.state.unique():
    total_ratio = 0
    count = 0
    for pc in df14[df14["state"]==state].pc_name.unique():
        total_ratio += df14[(df14["state"]==state) & (df14["pc_name"]==pc)]["Voter Turnout Ratio"].unique()[0]
        count += 1
    state_Voter_Turnout_Ratio_2014[state] = total_ratio/count
state_Voter_Turnout_Ratio_2014

{'Telangana': 0.7164436838527906,
 'Andhra Pradesh': 0.7812880277762365,
 'Arunachal Pradesh': 0.793559701643926,
 'Assam': 0.7976558736443258,
 'Bihar': 0.564768867833233,
 'Goa': 0.7707029629588493,
 'Gujarat': 0.6360615150646751,
 'Haryana': 0.7145224209256298,
 'Himachal Pradesh': 0.6438500452844521,
 'Jammu & Kashmir': 0.5055941425745316,
 'Karnataka': 0.6772129133911073,
 'Kerala': 0.7396870166048912,
 'Madhya Pradesh': 0.6170440575367803,
 'Maharashtra': 0.6048510821130649,
 'Manipur': 0.7945103814199421,
 'Meghalaya': 0.7065929200138219,
 'Mizoram': 0.6169460387085749,
 'Nagaland': 0.8782202790936725,
 'Punjab': 0.7065935284013087,
 'Rajasthan': 0.6301962272853828,
 'Sikkim': 0.8333117566146129,
 'Tamil Nadu': 0.7396860890922783,
 'Tripura': 0.846638693364812,
 'Uttar Pradesh': 0.5858117103872776,
 'West Bengal': 0.8217317247982407,
 'Jharkhand': 0.6394897551285011,
 'Uttarakhand': 0.6070425294773981,
 'Andaman & Nicobar Islands': 0.7065934065934066,
 'Chandigarh': 0.7370687273046452,
 'Dadra & Nagar Haveli': 0.840735107860242,
 'Daman & Diu': 0.7800710025306947,
 'NCT OF Delhi': 0.6519906998959744,
 'Lakshadweep': 0.8661311646168022,
 'Puducherry': 0.8210032206994565}

In [26]:
df14["state Voter Turnout Ratio"] = 0.0
for key, value in state_Voter_Turnout_Ratio_2014.items():
    df14.loc[df14["state"]==key, "state Voter Turnout Ratio"] = value
df14

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio,state Voter Turnout Ratio
0,Telangana,Adilabad,GODAM NAGESH,M,49.0,ST,TRS,Car,425762,5085,430847,1386282,1045839,0.754420,0.716444
1,Telangana,Adilabad,NARESH,M,37.0,ST,INC,Hand,257994,1563,259557,1386282,1045839,0.754420,0.716444
2,Telangana,Adilabad,RAMESH RATHOD,M,48.0,ST,TDP,Bicycle,182879,1319,184198,1386282,1045839,0.754420,0.716444
3,Telangana,Adilabad,RATHOD SADASHIV,M,55.0,ST,BSP,Elephant,94363,57,94420,1386282,1045839,0.754420,0.716444
4,Telangana,Adilabad,NETHAWATH RAMDAS,M,44.0,ST,IND,Auto- Rickshaw,41028,4,41032,1386282,1045839,0.754420,0.716444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8350,Puducherry,Puducherry,PUVALA NAGESWARA RAO,M,60.0,GEN,IND,Sewing Machine,465,0,465,901357,740017,0.821003,0.821003
8351,Puducherry,Puducherry,K. MANJINI,M,41.0,GEN,IND,Coconut,767,0,767,901357,740017,0.821003,0.821003
8352,Puducherry,Puducherry,R. VALAVAN,M,40.0,GEN,IND,Carrom Board,497,0,497,901357,740017,0.821003,0.821003
8353,Puducherry,Puducherry,V. VIJAYA,F,29.0,GEN,IND,Green Chilli,746,0,746,901357,740017,0.821003,0.821003
8354,Puducherry,Puducherry,None of the Above,NaN,NaN,NaN,NOTA,NOTA,22267,1,22268,901357,740017,0.821003,0.821003

In [27]:
# Calculating Voter Turnout Ratio for state
state_Voter_Turnout_Ratio_2019 = dict()
for state in df19.state.unique():
    total_ratio = 0
    count = 0
    for pc in df19[df19["state"]==state].pc_name.unique():
        total_ratio += df19[(df19["state"]==state) & (df19["pc_name"]==pc)]["Voter Turnout Ratio"].unique()[0]
        count += 1
    state_Voter_Turnout_Ratio_2019[state] = total_ratio/count
state_Voter_Turnout_Ratio_2019

{'Andhra Pradesh': 0.803330415607088,
 'Arunachal Pradesh': 0.8185976690389243,
 'Assam': 0.8112826866459253,
 'Bihar': 0.5750003757620296,
 'Goa': 0.7513522921368121,
 'Gujarat': 0.6442501881031457,
 'Haryana': 0.7044815266408022,
 'Himachal Pradesh': 0.7228856142876641,
 'Jammu & Kashmir': 0.45118145968458306,
 'Karnataka': 0.6967891712830557,
 'Kerala': 0.7781871880181359,
 'Madhya Pradesh': 0.7127338437085275,
 'Maharashtra': 0.6108249473253852,
 'Manipur': 0.8247147790032682,
 'Meghalaya': 0.7339336805901104,
 'Mizoram': 0.6304652324900564,
 'Nagaland': 0.8291119373657599,
 'Odisha': 0.732897403784901,
 'Punjab': 0.6586535840189841,
 'Rajasthan': 0.6619382767487763,
 'Sikkim': 0.810235690856153,
 'Tamil Nadu': 0.7273975277994718,
 'Tripura': 0.8236493855992636,
 'Uttar Pradesh': 0.592668128022159,
 'West Bengal': 0.816426657626762,
 'Chhattisgarh': 0.7181585037170533,
 'Jharkhand': 0.6711820722151342,
 'Uttarakhand': 0.6064747773023875,
 'Telangana': 0.6440268013289829,
 'Andaman & Nicobar Islands': 0.6509101299647377,
 'Chandigarh': 0.7059649404928494,
 'Dadra & Nagar Haveli': 0.7958396825968188,
 'Daman & Diu': 0.718490225069821,
 'NCT OF Delhi': 0.6051986380830864,
 'Lakshadweep': 0.8517820580188081,
 'Puducherry': 0.8123606702211812}

In [28]:
df19["state Voter Turnout Ratio"] = 0.0
for key, value in state_Voter_Turnout_Ratio_2019.items():
    df19.loc[df19["state"]==key, "state Voter Turnout Ratio"] = value
df19

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio,state Voter Turnout Ratio
0,Andhra Pradesh,Aruku,KISHORE CHANDRA DEO,MALE,72.0,ST,TDP,Bicycle,336163,1938,338101,1451418,1074538,0.740337,0.803330
1,Andhra Pradesh,Aruku,Dr. KOSURI KASI VISWANADHA VEERA VENKATA SATYA...,MALE,54.0,ST,BJP,Lotus,17578,289,17867,1451418,1074538,0.740337,0.803330
2,Andhra Pradesh,Aruku,GODDETI. MADHAVI,FEMALE,26.0,ST,YSRCP,Ceiling Fan,557561,4629,562190,1451418,1074538,0.740337,0.803330
3,Andhra Pradesh,Aruku,SHRUTI DEVI VYRICHERLA,FEMALE,46.0,ST,INC,Hand,17656,74,17730,1451418,1074538,0.740337,0.803330
4,Andhra Pradesh,Aruku,GANGULAIAH VAMPURU.,MALE,49.0,ST,JnP,Glass Tumbler,42245,549,42794,1451418,1074538,0.740337,0.803330
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8592,Puducherry,Puducherry,TIRAVITAMANKAI@LOURDHUMARY,FEMALE,57.0,GENERAL,IND,Slate,870,0,870,973410,790760,0.812361,0.812361
8593,Puducherry,Puducherry,IMS. BALAJI,MALE,32.0,GENERAL,IND,Bat,2546,0,2546,973410,790760,0.812361,0.812361
8594,Puducherry,Puducherry,RAMESH.D,MALE,49.0,SC,IND,Mike,1653,0,1653,973410,790760,0.812361,0.812361
8595,Puducherry,Puducherry,V. RAMAMURTHI,MALE,74.0,GENERAL,IND,Whistle,641,1,642,973410,790760,0.812361,0.812361
8596,Puducherry,Puducherry,NOTA,NaN,NaN,NaN,NOTA,NaN,12192,7,12199,973410,790760,0.812361,0.812361

In [29]:
Top_5_state_2014 = sorted(df14["state Voter Turnout Ratio"].unique())[-5:]
Top_5_state_2014

[0.8333117566146129,
 0.840735107860242,
 0.846638693364812,
 0.8661311646168022,
 0.8782202790936725]

In [30]:
Bottom_5_state_2014 = sorted(df14["state Voter Turnout Ratio"].unique())[:5]
Bottom_5_state_2014

[0.5055941425745316,
 0.564768867833233,
 0.5858117103872776,
 0.6048510821130649,
 0.6070425294773981]

In [31]:
Top_5_state_2019 = sorted(df19["state Voter Turnout Ratio"].unique())[-5:]
Top_5_state_2019

[0.8185976690389243,
 0.8236493855992636,
 0.8247147790032682,
 0.8291119373657599,
 0.8517820580188081]

In [32]:
Bottom_5_state_2019 = sorted(df19["state Voter Turnout Ratio"].unique())[:5]
Bottom_5_state_2019

[0.45118145968458306,
 0.5750003757620296,
 0.592668128022159,
 0.6051986380830864,
 0.6064747773023875]

## List top 5 / bottom 5 states of 2014 & 2019 in terms of voter turnout ratio

In [33]:
print("Top 5 state of 2014 in terms of voter turnout ratio are:")
for idx, ratio in enumerate(Top_5_state_2014[::-1]):
    print(idx+1, *df14[df14["state Voter Turnout Ratio"] == ratio].state.unique(), f"{ratio:.2f}")
print()
print("Top 5 state of 2019 in terms of voter turnout ratio are:")
for idx, ratio in enumerate(Top_5_state_2019[::-1]):
    print(idx+1, *df19[df19["state Voter Turnout Ratio"] == ratio].state.unique(),f"{ratio:.2f}")

Top 5 state of 2014 in terms of voter turnout ratio are:
1 Nagaland 0.88
2 Lakshadweep 0.87
3 Tripura 0.85
4 Dadra & Nagar Haveli 0.84
5 Sikkim 0.83

Top 5 state of 2019 in terms of voter turnout ratio are:
1 Lakshadweep 0.85
2 Nagaland 0.83
3 Manipur 0.82
4 Tripura 0.82
5 Arunachal Pradesh 0.82

In [34]:
print("Bottom 5 state of 2014 in terms of voter turnout ratio are:")
for idx, ratio in enumerate(Bottom_5_state_2014):
    print(idx+1, *df14[df14["state Voter Turnout Ratio"] == ratio].state.unique(), f"{ratio:.2f}")
print()
print("Bottom 5 state of 2019 in terms of voter turnout ratio are:")
for idx, ratio in enumerate(Bottom_5_state_2019):
    print(idx+1, *df19[df19["state Voter Turnout Ratio"] == ratio].state.unique(), f"{ratio:.2f}")

Bottom 5 state of 2014 in terms of voter turnout ratio are:
1 Jammu & Kashmir 0.51
2 Bihar 0.56
3 Uttar Pradesh 0.59
4 Maharashtra 0.60
5 Uttarakhand 0.61

Bottom 5 state of 2019 in terms of voter turnout ratio are:
1 Jammu & Kashmir 0.45
2 Bihar 0.58
3 Uttar Pradesh 0.59
4 NCT OF Delhi 0.61
5 Uttarakhand 0.61

# 3. Which constituencies have elected the same party for two consecutive elections, rank them by % of votes to that winning party in 2019

In [35]:
df14["winner_pc"] = "Not"

for state in df14.state.unique():
    state_data = df14[df14["state"] == state]
    
    for pc in state_data.pc_name.unique():
        pc_data = state_data[state_data["pc_name"] == pc]
        max_vote = pc_data["total_votes"].max()
        win_party = pc_data[pc_data["total_votes"] == max_vote]["party"].values[0]
        
        df14.loc[(df14["state"] == state) & (df14["pc_name"] == pc) & (df14["party"] == win_party), "winner_pc"] = "win"

df14

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio,state Voter Turnout Ratio,winner_pc
0,Telangana,Adilabad,GODAM NAGESH,M,49.0,ST,TRS,Car,425762,5085,430847,1386282,1045839,0.754420,0.716444,win
1,Telangana,Adilabad,NARESH,M,37.0,ST,INC,Hand,257994,1563,259557,1386282,1045839,0.754420,0.716444,Not
2,Telangana,Adilabad,RAMESH RATHOD,M,48.0,ST,TDP,Bicycle,182879,1319,184198,1386282,1045839,0.754420,0.716444,Not
3,Telangana,Adilabad,RATHOD SADASHIV,M,55.0,ST,BSP,Elephant,94363,57,94420,1386282,1045839,0.754420,0.716444,Not
4,Telangana,Adilabad,NETHAWATH RAMDAS,M,44.0,ST,IND,Auto- Rickshaw,41028,4,41032,1386282,1045839,0.754420,0.716444,Not
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8350,Puducherry,Puducherry,PUVALA NAGESWARA RAO,M,60.0,GEN,IND,Sewing Machine,465,0,465,901357,740017,0.821003,0.821003,Not
8351,Puducherry,Puducherry,K. MANJINI,M,41.0,GEN,IND,Coconut,767,0,767,901357,740017,0.821003,0.821003,Not
8352,Puducherry,Puducherry,R. VALAVAN,M,40.0,GEN,IND,Carrom Board,497,0,497,901357,740017,0.821003,0.821003,Not
8353,Puducherry,Puducherry,V. VIJAYA,F,29.0,GEN,IND,Green Chilli,746,0,746,901357,740017,0.821003,0.821003,Not
8354,Puducherry,Puducherry,None of the Above,NaN,NaN,NaN,NOTA,NOTA,22267,1,22268,901357,740017,0.821003,0.821003,Not

In [36]:
df19["winner_pc"] = "Not"

for state in df19.state.unique():
    state_data = df19[df19["state"] == state]
    
    for pc in state_data.pc_name.unique():
        pc_data = state_data[state_data["pc_name"] == pc]
        max_vote = pc_data["total_votes"].max()
        win_party = pc_data[pc_data["total_votes"] == max_vote]["party"].values[0]
        
        df19.loc[(df19["state"] == state) & (df19["pc_name"] == pc) & (df19["party"] == win_party), "winner_pc"] = "win"

df19

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio,state Voter Turnout Ratio,winner_pc
0,Andhra Pradesh,Aruku,KISHORE CHANDRA DEO,MALE,72.0,ST,TDP,Bicycle,336163,1938,338101,1451418,1074538,0.740337,0.803330,Not
1,Andhra Pradesh,Aruku,Dr. KOSURI KASI VISWANADHA VEERA VENKATA SATYA...,MALE,54.0,ST,BJP,Lotus,17578,289,17867,1451418,1074538,0.740337,0.803330,Not
2,Andhra Pradesh,Aruku,GODDETI. MADHAVI,FEMALE,26.0,ST,YSRCP,Ceiling Fan,557561,4629,562190,1451418,1074538,0.740337,0.803330,win
3,Andhra Pradesh,Aruku,SHRUTI DEVI VYRICHERLA,FEMALE,46.0,ST,INC,Hand,17656,74,17730,1451418,1074538,0.740337,0.803330,Not
4,Andhra Pradesh,Aruku,GANGULAIAH VAMPURU.,MALE,49.0,ST,JnP,Glass Tumbler,42245,549,42794,1451418,1074538,0.740337,0.803330,Not
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8592,Puducherry,Puducherry,TIRAVITAMANKAI@LOURDHUMARY,FEMALE,57.0,GENERAL,IND,Slate,870,0,870,973410,790760,0.812361,0.812361,Not
8593,Puducherry,Puducherry,IMS. BALAJI,MALE,32.0,GENERAL,IND,Bat,2546,0,2546,973410,790760,0.812361,0.812361,Not
8594,Puducherry,Puducherry,RAMESH.D,MALE,49.0,SC,IND,Mike,1653,0,1653,973410,790760,0.812361,0.812361,Not
8595,Puducherry,Puducherry,V. RAMAMURTHI,MALE,74.0,GENERAL,IND,Whistle,641,1,642,973410,790760,0.812361,0.812361,Not
8596,Puducherry,Puducherry,NOTA,NaN,NaN,NaN,NOTA,NaN,12192,7,12199,973410,790760,0.812361,0.812361,Not

In [37]:
df14[(df14["party"]=="NOTA") & (df14["winner_pc"]=="win")]

Empty DataFrame
Columns: [state, pc_name, candidate, sex, age, category, party, party_symbol, general_votes, postal_votes, total_votes, total_electors, Total_vote_pc, Voter Turnout Ratio, state Voter Turnout Ratio, winner_pc]
Index: []

In [38]:
df19[(df19["party"]=="NOTA") & (df19["winner_pc"]=="win")]

Empty DataFrame
Columns: [state, pc_name, candidate, sex, age, category, party, party_symbol, general_votes, postal_votes, total_votes, total_electors, Total_vote_pc, Voter Turnout Ratio, state Voter Turnout Ratio, winner_pc]
Index: []

In [39]:
win19 = df19[df19["winner_pc"]=="win"]
win19

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio,state Voter Turnout Ratio,winner_pc
2,Andhra Pradesh,Aruku,GODDETI. MADHAVI,FEMALE,26.0,ST,YSRCP,Ceiling Fan,557561,4629,562190,1451418,1074538,0.740337,0.803330,win
11,Andhra Pradesh,Srikakulam,KINJARAPU RAM MOHAN NAIDU,MALE,32.0,GENERAL,TDP,Bicycle,529213,5331,534544,1553860,1157329,0.744809,0.803330,win
23,Andhra Pradesh,Vizianagaram,Bellana Chandra Sekhar,MALE,57.0,GENERAL,YSRCP,Ceiling Fan,573466,4952,578418,1503980,1217890,0.809778,0.803330,win
39,Andhra Pradesh,Visakhapatnam,M V V SATYANARAYANA,MALE,52.0,GENERAL,YSRCP,Ceiling Fan,433968,2938,436906,1829300,1239754,0.677720,0.803330,win
53,Andhra Pradesh,Anakapalli,Dr.Beesetti Venkata Satyavathi,FEMALE,52.0,GENERAL,YSRCP,Ceiling Fan,583210,3016,586226,1521363,1238491,0.814067,0.803330,win
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8509,NCT OF Delhi,NORTH WEST DELHI,HANS RAJ HANS,MALE,57.0,SC,BJP,Lotus,847737,926,848663,2378995,1402962,0.589729,0.605199,win
8519,NCT OF Delhi,WEST DELHI,PARVESH SAHIB SINGH VERMA,MALE,41.0,GENERAL,BJP,Lotus,862058,3590,865648,2371644,1441601,0.607849,0.605199,win
8543,NCT OF Delhi,SOUTH DELHI,RAMESH BIDHURI,MALE,57.0,GENERAL,BJP,Lotus,685789,1225,687014,2067463,1214222,0.587300,0.605199,win
8573,Lakshadweep,Lakshadweep,MOHAMMED FAIZAL PP,MALE,43.0,ST,NCP,Clock,22796,55,22851,55189,47009,0.851782,0.851782,win
8580,Puducherry,Puducherry,Ve. VAITHILINGAM,MALE,68.0,GENERAL,INC,Hand,444646,335,444981,973410,790760,0.812361,0.812361,win

In [40]:
win14 = df14[df14["winner_pc"]=="win"]
win14

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio,state Voter Turnout Ratio,winner_pc
0,Telangana,Adilabad,GODAM NAGESH,M,49.0,ST,TRS,Car,425762,5085,430847,1386282,1045839,0.754420,0.716444,win
11,Telangana,Peddapalle,BALKA SUMAN,M,31.0,SC,TRS,Car,563214,2282,565496,1425355,1022184,0.717143,0.716444,win
31,Telangana,Karimnagar,VINOD KUMAR BOINAPALLY,M,54.0,GEN,TRS,Car,503197,2161,505358,1550810,1125184,0.725546,0.716444,win
46,Telangana,Nizamabad,KALVAKUNTLA KAVITHA,F,36.0,GEN,TRS,Car,435706,3601,439307,1496193,1033924,0.691037,0.716444,win
62,Telangana,Zahirabad,B.B. PATIL,M,58.0,GEN,TRS,Car,505983,2678,508661,1445354,1094806,0.757466,0.716444,win
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8264,NCT OF Delhi,NORTH WEST DELHI,UDIT RAJ,M,56.0,SC,BJP,Lotus,627529,2331,629860,2194343,1356036,0.617969,0.651991,win
8280,NCT OF Delhi,WEST DELHI,PARVESH SAHIB SINGH VERMA,M,36.0,GEN,BJP,Lotus,649542,1853,651395,2039410,1347971,0.660961,0.651991,win
8299,NCT OF Delhi,SOUTH DELHI,RAMESH BIDHURI,M,52.0,GEN,BJP,Lotus,497151,829,497980,1752748,1102410,0.628961,0.651991,win
8319,Lakshadweep,Lakshadweep,MOHAMMED FAIZAL P.P.,M,38.0,ST,NCP,Clock,21665,0,21665,49922,43239,0.866131,0.866131,win
8325,Puducherry,Puducherry,R. RADHAKRISHNAN,M,42.0,GEN,AINRC,Jug,255732,94,255826,901357,740017,0.821003,0.821003,win

In [41]:
len(win19)

577

In [42]:
new14 = win14.drop(["candidate", "sex", "age", "category", "party_symbol", "general_votes", "postal_votes"], axis=1)
new14

,state,pc_name,party,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio,state Voter Turnout Ratio,winner_pc
0,Telangana,Adilabad,TRS,430847,1386282,1045839,0.754420,0.716444,win
11,Telangana,Peddapalle,TRS,565496,1425355,1022184,0.717143,0.716444,win
31,Telangana,Karimnagar,TRS,505358,1550810,1125184,0.725546,0.716444,win
46,Telangana,Nizamabad,TRS,439307,1496193,1033924,0.691037,0.716444,win
62,Telangana,Zahirabad,TRS,508661,1445354,1094806,0.757466,0.716444,win
...,...,...,...,...,...,...,...,...,...
8264,NCT OF Delhi,NORTH WEST DELHI,BJP,629860,2194343,1356036,0.617969,0.651991,win
8280,NCT OF Delhi,WEST DELHI,BJP,651395,2039410,1347971,0.660961,0.651991,win
8299,NCT OF Delhi,SOUTH DELHI,BJP,497980,1752748,1102410,0.628961,0.651991,win
8319,Lakshadweep,Lakshadweep,NCP,21665,49922,43239,0.866131,0.866131,win
8325,Puducherry,Puducherry,AINRC,255826,901357,740017,0.821003,0.821003,win

In [43]:
new19 = win19.drop(["candidate", "sex", "age", "category", "party_symbol", "general_votes", "postal_votes"], axis=1)
new19

,state,pc_name,party,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio,state Voter Turnout Ratio,winner_pc
2,Andhra Pradesh,Aruku,YSRCP,562190,1451418,1074538,0.740337,0.803330,win
11,Andhra Pradesh,Srikakulam,TDP,534544,1553860,1157329,0.744809,0.803330,win
23,Andhra Pradesh,Vizianagaram,YSRCP,578418,1503980,1217890,0.809778,0.803330,win
39,Andhra Pradesh,Visakhapatnam,YSRCP,436906,1829300,1239754,0.677720,0.803330,win
53,Andhra Pradesh,Anakapalli,YSRCP,586226,1521363,1238491,0.814067,0.803330,win
...,...,...,...,...,...,...,...,...,...
8509,NCT OF Delhi,NORTH WEST DELHI,BJP,848663,2378995,1402962,0.589729,0.605199,win
8519,NCT OF Delhi,WEST DELHI,BJP,865648,2371644,1441601,0.607849,0.605199,win
8543,NCT OF Delhi,SOUTH DELHI,BJP,687014,2067463,1214222,0.587300,0.605199,win
8573,Lakshadweep,Lakshadweep,NCP,22851,55189,47009,0.851782,0.851782,win
8580,Puducherry,Puducherry,INC,444981,973410,790760,0.812361,0.812361,win

In [44]:
merge19 = pd.merge(new19, new14, on=["state", "pc_name", "party"], how='inner', suffixes=('_2019', '_2014')).drop_duplicates(subset=["state", "pc_name", "party"])
merge19

,state,pc_name,party,total_votes_2019,total_electors_2019,Total_vote_pc_2019,Voter Turnout Ratio_2019,state Voter Turnout Ratio_2019,winner_pc_2019,total_votes_2014,total_electors_2014,Total_vote_pc_2014,Voter Turnout Ratio_2014,state Voter Turnout Ratio_2014,winner_pc_2014
0,Andhra Pradesh,Aruku,YSRCP,562190,1451418,1074538,0.740337,0.803330,win,413191,1272340,909614,0.714914,0.781288,win
1,Andhra Pradesh,Srikakulam,TDP,534544,1553860,1157329,0.744809,0.803330,win,556545,1413726,1052115,0.744214,0.781288,win
2,Andhra Pradesh,Vijayawada,TDP,575498,1652994,1277711,0.772968,0.803330,win,592953,1564513,1195765,0.764305,0.781288,win
3,Andhra Pradesh,Guntur,TDP,587918,1706119,1351474,0.792133,0.803330,win,618417,1572017,1244926,0.791929,0.781288,win
4,Andhra Pradesh,Ongole,YSRCP,739202,1556469,1342368,0.862444,0.803330,win,589861,1470212,1208225,0.821803,0.781288,win
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,NCT OF Delhi,NEW DELHI,BJP,504206,1617470,920541,0.569124,0.605199,win,453350,1490147,969812,0.650816,0.651991,win
340,NCT OF Delhi,NORTH WEST DELHI,BJP,848663,2378995,1402962,0.589729,0.605199,win,629860,2194343,1356036,0.617969,0.651991,win
341,NCT OF Delhi,WEST DELHI,BJP,865648,2371644,1441601,0.607849,0.605199,win,651395,2039410,1347971,0.660961,0.651991,win
342,NCT OF Delhi,SOUTH DELHI,BJP,687014,2067463,1214222,0.587300,0.605199,win,497980,1752748,1102410,0.628961,0.651991,win
343,Lakshadweep,Lakshadweep,NCP,22851,55189,47009,0.851782,0.851782,win,21665,49922,43239,0.866131,0.866131,win

In [45]:
merge19["vote_percentage"] = merge19["total_votes_2019"]/merge19["Total_vote_pc_2019"]
merge19

,state,pc_name,party,total_votes_2019,total_electors_2019,Total_vote_pc_2019,Voter Turnout Ratio_2019,state Voter Turnout Ratio_2019,winner_pc_2019,total_votes_2014,total_electors_2014,Total_vote_pc_2014,Voter Turnout Ratio_2014,state Voter Turnout Ratio_2014,winner_pc_2014,vote_percentage
0,Andhra Pradesh,Aruku,YSRCP,562190,1451418,1074538,0.740337,0.803330,win,413191,1272340,909614,0.714914,0.781288,win,0.523192
1,Andhra Pradesh,Srikakulam,TDP,534544,1553860,1157329,0.744809,0.803330,win,556545,1413726,1052115,0.744214,0.781288,win,0.461877
2,Andhra Pradesh,Vijayawada,TDP,575498,1652994,1277711,0.772968,0.803330,win,592953,1564513,1195765,0.764305,0.781288,win,0.450413
3,Andhra Pradesh,Guntur,TDP,587918,1706119,1351474,0.792133,0.803330,win,618417,1572017,1244926,0.791929,0.781288,win,0.435020
4,Andhra Pradesh,Ongole,YSRCP,739202,1556469,1342368,0.862444,0.803330,win,589861,1470212,1208225,0.821803,0.781288,win,0.550670
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,NCT OF Delhi,NEW DELHI,BJP,504206,1617470,920541,0.569124,0.605199,win,453350,1490147,969812,0.650816,0.651991,win,0.547728
340,NCT OF Delhi,NORTH WEST DELHI,BJP,848663,2378995,1402962,0.589729,0.605199,win,629860,2194343,1356036,0.617969,0.651991,win,0.604908
341,NCT OF Delhi,WEST DELHI,BJP,865648,2371644,1441601,0.607849,0.605199,win,651395,2039410,1347971,0.660961,0.651991,win,0.600477
342,NCT OF Delhi,SOUTH DELHI,BJP,687014,2067463,1214222,0.587300,0.605199,win,497980,1752748,1102410,0.628961,0.651991,win,0.565806
343,Lakshadweep,Lakshadweep,NCP,22851,55189,47009,0.851782,0.851782,win,21665,49922,43239,0.866131,0.866131,win,0.486098

In [46]:
sorted_merge19 = merge19.sort_values(by="vote_percentage", ascending=False)
sorted_merge19

,state,pc_name,party,total_votes_2019,total_electors_2019,Total_vote_pc_2019,Voter Turnout Ratio_2019,state Voter Turnout Ratio_2019,winner_pc_2019,total_votes_2014,total_electors_2014,Total_vote_pc_2014,Voter Turnout Ratio_2014,state Voter Turnout Ratio_2014,winner_pc_2014,vote_percentage
80,Gujarat,Surat,BJP,795651,1655704,1068412,0.645292,0.644250,win,718412,1484068,947922,0.638732,0.636062,win,0.744704
81,Gujarat,Navsari,BJP,972739,1971658,1308018,0.663410,0.644250,win,820831,1764622,1160747,0.657788,0.636062,win,0.743674
76,Gujarat,Vadodara,BJP,883719,1794896,1222348,0.681013,0.644250,win,845464,1638321,1161577,0.709005,0.636062,win,0.722968
90,Himachal Pradesh,Kangra,BJP,725218,1427338,1006989,0.705501,0.722886,win,456163,1258601,799445,0.635185,0.643850,win,0.720185
222,Rajasthan,Bhilwara,BJP,938160,1997328,1310513,0.656133,0.661938,win,630317,1754901,1104090,0.629147,0.630196,win,0.715872
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,Punjab,Ludhiana,INC,383795,1683325,1046955,0.621957,0.658654,win,300459,1561201,1100457,0.704878,0.706594,win,0.366582
287,West Bengal,Maldaha Dakshin,INC,444270,1575590,1279202,0.811888,0.816427,win,380291,1347143,1092407,0.810906,0.821732,win,0.347302
94,Jammu & Kashmir,Ladakh,BJP,42914,179232,126426,0.705376,0.451181,win,31111,166763,118029,0.707765,0.505594,win,0.339440
36,Bihar,Kishanganj,INC,367017,1659651,1101603,0.663756,0.575000,win,493461,1438990,928490,0.645237,0.564769,win,0.333166
13,Assam,Kokrajhar,IND,484560,1776358,1479485,0.832875,0.811283,win,278649,1505472,1223869,0.812947,0.797656,win,0.327519

## Constituencies which have elected the same party for two consecutive elections, ranked by % of votes to that winning party in 2019

In [47]:
sorted_merge19['rank_2019'] = sorted_merge19['vote_percentage'].rank(method='dense', ascending=False)
sorted_merge19

,state,pc_name,party,total_votes_2019,total_electors_2019,Total_vote_pc_2019,Voter Turnout Ratio_2019,state Voter Turnout Ratio_2019,winner_pc_2019,total_votes_2014,total_electors_2014,Total_vote_pc_2014,Voter Turnout Ratio_2014,state Voter Turnout Ratio_2014,winner_pc_2014,vote_percentage,rank_2019
80,Gujarat,Surat,BJP,795651,1655704,1068412,0.645292,0.644250,win,718412,1484068,947922,0.638732,0.636062,win,0.744704,1.0
81,Gujarat,Navsari,BJP,972739,1971658,1308018,0.663410,0.644250,win,820831,1764622,1160747,0.657788,0.636062,win,0.743674,2.0
76,Gujarat,Vadodara,BJP,883719,1794896,1222348,0.681013,0.644250,win,845464,1638321,1161577,0.709005,0.636062,win,0.722968,3.0
90,Himachal Pradesh,Kangra,BJP,725218,1427338,1006989,0.705501,0.722886,win,456163,1258601,799445,0.635185,0.643850,win,0.720185,4.0
222,Rajasthan,Bhilwara,BJP,938160,1997328,1310513,0.656133,0.661938,win,630317,1754901,1104090,0.629147,0.630196,win,0.715872,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,Punjab,Ludhiana,INC,383795,1683325,1046955,0.621957,0.658654,win,300459,1561201,1100457,0.704878,0.706594,win,0.366582,329.0
287,West Bengal,Maldaha Dakshin,INC,444270,1575590,1279202,0.811888,0.816427,win,380291,1347143,1092407,0.810906,0.821732,win,0.347302,330.0
94,Jammu & Kashmir,Ladakh,BJP,42914,179232,126426,0.705376,0.451181,win,31111,166763,118029,0.707765,0.505594,win,0.339440,331.0
36,Bihar,Kishanganj,INC,367017,1659651,1101603,0.663756,0.575000,win,493461,1438990,928490,0.645237,0.564769,win,0.333166,332.0
13,Assam,Kokrajhar,IND,484560,1776358,1479485,0.832875,0.811283,win,278649,1505472,1223869,0.812947,0.797656,win,0.327519,333.0

# 4. Which constituencies have voted for different parties in two elections (list top 10 based on difference (2019-2014) in winner vote percentage in two elections)

In [48]:
new_party19 = pd.merge(new19, new14, on=["state", "pc_name"], suffixes=('_2019', '_2014'))
new_party19

,state,pc_name,party_2019,total_votes_2019,total_electors_2019,Total_vote_pc_2019,Voter Turnout Ratio_2019,state Voter Turnout Ratio_2019,winner_pc_2019,party_2014,total_votes_2014,total_electors_2014,Total_vote_pc_2014,Voter Turnout Ratio_2014,state Voter Turnout Ratio_2014,winner_pc_2014
0,Andhra Pradesh,Aruku,YSRCP,562190,1451418,1074538,0.740337,0.803330,win,YSRCP,413191,1272340,909614,0.714914,0.781288,win
1,Andhra Pradesh,Srikakulam,TDP,534544,1553860,1157329,0.744809,0.803330,win,TDP,556545,1413726,1052115,0.744214,0.781288,win
2,Andhra Pradesh,Vizianagaram,YSRCP,578418,1503980,1217890,0.809778,0.803330,win,TDP,536549,1403736,1120316,0.798096,0.781288,win
3,Andhra Pradesh,Visakhapatnam,YSRCP,436906,1829300,1239754,0.677720,0.803330,win,BJP,566832,1723011,1163558,0.675305,0.781288,win
4,Andhra Pradesh,Anakapalli,YSRCP,586226,1521363,1238491,0.814067,0.803330,win,TDP,568463,1401474,1148072,0.819189,0.781288,win
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555,NCT OF Delhi,NORTH WEST DELHI,BJP,848663,2378995,1402962,0.589729,0.605199,win,BJP,629860,2194343,1356036,0.617969,0.651991,win
556,NCT OF Delhi,WEST DELHI,BJP,865648,2371644,1441601,0.607849,0.605199,win,BJP,651395,2039410,1347971,0.660961,0.651991,win
557,NCT OF Delhi,SOUTH DELHI,BJP,687014,2067463,1214222,0.587300,0.605199,win,BJP,497980,1752748,1102410,0.628961,0.651991,win
558,Lakshadweep,Lakshadweep,NCP,22851,55189,47009,0.851782,0.851782,win,NCP,21665,49922,43239,0.866131,0.866131,win
559,Puducherry,Puducherry,INC,444981,973410,790760,0.812361,0.812361,win,AINRC,255826,901357,740017,0.821003,0.821003,win

In [49]:
new_party = new_party19[new_party19["party_2019"]!= new_party19["party_2014"]].drop_duplicates(subset=["state", "pc_name", "party_2019"])
new_party

,state,pc_name,party_2019,total_votes_2019,total_electors_2019,Total_vote_pc_2019,Voter Turnout Ratio_2019,state Voter Turnout Ratio_2019,winner_pc_2019,party_2014,total_votes_2014,total_electors_2014,Total_vote_pc_2014,Voter Turnout Ratio_2014,state Voter Turnout Ratio_2014,winner_pc_2014
2,Andhra Pradesh,Vizianagaram,YSRCP,578418,1503980,1217890,0.809778,0.803330,win,TDP,536549,1403736,1120316,0.798096,0.781288,win
3,Andhra Pradesh,Visakhapatnam,YSRCP,436906,1829300,1239754,0.677720,0.803330,win,BJP,566832,1723011,1163558,0.675305,0.781288,win
4,Andhra Pradesh,Anakapalli,YSRCP,586226,1521363,1238491,0.814067,0.803330,win,TDP,568463,1401474,1148072,0.819189,0.781288,win
5,Andhra Pradesh,Kakinada,YSRCP,537630,1563930,1234655,0.789457,0.803330,win,TDP,514402,1418290,1099999,0.775581,0.781288,win
6,Andhra Pradesh,Amalapuram,YSRCP,485958,1459556,1232895,0.844706,0.803330,win,TDP,594547,1357865,1120927,0.825507,0.781288,win
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
542,Telangana,Nagarkurnool,TRS,499672,1588111,989847,0.623286,0.644027,win,INC,420075,1477305,1108968,0.750670,0.716444,win
544,Telangana,Bhongir,INC,532795,1628033,1212631,0.744844,0.644027,win,TRS,448164,1492240,1211732,0.812022,0.716444,win
547,Telangana,Khammam,TRS,567459,1513809,1139831,0.752956,0.644027,win,YSRCP,422434,1440267,1183849,0.821965,0.716444,win
548,Andaman & Nicobar Islands,Andaman & Nicobar Islands,INC,95308,318471,207296,0.650910,0.650910,win,BJP,90969,269360,190328,0.706593,0.706593,win
559,Puducherry,Puducherry,INC,444981,973410,790760,0.812361,0.812361,win,AINRC,255826,901357,740017,0.821003,0.821003,win

In [50]:
new_party["winner_vote_difference"] = new_party["total_votes_2019"] - new_party["total_votes_2014"]
new_party

,state,pc_name,party_2019,total_votes_2019,total_electors_2019,Total_vote_pc_2019,Voter Turnout Ratio_2019,state Voter Turnout Ratio_2019,winner_pc_2019,party_2014,total_votes_2014,total_electors_2014,Total_vote_pc_2014,Voter Turnout Ratio_2014,state Voter Turnout Ratio_2014,winner_pc_2014,winner_vote_difference
2,Andhra Pradesh,Vizianagaram,YSRCP,578418,1503980,1217890,0.809778,0.803330,win,TDP,536549,1403736,1120316,0.798096,0.781288,win,41869
3,Andhra Pradesh,Visakhapatnam,YSRCP,436906,1829300,1239754,0.677720,0.803330,win,BJP,566832,1723011,1163558,0.675305,0.781288,win,-129926
4,Andhra Pradesh,Anakapalli,YSRCP,586226,1521363,1238491,0.814067,0.803330,win,TDP,568463,1401474,1148072,0.819189,0.781288,win,17763
5,Andhra Pradesh,Kakinada,YSRCP,537630,1563930,1234655,0.789457,0.803330,win,TDP,514402,1418290,1099999,0.775581,0.781288,win,23228
6,Andhra Pradesh,Amalapuram,YSRCP,485958,1459556,1232895,0.844706,0.803330,win,TDP,594547,1357865,1120927,0.825507,0.781288,win,-108589
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
542,Telangana,Nagarkurnool,TRS,499672,1588111,989847,0.623286,0.644027,win,INC,420075,1477305,1108968,0.750670,0.716444,win,79597
544,Telangana,Bhongir,INC,532795,1628033,1212631,0.744844,0.644027,win,TRS,448164,1492240,1211732,0.812022,0.716444,win,84631
547,Telangana,Khammam,TRS,567459,1513809,1139831,0.752956,0.644027,win,YSRCP,422434,1440267,1183849,0.821965,0.716444,win,145025
548,Andaman & Nicobar Islands,Andaman & Nicobar Islands,INC,95308,318471,207296,0.650910,0.650910,win,BJP,90969,269360,190328,0.706593,0.706593,win,4339
559,Puducherry,Puducherry,INC,444981,973410,790760,0.812361,0.812361,win,AINRC,255826,901357,740017,0.821003,0.821003,win,189155

### Top 10 With positve difference of no. of votes

In [51]:
new_party.sort_values(by="winner_vote_difference", ascending=False).head(10)

,state,pc_name,party_2019,total_votes_2019,total_electors_2019,Total_vote_pc_2019,Voter Turnout Ratio_2019,state Voter Turnout Ratio_2019,winner_pc_2019,party_2014,total_votes_2014,total_electors_2014,Total_vote_pc_2014,Voter Turnout Ratio_2014,state Voter Turnout Ratio_2014,winner_pc_2014,winner_vote_difference
200,Kerala,Idukki,INC,498493,1204191,919297,0.763415,0.778187,win,IND,629,1158735,819766,0.707466,0.739687,win,497864
193,Kerala,Chalakudy,INC,473444,1230197,990224,0.804931,0.778187,win,IND,1376,1150497,884033,0.768392,0.739687,win,472068
474,West Bengal,Alipurduars,BJP,750804,1648383,1380217,0.837316,0.816427,win,AITC,362453,1470911,1223566,0.831842,0.821732,win,388351
181,Karnataka,Chikkballapur,BJP,745912,1808780,1386963,0.766795,0.696789,win,INC,424800,1658410,1263274,0.761738,0.677213,win,321112
400,Uttar Pradesh,Sambhal,SP,658006,1828764,1183469,0.647141,0.592668,win,BJP,360242,1693229,1057002,0.624252,0.585812,win,297764
182,Karnataka,Kolar,BJP,709165,1629961,1258551,0.772136,0.696789,win,INC,418926,1492977,1127315,0.755079,0.677213,win,290239
58,Bihar,Jhanjharpur,JD(U),602391,1852417,1060562,0.572529,0.575000,win,BJP,335481,1668405,941249,0.564161,0.564769,win,266910
475,West Bengal,Jalpaiguri,BJP,760145,1735464,1500922,0.864853,0.816427,win,AITC,494773,1531469,1302117,0.850241,0.821732,win,265372
59,Bihar,Supaul,JD(U),597377,1690620,1110805,0.657040,0.575000,win,INC,332927,1525583,970528,0.636169,0.564769,win,264450
467,Uttar Pradesh,Ghazipur,BSP,566082,1881077,1105627,0.587763,0.592668,win,BJP,306929,1801519,986673,0.547689,0.585812,win,259153

In [52]:
new_party["winner_vote_difference"] = abs(new_party["total_votes_2019"] - new_party["total_votes_2014"])
new_party

,state,pc_name,party_2019,total_votes_2019,total_electors_2019,Total_vote_pc_2019,Voter Turnout Ratio_2019,state Voter Turnout Ratio_2019,winner_pc_2019,party_2014,total_votes_2014,total_electors_2014,Total_vote_pc_2014,Voter Turnout Ratio_2014,state Voter Turnout Ratio_2014,winner_pc_2014,winner_vote_difference
2,Andhra Pradesh,Vizianagaram,YSRCP,578418,1503980,1217890,0.809778,0.803330,win,TDP,536549,1403736,1120316,0.798096,0.781288,win,41869
3,Andhra Pradesh,Visakhapatnam,YSRCP,436906,1829300,1239754,0.677720,0.803330,win,BJP,566832,1723011,1163558,0.675305,0.781288,win,129926
4,Andhra Pradesh,Anakapalli,YSRCP,586226,1521363,1238491,0.814067,0.803330,win,TDP,568463,1401474,1148072,0.819189,0.781288,win,17763
5,Andhra Pradesh,Kakinada,YSRCP,537630,1563930,1234655,0.789457,0.803330,win,TDP,514402,1418290,1099999,0.775581,0.781288,win,23228
6,Andhra Pradesh,Amalapuram,YSRCP,485958,1459556,1232895,0.844706,0.803330,win,TDP,594547,1357865,1120927,0.825507,0.781288,win,108589
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
542,Telangana,Nagarkurnool,TRS,499672,1588111,989847,0.623286,0.644027,win,INC,420075,1477305,1108968,0.750670,0.716444,win,79597
544,Telangana,Bhongir,INC,532795,1628033,1212631,0.744844,0.644027,win,TRS,448164,1492240,1211732,0.812022,0.716444,win,84631
547,Telangana,Khammam,TRS,567459,1513809,1139831,0.752956,0.644027,win,YSRCP,422434,1440267,1183849,0.821965,0.716444,win,145025
548,Andaman & Nicobar Islands,Andaman & Nicobar Islands,INC,95308,318471,207296,0.650910,0.650910,win,BJP,90969,269360,190328,0.706593,0.706593,win,4339
559,Puducherry,Puducherry,INC,444981,973410,790760,0.812361,0.812361,win,AINRC,255826,901357,740017,0.821003,0.821003,win,189155

### Top 10 With absolute difference in no. of votes

In [53]:
new_party.sort_values(by="winner_vote_difference", ascending=False).head(10)

,state,pc_name,party_2019,total_votes_2019,total_electors_2019,Total_vote_pc_2019,Voter Turnout Ratio_2019,state Voter Turnout Ratio_2019,winner_pc_2019,party_2014,total_votes_2014,total_electors_2014,Total_vote_pc_2014,Voter Turnout Ratio_2014,state Voter Turnout Ratio_2014,winner_pc_2014,winner_vote_difference
159,Karnataka,Mandya,IND,1725,1712004,1379210,0.805611,0.696789,win,JD(S),524370,1669262,1192638,0.714470,0.677213,win,522645
200,Kerala,Idukki,INC,498493,1204191,919297,0.763415,0.778187,win,IND,629,1158735,819766,0.707466,0.739687,win,497864
193,Kerala,Chalakudy,INC,473444,1230197,990224,0.804931,0.778187,win,IND,1376,1150497,884033,0.768392,0.739687,win,472068
252,Maharashtra,Amravati,IND,1088,1833091,1112385,0.606836,0.610825,win,SHS,467212,1612739,1004061,0.622581,0.604851,win,466124
474,West Bengal,Alipurduars,BJP,750804,1648383,1380217,0.837316,0.816427,win,AITC,362453,1470911,1223566,0.831842,0.821732,win,388351
181,Karnataka,Chikkballapur,BJP,745912,1808780,1386963,0.766795,0.696789,win,INC,424800,1658410,1263274,0.761738,0.677213,win,321112
400,Uttar Pradesh,Sambhal,SP,658006,1828764,1183469,0.647141,0.592668,win,BJP,360242,1693229,1057002,0.624252,0.585812,win,297764
182,Karnataka,Kolar,BJP,709165,1629961,1258551,0.772136,0.696789,win,INC,418926,1492977,1127315,0.755079,0.677213,win,290239
58,Bihar,Jhanjharpur,JD(U),602391,1852417,1060562,0.572529,0.575000,win,BJP,335481,1668405,941249,0.564161,0.564769,win,266910
475,West Bengal,Jalpaiguri,BJP,760145,1735464,1500922,0.864853,0.816427,win,AITC,494773,1531469,1302117,0.850241,0.821732,win,265372

# 5. Top 5 candidates based on margin difference with runners in 2014 and 2019.

In [54]:
df14

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio,state Voter Turnout Ratio,winner_pc
0,Telangana,Adilabad,GODAM NAGESH,M,49.0,ST,TRS,Car,425762,5085,430847,1386282,1045839,0.754420,0.716444,win
1,Telangana,Adilabad,NARESH,M,37.0,ST,INC,Hand,257994,1563,259557,1386282,1045839,0.754420,0.716444,Not
2,Telangana,Adilabad,RAMESH RATHOD,M,48.0,ST,TDP,Bicycle,182879,1319,184198,1386282,1045839,0.754420,0.716444,Not
3,Telangana,Adilabad,RATHOD SADASHIV,M,55.0,ST,BSP,Elephant,94363,57,94420,1386282,1045839,0.754420,0.716444,Not
4,Telangana,Adilabad,NETHAWATH RAMDAS,M,44.0,ST,IND,Auto- Rickshaw,41028,4,41032,1386282,1045839,0.754420,0.716444,Not
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8350,Puducherry,Puducherry,PUVALA NAGESWARA RAO,M,60.0,GEN,IND,Sewing Machine,465,0,465,901357,740017,0.821003,0.821003,Not
8351,Puducherry,Puducherry,K. MANJINI,M,41.0,GEN,IND,Coconut,767,0,767,901357,740017,0.821003,0.821003,Not
8352,Puducherry,Puducherry,R. VALAVAN,M,40.0,GEN,IND,Carrom Board,497,0,497,901357,740017,0.821003,0.821003,Not
8353,Puducherry,Puducherry,V. VIJAYA,F,29.0,GEN,IND,Green Chilli,746,0,746,901357,740017,0.821003,0.821003,Not
8354,Puducherry,Puducherry,None of the Above,NaN,NaN,NaN,NOTA,NOTA,22267,1,22268,901357,740017,0.821003,0.821003,Not

In [55]:
df19

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio,state Voter Turnout Ratio,winner_pc
0,Andhra Pradesh,Aruku,KISHORE CHANDRA DEO,MALE,72.0,ST,TDP,Bicycle,336163,1938,338101,1451418,1074538,0.740337,0.803330,Not
1,Andhra Pradesh,Aruku,Dr. KOSURI KASI VISWANADHA VEERA VENKATA SATYA...,MALE,54.0,ST,BJP,Lotus,17578,289,17867,1451418,1074538,0.740337,0.803330,Not
2,Andhra Pradesh,Aruku,GODDETI. MADHAVI,FEMALE,26.0,ST,YSRCP,Ceiling Fan,557561,4629,562190,1451418,1074538,0.740337,0.803330,win
3,Andhra Pradesh,Aruku,SHRUTI DEVI VYRICHERLA,FEMALE,46.0,ST,INC,Hand,17656,74,17730,1451418,1074538,0.740337,0.803330,Not
4,Andhra Pradesh,Aruku,GANGULAIAH VAMPURU.,MALE,49.0,ST,JnP,Glass Tumbler,42245,549,42794,1451418,1074538,0.740337,0.803330,Not
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8592,Puducherry,Puducherry,TIRAVITAMANKAI@LOURDHUMARY,FEMALE,57.0,GENERAL,IND,Slate,870,0,870,973410,790760,0.812361,0.812361,Not
8593,Puducherry,Puducherry,IMS. BALAJI,MALE,32.0,GENERAL,IND,Bat,2546,0,2546,973410,790760,0.812361,0.812361,Not
8594,Puducherry,Puducherry,RAMESH.D,MALE,49.0,SC,IND,Mike,1653,0,1653,973410,790760,0.812361,0.812361,Not
8595,Puducherry,Puducherry,V. RAMAMURTHI,MALE,74.0,GENERAL,IND,Whistle,641,1,642,973410,790760,0.812361,0.812361,Not
8596,Puducherry,Puducherry,NOTA,NaN,NaN,NaN,NOTA,NaN,12192,7,12199,973410,790760,0.812361,0.812361,Not

In [56]:
for state in df19.state.unique():
    state_data = df19[df19["state"] == state]
    
    for pc in state_data.pc_name.unique():
        pc_data = state_data[state_data["pc_name"] == pc]
        
        # Check if there are at least two parties in the current pc_data
        if len(pc_data) > 1:
            # Get the second largest total votes
            second_max_vote = pc_data["total_votes"].nlargest(2).iloc[-1]
            # Get the party with the second largest votes
            win_party = pc_data[pc_data["total_votes"] == second_max_vote]["party"].values[0]
            df19.loc[(df19["state"] == state) & (df19["pc_name"] == pc) & (df19["party"] == win_party), "winner_pc"] = "1st runner"
        else:
            # If there's only one party, handle it according to your specific needs
            pass

In [57]:
df19

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio,state Voter Turnout Ratio,winner_pc
0,Andhra Pradesh,Aruku,KISHORE CHANDRA DEO,MALE,72.0,ST,TDP,Bicycle,336163,1938,338101,1451418,1074538,0.740337,0.803330,1st runner
1,Andhra Pradesh,Aruku,Dr. KOSURI KASI VISWANADHA VEERA VENKATA SATYA...,MALE,54.0,ST,BJP,Lotus,17578,289,17867,1451418,1074538,0.740337,0.803330,Not
2,Andhra Pradesh,Aruku,GODDETI. MADHAVI,FEMALE,26.0,ST,YSRCP,Ceiling Fan,557561,4629,562190,1451418,1074538,0.740337,0.803330,win
3,Andhra Pradesh,Aruku,SHRUTI DEVI VYRICHERLA,FEMALE,46.0,ST,INC,Hand,17656,74,17730,1451418,1074538,0.740337,0.803330,Not
4,Andhra Pradesh,Aruku,GANGULAIAH VAMPURU.,MALE,49.0,ST,JnP,Glass Tumbler,42245,549,42794,1451418,1074538,0.740337,0.803330,Not
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8592,Puducherry,Puducherry,TIRAVITAMANKAI@LOURDHUMARY,FEMALE,57.0,GENERAL,IND,Slate,870,0,870,973410,790760,0.812361,0.812361,Not
8593,Puducherry,Puducherry,IMS. BALAJI,MALE,32.0,GENERAL,IND,Bat,2546,0,2546,973410,790760,0.812361,0.812361,Not
8594,Puducherry,Puducherry,RAMESH.D,MALE,49.0,SC,IND,Mike,1653,0,1653,973410,790760,0.812361,0.812361,Not
8595,Puducherry,Puducherry,V. RAMAMURTHI,MALE,74.0,GENERAL,IND,Whistle,641,1,642,973410,790760,0.812361,0.812361,Not
8596,Puducherry,Puducherry,NOTA,NaN,NaN,NaN,NOTA,NaN,12192,7,12199,973410,790760,0.812361,0.812361,Not

In [58]:
df19[df19["winner_pc"]=="win"].drop_duplicates(subset=["state", "pc_name"])

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio,state Voter Turnout Ratio,winner_pc
2,Andhra Pradesh,Aruku,GODDETI. MADHAVI,FEMALE,26.0,ST,YSRCP,Ceiling Fan,557561,4629,562190,1451418,1074538,0.740337,0.803330,win
11,Andhra Pradesh,Srikakulam,KINJARAPU RAM MOHAN NAIDU,MALE,32.0,GENERAL,TDP,Bicycle,529213,5331,534544,1553860,1157329,0.744809,0.803330,win
23,Andhra Pradesh,Vizianagaram,Bellana Chandra Sekhar,MALE,57.0,GENERAL,YSRCP,Ceiling Fan,573466,4952,578418,1503980,1217890,0.809778,0.803330,win
39,Andhra Pradesh,Visakhapatnam,M V V SATYANARAYANA,MALE,52.0,GENERAL,YSRCP,Ceiling Fan,433968,2938,436906,1829300,1239754,0.677720,0.803330,win
53,Andhra Pradesh,Anakapalli,Dr.Beesetti Venkata Satyavathi,FEMALE,52.0,GENERAL,YSRCP,Ceiling Fan,583210,3016,586226,1521363,1238491,0.814067,0.803330,win
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8509,NCT OF Delhi,NORTH WEST DELHI,HANS RAJ HANS,MALE,57.0,SC,BJP,Lotus,847737,926,848663,2378995,1402962,0.589729,0.605199,win
8519,NCT OF Delhi,WEST DELHI,PARVESH SAHIB SINGH VERMA,MALE,41.0,GENERAL,BJP,Lotus,862058,3590,865648,2371644,1441601,0.607849,0.605199,win
8543,NCT OF Delhi,SOUTH DELHI,RAMESH BIDHURI,MALE,57.0,GENERAL,BJP,Lotus,685789,1225,687014,2067463,1214222,0.587300,0.605199,win
8573,Lakshadweep,Lakshadweep,MOHAMMED FAIZAL PP,MALE,43.0,ST,NCP,Clock,22796,55,22851,55189,47009,0.851782,0.851782,win
8580,Puducherry,Puducherry,Ve. VAITHILINGAM,MALE,68.0,GENERAL,INC,Hand,444646,335,444981,973410,790760,0.812361,0.812361,win

In [59]:
df19[df19["winner_pc"] == "1st runner"].drop_duplicates(subset=["state", "pc_name"])

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio,state Voter Turnout Ratio,winner_pc
0,Andhra Pradesh,Aruku,KISHORE CHANDRA DEO,MALE,72.0,ST,TDP,Bicycle,336163,1938,338101,1451418,1074538,0.740337,0.803330,1st runner
13,Andhra Pradesh,Srikakulam,DUVVADA SRINIVAS,MALE,52.0,GENERAL,YSRCP,Ceiling Fan,520931,6960,527891,1553860,1157329,0.744809,0.803330,1st runner
21,Andhra Pradesh,Vizianagaram,Ashok Gajapathi Raju Pusapati,MALE,67.0,GENERAL,TDP,Bicycle,527307,3075,530382,1503980,1217890,0.809778,0.803330,1st runner
38,Andhra Pradesh,Visakhapatnam,BHARAT MATHUKUMILLI,MALE,29.0,GENERAL,TDP,Bicycle,431093,1399,432492,1829300,1239754,0.677720,0.803330,1st runner
51,Andhra Pradesh,Anakapalli,ADARI ANAND KUMAR,MALE,43.0,GENERAL,TDP,Bicycle,495381,1653,497034,1521363,1238491,0.814067,0.803330,1st runner
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8507,NCT OF Delhi,NORTH WEST DELHI,GUGAN SINGH,MALE,70.0,SC,AAAP,Broom,294662,104,294766,2378995,1402962,0.589729,0.605199,1st runner
8521,NCT OF Delhi,WEST DELHI,MAHABAL MISHRA,MALE,64.0,GENERAL,INC,Hand,286745,417,287162,2371644,1441601,0.607849,0.605199,1st runner
8544,NCT OF Delhi,SOUTH DELHI,RAGHAV CHADHA,MALE,30.0,GENERAL,AAAP,Broom,319770,201,319971,2067463,1214222,0.587300,0.605199,1st runner
8575,Lakshadweep,Lakshadweep,HAMDULLAH SAYEED,MALE,36.0,ST,INC,Hand,21980,48,22028,55189,47009,0.851782,0.851782,1st runner
8578,Puducherry,Puducherry,Dr. NARAYANASAMY KESAVAN,MALE,29.0,GENERAL,AINRC,Jug,247844,112,247956,973410,790760,0.812361,0.812361,1st runner

In [60]:
winner = df19[df19["winner_pc"]=="win"].drop_duplicates(subset=["state", "pc_name", "party"])
runner = df19[df19["winner_pc"] == "1st runner"].drop_duplicates(subset=["state", "pc_name", "party"])

In [61]:
winner["margin difference"] = 0  # Initialize the margin difference column

for state in winner.state.unique():
    state_data = winner[winner["state"] == state]
    
    for pc in state_data.pc_name.unique():
        winner_mask = (winner["state"] == state) & (winner["pc_name"] == pc)
        runner_mask = (runner["state"] == state) & (runner["pc_name"] == pc)
        
        winner_votes = winner.loc[winner_mask, "total_votes"].values
        runner_votes = runner.loc[runner_mask, "total_votes"].values
        
        if len(winner_votes) > 0 and len(runner_votes) > 0:
            winner.loc[winner_mask, "margin difference"] = winner_votes[0] - runner_votes[0]

winner

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio,state Voter Turnout Ratio,winner_pc,margin difference
2,Andhra Pradesh,Aruku,GODDETI. MADHAVI,FEMALE,26.0,ST,YSRCP,Ceiling Fan,557561,4629,562190,1451418,1074538,0.740337,0.803330,win,224089
11,Andhra Pradesh,Srikakulam,KINJARAPU RAM MOHAN NAIDU,MALE,32.0,GENERAL,TDP,Bicycle,529213,5331,534544,1553860,1157329,0.744809,0.803330,win,6653
23,Andhra Pradesh,Vizianagaram,Bellana Chandra Sekhar,MALE,57.0,GENERAL,YSRCP,Ceiling Fan,573466,4952,578418,1503980,1217890,0.809778,0.803330,win,48036
39,Andhra Pradesh,Visakhapatnam,M V V SATYANARAYANA,MALE,52.0,GENERAL,YSRCP,Ceiling Fan,433968,2938,436906,1829300,1239754,0.677720,0.803330,win,4414
53,Andhra Pradesh,Anakapalli,Dr.Beesetti Venkata Satyavathi,FEMALE,52.0,GENERAL,YSRCP,Ceiling Fan,583210,3016,586226,1521363,1238491,0.814067,0.803330,win,89192
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8509,NCT OF Delhi,NORTH WEST DELHI,HANS RAJ HANS,MALE,57.0,SC,BJP,Lotus,847737,926,848663,2378995,1402962,0.589729,0.605199,win,553897
8519,NCT OF Delhi,WEST DELHI,PARVESH SAHIB SINGH VERMA,MALE,41.0,GENERAL,BJP,Lotus,862058,3590,865648,2371644,1441601,0.607849,0.605199,win,578486
8543,NCT OF Delhi,SOUTH DELHI,RAMESH BIDHURI,MALE,57.0,GENERAL,BJP,Lotus,685789,1225,687014,2067463,1214222,0.587300,0.605199,win,367043
8573,Lakshadweep,Lakshadweep,MOHAMMED FAIZAL PP,MALE,43.0,ST,NCP,Clock,22796,55,22851,55189,47009,0.851782,0.851782,win,823
8580,Puducherry,Puducherry,Ve. VAITHILINGAM,MALE,68.0,GENERAL,INC,Hand,444646,335,444981,973410,790760,0.812361,0.812361,win,197025

### Top 5 candidates based on margin difference with runners in 2019.

In [62]:
winner.sort_values(by="margin difference", ascending=False).head(5)

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio,state Voter Turnout Ratio,winner_pc,margin difference
1559,Gujarat,Navsari,C. R. Patil,MALE,64.0,GENERAL,BJP,Lotus,969430,3309,972739,1971658,1308018,0.663410,0.644250,win,689668
1689,Haryana,Karnal,Sanjay Bhatia,MALE,51.0,GENERAL,BJP,Lotus,909432,2162,911594,1904193,1300722,0.683083,0.704482,win,656142
1800,Haryana,Faridabad,KRISHAN PAL,MALE,62.0,GENERAL,BJP,Lotus,910787,2435,913222,2071816,1327295,0.640643,0.704482,win,638239
4873,Rajasthan,Bhilwara,SUBHASH CHANDRA BAHERIA,MALE,62.0,GENERAL,BJP,Lotus,936065,2095,938160,1997328,1310513,0.656133,0.661938,win,612000
1492,Gujarat,Vadodara,RANJANBEN BHATT,FEMALE,56.0,GENERAL,BJP,Lotus,880905,2814,883719,1794896,1222348,0.681013,0.644250,win,589177

In [63]:
for state in df14.state.unique():
    state_data = df14[df14["state"] == state]
    
    for pc in state_data.pc_name.unique():
        pc_data = state_data[state_data["pc_name"] == pc]
        
        # Check if there are at least two parties in the current pc_data
        if len(pc_data) > 1:
            # Get the second largest total votes
            second_max_vote = pc_data["total_votes"].nlargest(2).iloc[-1]
            # Get the party with the second largest votes
            win_party = pc_data[pc_data["total_votes"] == second_max_vote]["party"].values[0]
            df14.loc[(df14["state"] == state) & (df14["pc_name"] == pc) & (df14["party"] == win_party), "winner_pc"] = "1st runner"
        else:
            # If there's only one party, handle it according to your specific needs
            pass

In [64]:
df14[df14["winner_pc"]=="win"].drop_duplicates(subset=["state", "pc_name"])

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio,state Voter Turnout Ratio,winner_pc
0,Telangana,Adilabad,GODAM NAGESH,M,49.0,ST,TRS,Car,425762,5085,430847,1386282,1045839,0.754420,0.716444,win
11,Telangana,Peddapalle,BALKA SUMAN,M,31.0,SC,TRS,Car,563214,2282,565496,1425355,1022184,0.717143,0.716444,win
31,Telangana,Karimnagar,VINOD KUMAR BOINAPALLY,M,54.0,GEN,TRS,Car,503197,2161,505358,1550810,1125184,0.725546,0.716444,win
46,Telangana,Nizamabad,KALVAKUNTLA KAVITHA,F,36.0,GEN,TRS,Car,435706,3601,439307,1496193,1033924,0.691037,0.716444,win
62,Telangana,Zahirabad,B.B. PATIL,M,58.0,GEN,TRS,Car,505983,2678,508661,1445354,1094806,0.757466,0.716444,win
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8264,NCT OF Delhi,NORTH WEST DELHI,UDIT RAJ,M,56.0,SC,BJP,Lotus,627529,2331,629860,2194343,1356036,0.617969,0.651991,win
8280,NCT OF Delhi,WEST DELHI,PARVESH SAHIB SINGH VERMA,M,36.0,GEN,BJP,Lotus,649542,1853,651395,2039410,1347971,0.660961,0.651991,win
8299,NCT OF Delhi,SOUTH DELHI,RAMESH BIDHURI,M,52.0,GEN,BJP,Lotus,497151,829,497980,1752748,1102410,0.628961,0.651991,win
8319,Lakshadweep,Lakshadweep,MOHAMMED FAIZAL P.P.,M,38.0,ST,NCP,Clock,21665,0,21665,49922,43239,0.866131,0.866131,win
8325,Puducherry,Puducherry,R. RADHAKRISHNAN,M,42.0,GEN,AINRC,Jug,255732,94,255826,901357,740017,0.821003,0.821003,win

In [65]:
df14[df14["winner_pc"] == "1st runner"].drop_duplicates(subset=["state", "pc_name"])

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio,state Voter Turnout Ratio,winner_pc
1,Telangana,Adilabad,NARESH,M,37.0,ST,INC,Hand,257994,1563,259557,1386282,1045839,0.754420,0.716444,1st runner
12,Telangana,Peddapalle,G. VIVEKANAND,M,56.0,SC,INC,Hand,273441,897,274338,1425355,1022184,0.717143,0.716444,1st runner
28,Telangana,Karimnagar,PONNAM PRABHAKAR,M,47.0,GEN,INC,Hand,298386,2320,300706,1550810,1125184,0.725546,0.716444,1st runner
48,Telangana,Nizamabad,MADHU YASKHI GOUD,M,56.0,GEN,INC,Hand,270948,1175,272123,1496193,1033924,0.691037,0.716444,1st runner
65,Telangana,Zahirabad,SURESH KUMAR SHETKAR,M,53.0,GEN,INC,Hand,362939,1091,364030,1445354,1094806,0.757466,0.716444,1st runner
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8267,NCT OF Delhi,NORTH WEST DELHI,RAKHI BIRLA,F,27.0,SC,AAAP,Broom,522842,216,523058,2194343,1356036,0.617969,0.651991,1st runner
8279,NCT OF Delhi,WEST DELHI,JARNAIL SINGH,M,41.0,GEN,AAAP,Broom,382610,199,382809,2039410,1347971,0.660961,0.651991,1st runner
8297,NCT OF Delhi,SOUTH DELHI,COL DEVINDER SEHRAWAT,M,48.0,GEN,AAAP,Broom,390858,122,390980,1752748,1102410,0.628961,0.651991,1st runner
8321,Lakshadweep,Lakshadweep,HAMDULLAH SAYEED,M,31.0,ST,INC,Hand,20130,0,20130,49922,43239,0.866131,0.866131,1st runner
8328,Puducherry,Puducherry,V. NARAYANASAMY,M,66.0,GEN,INC,Hand,194873,99,194972,901357,740017,0.821003,0.821003,1st runner

In [66]:
winner = df14[df14["winner_pc"]=="win"].drop_duplicates(subset=["state", "pc_name", "party"])
runner = df14[df14["winner_pc"] == "1st runner"].drop_duplicates(subset=["state", "pc_name", "party"])

In [67]:
winner["margin difference"] = 0  # Initialize the margin difference column

for state in winner.state.unique():
    state_data = winner[winner["state"] == state]
    
    for pc in state_data.pc_name.unique():
        winner_mask = (winner["state"] == state) & (winner["pc_name"] == pc)
        runner_mask = (runner["state"] == state) & (runner["pc_name"] == pc)
        
        winner_votes = winner.loc[winner_mask, "total_votes"].values
        runner_votes = runner.loc[runner_mask, "total_votes"].values
        
        if len(winner_votes) > 0 and len(runner_votes) > 0:
            winner.loc[winner_mask, "margin difference"] = winner_votes[0] - runner_votes[0]

winner

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio,state Voter Turnout Ratio,winner_pc,margin difference
0,Telangana,Adilabad,GODAM NAGESH,M,49.0,ST,TRS,Car,425762,5085,430847,1386282,1045839,0.754420,0.716444,win,171290
11,Telangana,Peddapalle,BALKA SUMAN,M,31.0,SC,TRS,Car,563214,2282,565496,1425355,1022184,0.717143,0.716444,win,291158
31,Telangana,Karimnagar,VINOD KUMAR BOINAPALLY,M,54.0,GEN,TRS,Car,503197,2161,505358,1550810,1125184,0.725546,0.716444,win,204652
46,Telangana,Nizamabad,KALVAKUNTLA KAVITHA,F,36.0,GEN,TRS,Car,435706,3601,439307,1496193,1033924,0.691037,0.716444,win,167184
62,Telangana,Zahirabad,B.B. PATIL,M,58.0,GEN,TRS,Car,505983,2678,508661,1445354,1094806,0.757466,0.716444,win,144631
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8264,NCT OF Delhi,NORTH WEST DELHI,UDIT RAJ,M,56.0,SC,BJP,Lotus,627529,2331,629860,2194343,1356036,0.617969,0.651991,win,106802
8280,NCT OF Delhi,WEST DELHI,PARVESH SAHIB SINGH VERMA,M,36.0,GEN,BJP,Lotus,649542,1853,651395,2039410,1347971,0.660961,0.651991,win,268586
8299,NCT OF Delhi,SOUTH DELHI,RAMESH BIDHURI,M,52.0,GEN,BJP,Lotus,497151,829,497980,1752748,1102410,0.628961,0.651991,win,107000
8319,Lakshadweep,Lakshadweep,MOHAMMED FAIZAL P.P.,M,38.0,ST,NCP,Clock,21665,0,21665,49922,43239,0.866131,0.866131,win,1535
8325,Puducherry,Puducherry,R. RADHAKRISHNAN,M,42.0,GEN,AINRC,Jug,255732,94,255826,901357,740017,0.821003,0.821003,win,60854

### Top 5 candidates based on margin difference with runners in 2014

In [68]:
winner.sort_values(by="margin difference", ascending=False).head(5)

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio,state Voter Turnout Ratio,winner_pc,margin difference
1777,Gujarat,Vadodara,NARENDRA MODI,M,63.0,GEN,BJP,Lotus,841592,3872,845464,1638321,1161577,0.709005,0.636062,win,570128
6062,Uttar Pradesh,Ghaziabad,VIJAY KUMAR SINGH,M,62.0,GEN,BJP,Lotus,758113,369,758482,2357553,1342321,0.569370,0.585812,win,567260
1827,Gujarat,Navsari,C. R. PATIL,M,59.0,GEN,BJP,Lotus,818367,2464,820831,1764622,1160747,0.657788,0.636062,win,558116
4716,Rajasthan,Jaipur,RAMCHARAN BOHARA,M,56.0,GEN,BJP,Lotus,859973,3385,863358,1957820,1296806,0.662372,0.630196,win,539345
1818,Gujarat,Surat,DARSHANA VIKRAM JARDOSH,F,53.0,GEN,BJP,Lotus,717429,983,718412,1484068,947922,0.638732,0.636062,win,533190

# 6. % Split of votes of parties between 2014 vs 2019 at national level

In [69]:
parties = {"party" : [],
          "total_votes" : [],
          "percent_of_vote" : []}
for party in df14.party.unique():
    parties["party"] += [party]
    parties["total_votes"] += [df14[df14["party"]==party].total_votes.sum()]
    parties["percent_of_vote"] += [round((df14[df14["party"]==party].total_votes.sum()/df14.total_votes.sum())*100, 2)]
percent_split_national_2014 = pd.DataFrame(parties)
percent_split_national_2014

     party  total_votes  percent_of_vote
0      TRS      6736270             1.30
1      INC     96641749            18.58
2      TDP     14099230             2.71
3      BSP     22434033             4.31
4      IND     15888094             3.06
..     ...          ...              ...
448   BVLP          161             0.00
449   ABSP          651             0.00
450   RJAP          415             0.00
451   JSMP          357             0.00
452  AINRC       255826             0.05

[453 rows x 3 columns]

### % Split of votes of parties between 2014 at national level

In [70]:
percent_split_national_2014.sort_values(by="percent_of_vote", ascending=False)

     party  total_votes  percent_of_vote
12     BJP    161047761            30.97
1      INC     96641749            18.58
3      BSP     22434033             4.31
64    AITC     21215661             4.08
69      SP     18632568             3.58
..     ...          ...              ...
205  BBPSP         1679             0.00
204   MAHP         2101             0.00
203  BhNaP         1408             0.00
202   bjyp         2000             0.00
226   AwVP         3747             0.00

[453 rows x 3 columns]

In [71]:
parties = {"party" : [],
          "total_votes" : [],
          "percent_of_vote" : []}
for party in df19.party.unique():
    parties["party"] += [party]
    parties["total_votes"] += [df19[df19["party"]==party].total_votes.sum()]
    parties["percent_of_vote"] += [round((df19[df19["party"]==party].total_votes.sum()/df19.total_votes.sum())*100, 2)]
percent_split_national_2019 = pd.DataFrame(parties)
percent_split_national_2019

     party  total_votes  percent_of_vote
0      TDP     12515345             2.04
1      BJP    229076879            37.30
2    YSRCP     15537006             2.53
3      INC    119495214            19.46
4      JnP      1915127             0.31
..     ...          ...              ...
669    BPC          724             0.00
670   SoJP          805             0.00
671    NYP         1053             0.00
672  AINRC       247956             0.04
673  PUDEP         1319             0.00

[674 rows x 3 columns]

### % Split of votes of parties between 2019 at national level

In [72]:
percent_split_national_2019.sort_values(by="percent_of_vote", ascending=False)

     party  total_votes  percent_of_vote
1      BJP    229076879            37.30
3      INC    119495214            19.46
55    AITC     24929330             4.06
34     BSP     22246501             3.62
6      IND     16583326             2.70
..     ...          ...              ...
268     EP         1442             0.00
269   KPPR         3697             0.00
270   rpsn         5982             0.00
271   KPJP         1207             0.00
673  PUDEP         1319             0.00

[674 rows x 3 columns]

### % Split of votes of parties between 2014 vs 2019 at national level

In [73]:
pd.merge(percent_split_national_2019, percent_split_national_2014, how="inner", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
1,BJP,229076879,37.30,161047761,30.97
3,INC,119495214,19.46,96641749,18.58
32,AITC,24929330,4.06,21215661,4.08
20,BSP,22246501,3.62,22434033,4.31
4,IND,16583326,2.70,15888094,3.06
...,...,...,...,...,...
123,MNDP,6198,0.00,11225,0.00
124,SP(I),3916,0.00,41518,0.01
125,BMSM,2484,0.00,3441,0.00
126,ARP,4399,0.00,16461,0.00
139,HiPPa,3750,0.00,8853,0.00

### Verification of no. of parties

In [74]:
len(df14.party.unique())

453

In [75]:
len(df19.party.unique())

674

In [76]:
len(set(df19.party.unique()).intersection(set(df14.party.unique())))

228

# 7. % Split of votes of parties between 2014 vs 2019 at state level.

In [77]:
parties_statewise19 = {state : {"party" : [],
          "total_votes" : [],
          "percent_of_vote" : []} for state in df19.state.unique()}

for state in df19.state.unique():
    for party in df19[df19["state"]==state].party.unique():
        parties_statewise19[state]["party"] += [party]
        parties_statewise19[state]["total_votes"] += [df19[(df19["party"]==party) & (df19["state"]==state)].total_votes.sum()]
        parties_statewise19[state]["percent_of_vote"] += [round((df19[(df19["party"]==party) & (df19["state"]==state)].total_votes.sum()/df19[df19["state"]==state].total_votes.sum())*100, 2)]

parties_statewise19

{'Andhra Pradesh': {'party': ['TDP',
   'BJP',
   'YSRCP',
   'INC',
   'JnP',
   'JAJGP',
   'IND',
   'NOTA',
   'PPOI',
   'SAPRP',
   'ACP',
   'VCK',
   'CPI(ML)(L)',
   'DABAP',
   'MPP',
   'PRSHP',
   'AINPP',
   'AIFB',
   'RPI(KH)',
   'IPBP',
   'APoI',
   'RPC(S)',
   'NVSP',
   'RPI(A)',
   'MCPI',
   'SP',
   'BAHUMP',
   'NRCP',
   'IUML',
   'HMRD',
   'CPIM',
   'ILP(AP)',
   'NDDHP',
   'NNKP',
   'BSP',
   'NPT',
   'AlPP',
   'AYSRCP',
   'ANC',
   'BCUF',
   'SDPI',
   'SUCI(C)',
   'RRS',
   'SMFB',
   'CPI',
   'VJNP',
   'RD',
   'RDHP',
   'JPD',
   'ARPS',
   'RKSP',
   'NavaP'],
  'total_votes': [12515345,
   303985,
   15537006,
   406977,
   1829346,
   11464,
   248025,
   468822,
   27339,
   4983,
   1263,
   4864,
   4440,
   4444,
   7342,
   9738,
   2023,
   1687,
   1804,
   6937,
   1757,
   996,
   4286,
   8614,
   583,
   6753,
   1017,
   1489,
   2387,
   447,
   41111,
   1017,
   628,
   887,
   83613,
   1341,
   370,
   5511,
   1510,
   649,
   7293,
   2184,
   1229,
   2107,
   26536,
   1726,
   1220,
   368,
   913,
   1563,
   3460,
   1135],
  'percent_of_vote': [39.59,
   0.96,
   49.15,
   1.29,
   5.79,
   0.04,
   0.78,
   1.48,
   0.09,
   0.02,
   0.0,
   0.02,
   0.01,
   0.01,
   0.02,
   0.03,
   0.01,
   0.01,
   0.01,
   0.02,
   0.01,
   0.0,
   0.01,
   0.03,
   0.0,
   0.02,
   0.0,
   0.0,
   0.01,
   0.0,
   0.13,
   0.0,
   0.0,
   0.0,
   0.26,
   0.0,
   0.0,
   0.02,
   0.0,
   0.0,
   0.02,
   0.01,
   0.0,
   0.01,
   0.08,
   0.01,
   0.0,
   0.0,
   0.0,
   0.0,
   0.01,
   0.0]},
 'Arunachal Pradesh': {'party': ['BJP',
   'INC',
   'PPA',
   'JD(S)',
   'AIFB',
   'NPEP',
   'IND',
   'NOTA'],
  'total_votes': [379679, 134888, 27703, 59878, 1921, 27119, 13439, 7464],
  'percent_of_vote': [58.22, 20.69, 4.25, 9.18, 0.29, 4.16, 2.06, 1.14]},
 'Assam': {'party': ['BJP',
   'AITC',
   'AIUDF',
   'INC',
   'AIFB',
   'HND',
   'SUCI(C)',
   'IND',
   'NOTA',
   'NPEP',
   'ASDC',
   'AGP',
   'PUJP',
   'BNJD',
   'RPI(A)',
   'VPI',
   'BOPF',
   'CPIM',
   'UPPL',
   'NRCong',
   'TNRMPI',
   'BGanP',
   'SwaBP',
   'SP',
   'AJM',
   'NCP',
   'CPI',
   'BMUP',
   'ADRP'],
  'total_votes': [6484596,
   74522,
   1402088,
   6373659,
   5816,
   22031,
   16831,
   868715,
   178353,
   48689,
   36915,
   1480697,
   22415,
   2072,
   11250,
   50355,
   446774,
   40937,
   312435,
   4278,
   3973,
   13039,
   4110,
   2383,
   21678,
   11010,
   31227,
   6933,
   8285],
  'percent_of_vote': [36.05,
   0.41,
   7.8,
   35.44,
   0.03,
   0.12,
   0.09,
   4.83,
   0.99,
   0.27,
   0.21,
   8.23,
   0.12,
   0.01,
   0.06,
   0.28,
   2.48,
   0.23,
   1.74,
   0.02,
   0.02,
   0.07,
   0.02,
   0.01,
   0.12,
   0.06,
   0.17,
   0.04,
   0.05]},
 'Bihar': {'party': ['BSP',
   'JD(U)',
   'INC',
   'BLND',
   'SBSP',
   'JKiP',
   'RAHIS',
   'RSJVP',
   'BBC',
   'SHS',
   'IND',
   'NOTA',
   'BLSP',
   'BJP',
   'LAJSP',
   'CPI',
   'RMGP',
   'JPS',
   'JP',
   'ASDHP',
   'JDR',
   'RJBP',
   'RSPSR',
   'BJKVP',
   'AKBHAD',
   'SSD',
   'BNDl',
   'NCP',
   'RJD',
   'JANADIP',
   'BJAZP',
   'AIFB',
   'BHAPRAP',
   'KPOI',
   'AAAP',
   'BMtrP',
   'PBI',
   'AKBMP',
   'PSPL',
   'VSIP',
   'BMUP',
   'VPI',
   'RPI(A)',
   'PUJP',
   'PPID',
   'SJDD',
   'AMiP',
   'AAM',
   'JHP',
   'RVNP',
   'VCSMP',
   'JKNPP',
   'LSD',
   'AJPR',
   'AITC',
   'AIMIM',
   'JMM',
   'BALP',
   'JAPL',
   'mimm',
   'BMF',
   'RRP',
   'AAHPty',
   'SUCI(C)',
   'BhNP',
   'YKP',
   'LJP',
   'JTVP',
   'LCD',
   'RPP',
   'SPAKP',
   'GJNP',
   'JPJD',
   'CPI(ML)(L)',
   'BSSPA',
   'SWSP',
   'RSTSAHP',
   'SANVP',
   'BJKD',
   'ManJP',
   'BNSKP',
   'JGHTP',
   'BHAIP',
   'PMPT',
   'SAAFP',
   'CPIM',
   'JRVP',
   'WAP',
   'BLRP',
   'PSS',
   'BDlP',
   'SaBP',
   'HAMS',
   'BIP',
   'NJP',
   'HND',
   'SGUP',
   'RPI',
   'PMP',
   'RJPD',
   'RACHEP',
   'APKSP',
   'BhAmAP',
   'BKVP',
   'ABJS',
   'RDU',
   'LJVM',
   'APoI',
   'SP',
   'RSWD',
   'SPL',
   'ANC',
   'AHFBK',
   'ravp',
   'BRM',
   'MOSP',
   'MADP',
   'BBMP',
   'RUC'],
  'total_votes': [682428,
   8902719,
   3140797,
   32445,
   36617,
   9264,
   67782,
   6497,
   19003,
   64462,
   2225474,
   816950,
   1462518,
   9619548,
   9868,
   280250,
   16371,
   1793,
   13467,
   11598,
   27584,
   37610,
   55803,
   40906,
   4378,
   54483,
   26065,
   38991,
   6270769,
   34770,
   1814,
   16454,
   4965,
   3064,
   26147,
   12737,
   5965,
   10127,
   20434,
   660706,
   63443,
   42919,
   10283,
   5074,
   55477,
   25630,
   11311,
   32218,
   13693,
   10721,
   17856,
   3545,
   6313,
   31017,
   5483,
   295029,
   30853,
   12270,
   97631,
   4413,
   23765,
   3195,
   3434,
   33146,
   5674,
   30492,
   3206979,
   17955,
   2384,
   2718,
   3978,
   11678,
   17791,
   545096,
   3615,
   2069,
   2756,
   2364,
   23414,
   6267,
   2640,
   6171,
   1613,
   11081,
   8643,
   27577,
   2364,
   29392,
   4208,
   2830,
   15376,
   6395,
   956501,
   2231,
   4444,
   10966,
   6514,
   6428,
   13238,
   1414,
   1975,
   8354,
   9628,
   3778,
   3597,
   1907,
   9278,
   25234,
   2881,
   8381,
   15132,
   12431,
   23252,
   9109,
   7944,
   17980,
   14532,
   9894,
   3776],
  'percent_of_vote': [1.67,
   21.82,
   7.7,
   0.08,
   0.09,
   0.02,
   0.17,
   0.02,
   0.05,
   0.16,
   5.45,
   2.0,
   3.58,
   23.57,
   0.02,
   0.69,
   0.04,
   0.0,
   0.03,
   0.03,
   0.07,
   0.09,
   0.14,
   0.1,
   0.01,
   0.13,
   0.06,
   0.1,
   15.37,
   0.09,
   0.0,
   0.04,
   0.01,
   0.01,
   0.06,
   0.03,
   0.01,
   0.02,
   0.05,
   1.62,
   0.16,
   0.11,
   0.03,
   0.01,
   0.14,
   0.06,
   0.03,
   0.08,
   0.03,
   0.03,
   0.04,
   0.01,
   0.02,
   0.08,
   0.01,
   0.72,
   0.08,
   0.03,
   0.24,
   0.01,
   0.06,
   0.01,
   0.01,
   0.08,
   0.01,
   0.07,
   7.86,
   0.04,
   0.01,
   0.01,
   0.01,
   0.03,
   0.04,
   1.34,
   0.01,
   0.01,
   0.01,
   0.01,
   0.06,
   0.02,
   0.01,
   0.02,
   0.0,
   0.03,
   0.02,
   0.07,
   0.01,
   0.07,
   0.01,
   0.01,
   0.04,
   0.02,
   2.34,
   0.01,
   0.01,
   0.03,
   0.02,
   0.02,
   0.03,
   0.0,
   0.0,
   0.02,
   0.02,
   0.01,
   0.01,
   0.0,
   0.02,
   0.06,
   0.01,
   0.02,
   0.04,
   0.03,
   0.06,
   0.02,
   0.02,
   0.04,
   0.04,
   0.02,
   0.01]},
 'Goa': {'party': ['INC', 'BJP', 'RPI(KM)', 'AAAP', 'IND', 'NOTA', 'SHS'],
  'total_votes': [366158, 436650, 2809, 25647, 7677, 12499, 1763],
  'percent_of_vote': [42.92, 51.18, 0.33, 3.01, 0.9, 1.46, 0.21]},
 'Gujarat': {'party': ['BJP',
   'INC',
   'BSP',
   'HND',
   'aicp',
   'BMUP',
   'RPWP',
   'IND',
   'NOTA',
   'GAGUP',
   'NCP',
   'BRP',
   'YJJP',
   'BTP',
   'BNJD',
   'RVZP',
   'JANSAPP',
   'PPID',
   'RTORP',
   'BSDL',
   'ANC',
   'LoRP',
   'SABHP',
   'JSVP',
   'LOGAP',
   'PAP',
   'MaNPa',
   'NIRBHP',
   'APoI',
   'VPP',
   'GJPP',
   'BAHUMP',
   'RSP(S)',
   'SVPP',
   'ABJS',
   'ADPT',
   'AINHCP',
   'SUCI(C)',
   'BMFP',
   'SANVP',
   'BARESP',
   'STBSP',
   'CPI',
   'PPOI',
   'YuS',
   'REALDP',
   'BBC',
   'BSCP',
   'RNNBP',
   'RSPS'],
  'total_votes': [18091275,
   9337084,
   249184,
   22482,
   3391,
   20823,
   3762,
   626629,
   400932,
   10469,
   27305,
   992,
   10147,
   180260,
   5271,
   1290,
   3646,
   2163,
   3577,
   743,
   2804,
   705,
   604,
   3330,
   635,
   1346,
   1887,
   2449,
   1055,
   14974,
   1524,
   713,
   3256,
   13884,
   1034,
   5682,
   1097,
   1614,
   858,
   3282,
   1692,
   2142,
   5735,
   1472,
   1296,
   532,
   497,
   613,
   811,
   3016],
  'percent_of_vote': [62.21,
   32.11,
   0.86,
   0.08,
   0.01,
   0.07,
   0.01,
   2.15,
   1.38,
   0.04,
   0.09,
   0.0,
   0.03,
   0.62,
   0.02,
   0.0,
   0.01,
   0.01,
   0.01,
   0.0,
   0.01,
   0.0,
   0.0,
   0.01,
   0.0,
   0.0,
   0.01,
   0.01,
   0.0,
   0.05,
   0.01,
   0.0,
   0.01,
   0.05,
   0.0,
   0.02,
   0.0,
   0.01,
   0.0,
   0.01,
   0.01,
   0.01,
   0.02,
   0.01,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.01]},
 'Haryana': {'party': ['CPI',
   'BSP',
   'BJP',
   'INLD',
   'INC',
   'RPI(A)',
   'RasLP',
   'AAAP',
   'BSCP',
   'PPID',
   'AAPP',
   'BMUP',
   'PSPL',
   'IND',
   'NOTA',
   'JNJP',
   'NNMP',
   'BHAPRAP',
   'BJSAP',
   'SHS',
   'RMPOI',
   'CPIM',
   'BHTJP',
   'RABSP',
   'SPAKP',
   'JJJKP',
   'AJNSP',
   'RGD',
   'SNP',
   'MYSP',
   'BAHUMP',
   'SUCI(C)',
   'RMEP',
   'AIFB',
   'LTSP',
   'RJAVP',
   'DSPVAD',
   'RPI',
   'VoP',
   'DKSP',
   'RaNP',
   'ABJS',
   'RASAP',
   'RRP',
   'RPIE',
   'AVIRP',
   'ToP',
   'RVP',
   'LPSP',
   'HCP',
   'BKNP',
   'ABD'],
  'total_votes': [7563,
   461273,
   7357347,
   240258,
   3604106,
   2128,
   9005,
   45498,
   4532,
   10849,
   6729,
   11162,
   8094,
   135637,
   41781,
   619970,
   985,
   4587,
   766,
   6761,
   1851,
   9150,
   2209,
   1777,
   770,
   1243,
   551,
   774,
   5027,
   605,
   357,
   5760,
   509,
   1523,
   55280,
   535,
   422,
   443,
   2478,
   346,
   658,
   1027,
   527,
   1868,
   463,
   471,
   330,
   477,
   478,
   1192,
   2688,
   716],
  'percent_of_vote': [0.06,
   3.64,
   58.02,
   1.89,
   28.42,
   0.02,
   0.07,
   0.36,
   0.04,
   0.09,
   0.05,
   0.09,
   0.06,
   1.07,
   0.33,
   4.89,
   0.01,
   0.04,
   0.01,
   0.05,
   0.01,
   0.07,
   0.02,
   0.01,
   0.01,
   0.01,
   0.0,
   0.01,
   0.04,
   0.0,
   0.0,
   0.05,
   0.0,
   0.01,
   0.44,
   0.0,
   0.0,
   0.0,
   0.02,
   0.0,
   0.01,
   0.01,
   0.0,
   0.01,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.01,
   0.02,
   0.01]},
 'Himachal Pradesh': {'party': ['BJP',
   'BSP',
   'INC',
   'NED',
   'SWAP',
   'HIMJKP',
   'IND',
   'NOTA',
   'CPIM',
   'PPID',
   'AIFB',
   'RADM',
   'APoI',
   'BSCP',
   'SatBP',
   'BMUP'],
  'total_votes': [2661281,
   32780,
   1051113,
   2371,
   1839,
   970,
   35710,
   33008,
   14838,
   511,
   7097,
   3799,
   1872,
   751,
   2319,
   473],
  'percent_of_vote': [69.11,
   0.85,
   27.3,
   0.06,
   0.05,
   0.03,
   0.93,
   0.86,
   0.39,
   0.01,
   0.18,
   0.1,
   0.05,
   0.02,
   0.06,
   0.01]},
 'Jammu & Kashmir': {'party': ['JKNPP',
   'JKPDP',
   'INC',
   'JKN',
   'BJP',
   'JPC',
   'IND',
   'NOTA',
   'PDP',
   'JD(U)',
   'SHS',
   'RaJPa',
   'MaNPa',
   'PSPL',
   'BSP',
   'DSSP',
   'NRCP',
   'AIFB',
   'HND',
   'INDPP',
   'JKPPAP'],
  'total_votes': [34044,
   84054,
   1011527,
   280356,
   1648041,
   133612,
   226239,
   21739,
   36700,
   1250,
   3430,
   506,
   2184,
   217,
   30877,
   26588,
   2776,
   3866,
   1281,
   1723,
   1612],
  'percent_of_vote': [0.96,
   2.37,
   28.47,
   7.89,
   46.39,
   3.76,
   6.37,
   0.61,
   1.03,
   0.04,
   0.1,
   0.01,
   0.06,
   0.01,
   0.87,
   0.75,
   0.08,
   0.11,
   0.04,
   0.05,
   0.05]},
 'Karnataka': {'party': ['BJP',
   'INC',
   'BSP',
   'BBM',
   'UPJP',
   'RPI',
   'IND',
   'NOTA',
   'RPI(A)',
   'RPIK',
   'SDC',
   'KJP',
   'RTBHP',
   'BMUP',
   'HJP',
   'JD(S)',
   'RSPS',
   'BBKD',
   'SJPA',
   'SUCI(C)',
   'BHPP',
   'ABML(S)',
   'APoI',
   'BHAPRAP',
   'PrStP',
   'BAHUMP',
   'NDEP',
   'PUJP',
   'KKJHS',
   'BJKD',
   'MLPOIRF',
   'CPIM',
   'SHS',
   'ILP(AP)',
   'PPOI',
   'SMFB',
   'AINHCP',
   'AMKP',
   'BPKP',
   'PBI',
   'RJBP',
   'BHBHP',
   'IPBP',
   'PSS',
   'SDPI',
   'ASP',
   'PSPL',
   'CPI',
   'INCP',
   'AHNP',
   'EP',
   'KPPR',
   'rpsn',
   'KPJP',
   'KKMP',
   'RTORP',
   'GaAP',
   'JVBP',
   'ICF',
   'DPPS',
   'KCVP',
   'VCK',
   'SAJP'],
  'total_votes': [18053454,
   11203016,
   412382,
   5971,
   120800,
   1059,
   1367841,
   250810,
   6545,
   14746,
   1016,
   2013,
   811,
   645,
   4400,
   3397229,
   4863,
   2159,
   14213,
   24505,
   1649,
   4624,
   3635,
   2372,
   742,
   2028,
   1138,
   1241,
   1707,
   3344,
   1609,
   21923,
   14350,
   3906,
   20760,
   3397,
   1189,
   829,
   3385,
   1320,
   3128,
   1685,
   4625,
   3539,
   46839,
   22619,
   2055,
   17227,
   20235,
   4992,
   1442,
   3697,
   5081,
   1207,
   3084,
   1033,
   385,
   696,
   3017,
   429,
   2510,
   540,
   4991],
  'percent_of_vote': [51.38,
   31.88,
   1.17,
   0.02,
   0.34,
   0.0,
   3.89,
   0.71,
   0.02,
   0.04,
   0.0,
   0.01,
   0.0,
   0.0,
   0.01,
   9.67,
   0.01,
   0.01,
   0.04,
   0.07,
   0.0,
   0.01,
   0.01,
   0.01,
   0.0,
   0.01,
   0.0,
   0.0,
   0.0,
   0.01,
   0.0,
   0.06,
   0.04,
   0.01,
   0.06,
   0.01,
   0.0,
   0.0,
   0.01,
   0.0,
   0.01,
   0.0,
   0.01,
   0.01,
   0.13,
   0.06,
   0.01,
   0.05,
   0.06,
   0.01,
   0.0,
   0.01,
   0.01,
   0.0,
   0.01,
   0.0,
   0.0,
   0.0,
   0.01,
   0.0,
   0.01,
   0.0,
   0.01]},
 'Kerala': {'party': ['BSP',
   'BJP',
   'INC',
   'CPIM',
   'IND',
   'NOTA',
   'SUCI(C)',
   'SDPI',
   'SDC',
   'NALAP',
   'CPI',
   'BDJS',
   'AgIMK',
   'igp',
   'IUML',
   'MCPI',
   'PDP',
   'SMFB',
   'APoI',
   'RSPS',
   'VCK',
   'KEC(M)',
   'KEC',
   'RSP',
   'PNP'],
  'total_votes': [50153,
   2635810,
   7596610,
   5270241,
   817459,
   103596,
   11527,
   80111,
   804,
   2833,
   1233886,
   380847,
   845,
   320,
   1111697,
   871,
   3156,
   932,
   3958,
   379,
   1628,
   421046,
   155135,
   499677,
   1695],
  'percent_of_vote': [0.25,
   12.93,
   37.27,
   25.85,
   4.01,
   0.51,
   0.06,
   0.39,
   0.0,
   0.01,
   6.05,
   1.87,
   0.0,
   0.0,
   5.45,
   0.0,
   0.02,
   0.0,
   0.02,
   0.0,
   0.01,
   2.07,
   0.76,
   2.45,
   0.01]},
 'Madhya Pradesh': {'party': ['BSP',
   'BJP',
   'INC',
   'VSP',
   'PSPL',
   'RPIR',
   'SWAJANPA',
   'RPI(A)',
   'BHAPRAP',
   'RaNP',
   'ARK',
   'RKSP',
   'HND',
   'SHS',
   'IND',
   'NOTA',
   'BMUP',
   'APoI',
   'JANADIP',
   'AIFB',
   'PPID',
   'PSJP',
   'RSOSP',
   'RRP',
   'SUCI(C)',
   'AABHAP',
   'SGUP',
   'BSCP',
   'PHRC',
   'MPJVP',
   'ANRP',
   'SP',
   'SPAKP',
   'GGP',
   'PSPU',
   'SABHP',
   'AKBHAD',
   'RTAMP',
   'JAC',
   'BHJMP',
   'BMVSP',
   'RSPS',
   'SMARTIP',
   'ABHM',
   'CPIM',
   'SJPT',
   'JNSMP',
   'AVVP',
   'KSRP',
   'RsAD',
   'AVIRP',
   'KPOI',
   'CPI',
   'ABGP',
   'SADSP',
   'cvgrp',
   'BJSPP',
   'PBI',
   'BLRP',
   'ANSP',
   'RAPty',
   'PRSP',
   'swbi',
   'RTORP',
   'JLokP',
   'ssrd',
   'SaVP',
   'SDP(MP)',
   'SamSP',
   'BTARP',
   'BAHUMP',
   'NATWOMP',
   'BTP',
   'AINHCP',
   'JD(U)',
   'MNDP',
   'SP(I)',
   'AIUC'],
  'total_votes': [878013,
   21406911,
   12733074,
   4294,
   23901,
   825,
   968,
   9299,
   16598,
   930,
   933,
   1431,
   17767,
   9900,
   699148,
   340984,
   34642,
   32423,
   3112,
   3236,
   35703,
   1204,
   7361,
   1113,
   3540,
   3472,
   15558,
   61758,
   9906,
   15472,
   2360,
   82662,
   28618,
   111512,
   2304,
   10554,
   6879,
   1965,
   7888,
   1055,
   1311,
   2164,
   11877,
   3081,
   14271,
   1672,
   1158,
   1325,
   2426,
   5696,
   6335,
   2583,
   91704,
   46595,
   6368,
   3353,
   1392,
   1890,
   3435,
   1424,
   2272,
   4612,
   527,
   484,
   473,
   572,
   2688,
   418,
   9396,
   4632,
   7760,
   1748,
   14784,
   5584,
   6320,
   4455,
   528,
   4024],
  'percent_of_vote': [2.38,
   58.0,
   34.5,
   0.01,
   0.06,
   0.0,
   0.0,
   0.03,
   0.04,
   0.0,
   0.0,
   0.0,
   0.05,
   0.03,
   1.89,
   0.92,
   0.09,
   0.09,
   0.01,
   0.01,
   0.1,
   0.0,
   0.02,
   0.0,
   0.01,
   0.01,
   0.04,
   0.17,
   0.03,
   0.04,
   0.01,
   0.22,
   0.08,
   0.3,
   0.01,
   0.03,
   0.02,
   0.01,
   0.02,
   0.0,
   0.0,
   0.01,
   0.03,
   0.01,
   0.04,
   0.0,
   0.0,
   0.0,
   0.01,
   0.02,
   0.02,
   0.01,
   0.25,
   0.13,
   0.02,
   0.01,
   0.0,
   0.01,
   0.01,
   0.0,
   0.01,
   0.01,
   0.0,
   0.0,
   0.0,
   0.0,
   0.01,
   0.0,
   0.03,
   0.01,
   0.02,
   0.0,
   0.04,
   0.02,
   0.02,
   0.01,
   0.0,
   0.01]},
 'Maharashtra': {'party': ['INC',
   'BSP',
   'BJP',
   'VBA',
   'BTP',
   'BMUP',
   'IND',
   'NOTA',
   'LKSGM',
   'BALP',
   'BMSM',
   'RASMARP',
   'RJnPty',
   'BAHUMP',
   'BKNP',
   'BARESP',
   'NCP',
   'HND',
   'RSP(S)',
   'RJSPS',
   'RAJSPty',
   'APoI',
   'HJP',
   'IUML',
   'SHS',
   'PPID',
   'ARP',
   'RJanPty',
   'LJGP',
   'RJBP',
   'CPIM',
   'SUCI(C)',
   'MNDP',
   'CSM',
   'DJHP',
   'ABMP',
   'HBP',
   'ABSSP',
   'BMFP',
   'BSCP',
   'PBI',
   'GGP',
   'PRCP',
   'RBCP',
   'SaRaPa',
   'PHJSP',
   'AKHP',
   'ANC',
   'SP',
   'CPI',
   'STBP',
   'BPSJP',
   'BBKD',
   'SanS',
   'ALoP',
   'ABHS',
   'PSPL',
   'AIMIM',
   'BHAPRAP',
   'NNP',
   'MSHP',
   'BVA',
   'MLPOIRF',
   'JANADIP',
   'BAAP',
   'PECP',
   'NAP',
   'ABJS',
   'SABHP',
   'SVPP',
   'ssrd',
   'BLRP',
   'JAC',
   'RAKRD',
   'RUC',
   'AAPP',
   'AIMF',
   'DMSK',
   'ACDP',
   'KKJHS',
   'JMBP',
   'bns',
   'SwaBP',
   'PUNP',
   'HAPa',
   'RTORP',
   'RBS',
   'MAHKRS',
   'DSPVAD',
   'BEPP',
   'HiPPa',
   'ABEP',
   'BJAZP',
   'SWP',
   'SMFB'],
  'total_votes': [8792237,
   462539,
   14912139,
   3743560,
   22673,
   76579,
   1991492,
   488766,
   8418,
   11383,
   620,
   8997,
   699,
   33428,
   5580,
   52574,
   8387363,
   2096,
   670,
   1934,
   1425,
   51693,
   5597,
   8440,
   12589064,
   8640,
   4399,
   3433,
   1135,
   10835,
   111272,
   1083,
   673,
   1169,
   273,
   480,
   7082,
   735,
   4576,
   905,
   1589,
   5778,
   10446,
   1574,
   1961,
   20620,
   3907,
   7384,
   12306,
   37395,
   12430,
   14757,
   4525,
   1987,
   4856,
   1567,
   1812,
   389042,
   5822,
   4590,
   281578,
   491596,
   12407,
   7054,
   3919,
   2712,
   1654,
   850,
   1290,
   998,
   3184,
   1234,
   1158,
   475,
   1632,
   1890,
   722,
   2199,
   589,
   9493,
   1347,
   4917,
   446,
   547,
   2728,
   1492,
   1820,
   2761,
   1238,
   1434,
   3750,
   1006,
   6607,
   834380,
   2134],
  'percent_of_vote': [16.27,
   0.86,
   27.59,
   6.93,
   0.04,
   0.14,
   3.68,
   0.9,
   0.02,
   0.02,
   0.0,
   0.02,
   0.0,
   0.06,
   0.01,
   0.1,
   15.52,
   0.0,
   0.0,
   0.0,
   0.0,
   0.1,
   0.01,
   0.02,
   23.29,
   0.02,
   0.01,
   0.01,
   0.0,
   0.02,
   0.21,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.01,
   0.0,
   0.01,
   0.0,
   0.0,
   0.01,
   0.02,
   0.0,
   0.0,
   0.04,
   0.01,
   0.01,
   0.02,
   0.07,
   0.02,
   0.03,
   0.01,
   0.0,
   0.01,
   0.0,
   0.0,
   0.72,
   0.01,
   0.01,
   0.52,
   0.91,
   0.02,
   0.01,
   0.01,
   0.01,
   0.0,
   0.0,
   0.0,
   0.0,
   0.01,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.02,
   0.0,
   0.01,
   0.0,
   0.0,
   0.01,
   0.0,
   0.0,
   0.01,
   0.0,
   0.0,
   0.01,
   0.0,
   0.01,
   1.54,
   0.0]},
 'Manipur': {'party': ['INC',
   'CPI',
   'BJP',
   'NEINDP',
   'MPEP',
   'MDPF',
   'RJSNP',
   'IND',
   'NOTA',
   'NCP',
   'NPEP',
   'NPF',
   'JD(U)'],
  'total_votes': [398387,
   133813,
   553377,
   37221,
   1783,
   1256,
   747,
   85565,
   5389,
   2552,
   30726,
   363527,
   2987],
  'percent_of_vote': [24.63,
   8.27,
   34.22,
   2.3,
   0.11,
   0.08,
   0.05,
   5.29,
   0.33,
   0.16,
   1.9,
   22.48,
   0.18]},
 'Meghalaya': {'party': ['UDP', 'BJP', 'INC', 'IND', 'NOTA', 'NPEP'],
  'total_votes': [267256, 108390, 660114, 16142, 10874, 304455],
  'percent_of_vote': [19.55, 7.93, 48.28, 1.18, 0.8, 22.27]},
 'Mizoram': {'party': ['MNF', 'BJP', 'PRISMP', 'IND', 'NOTA'],
  'total_votes': [224286, 28707, 13323, 230796, 2509],
  'percent_of_vote': [44.89, 5.75, 2.67, 46.19, 0.5]},
 'Nagaland': {'party': ['INC', 'NPEP', 'NDPP', 'IND', 'NOTA'],
  'total_votes': [484166, 14997, 500510, 4620, 2064],
  'percent_of_vote': [48.11, 1.49, 49.73, 0.46, 0.21]},
 'Odisha': {'party': ['BSP',
   'INC',
   'BJD',
   'BJP',
   'IND',
   'NOTA',
   'SUCI(C)',
   'HND',
   'AAAP',
   'PSPL',
   'BHAPRAP',
   'GGP',
   'APoI',
   'ANC',
   'AIFB',
   'BMUP',
   'RAIM',
   'ABHM',
   'JMM',

In [78]:
df19.state.unique()

array(['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Goa',
       'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu & Kashmir',
       'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
       'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab',
       'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Tripura', 'Uttar Pradesh',
       'West Bengal', 'Chhattisgarh', 'Jharkhand', 'Uttarakhand',
       'Telangana', 'Andaman & Nicobar Islands', 'Chandigarh',
       'Dadra & Nagar Haveli', 'Daman & Diu', 'NCT OF Delhi',
       'Lakshadweep', 'Puducherry'], dtype=object)

In [79]:
parties_statewise14 = {state : {"party" : [],
          "total_votes" : [],
          "percent_of_vote" : []} for state in df14.state.unique()}

for state in df14.state.unique():
    for party in df14[df14["state"]==state].party.unique():
        parties_statewise14[state]["party"] += [party]
        parties_statewise14[state]["total_votes"] += [df14[(df14["party"]==party) & (df14["state"]==state)].total_votes.sum()]
        parties_statewise14[state]["percent_of_vote"] += [round((df14[(df14["party"]==party) & (df14["state"]==state)].total_votes.sum()/df14[df14["state"]==state].total_votes.sum())*100, 2)]

parties_statewise14

{'Telangana': {'party': ['TRS',
   'INC',
   'TDP',
   'BSP',
   'IND',
   'NOTA',
   'PPOI',
   'RPI',
   'BCUF',
   'NIP',
   'MaSP',
   'RP(K)',
   'BJP',
   'NCP',
   'BMUP',
   'YSRCP',
   'RPI(A)',
   'WPOI',
   'AAAP',
   'MBT',
   'LSP',
   'SHP',
   'AIMIM',
   'TLP',
   'JaSPa',
   'SHS',
   'BCBDP',
   'APRSSP',
   'ABML(S)',
   'pjdl',
   'AIFB',
   'sps',
   'mmsp',
   'RPI(KH)',
   'JAP',
   'SUCI',
   'IUML',
   'RSP',
   'ICSP',
   'TECPI',
   'AIACP',
   'SP(I)',
   'NBNP',
   'CPM',
   'RLD',
   'MCPI',
   'CPI'],
  'total_votes': [6301193,
   4393661,
   2016808,
   218472,
   656441,
   144974,
   97673,
   8609,
   7036,
   5082,
   5724,
   45977,
   2014829,
   4769,
   9344,
   824271,
   40507,
   83122,
   39386,
   7112,
   158248,
   7953,
   680132,
   802,
   15130,
   1390,
   596,
   529,
   809,
   928,
   2015,
   547,
   959,
   1813,
   873,
   554,
   786,
   2058,
   2603,
   2311,
   1593,
   598,
   485,
   108458,
   5551,
   5920,
   187702],
  'percent_of_vote': [34.78,
   24.25,
   11.13,
   1.21,
   3.62,
   0.8,
   0.54,
   0.05,
   0.04,
   0.03,
   0.03,
   0.25,
   11.12,
   0.03,
   0.05,
   4.55,
   0.22,
   0.46,
   0.22,
   0.04,
   0.87,
   0.04,
   3.75,
   0.0,
   0.08,
   0.01,
   0.0,
   0.0,
   0.0,
   0.01,
   0.01,
   0.0,
   0.01,
   0.01,
   0.0,
   0.0,
   0.0,
   0.01,
   0.01,
   0.01,
   0.01,
   0.0,
   0.0,
   0.6,
   0.03,
   0.03,
   1.04]},
 'Andhra Pradesh': {'party': ['TRS',
   'TDP',
   'INC',
   'BSP',
   'PPOI',
   'YSRCP',
   'TLP',
   'ABML(S)',
   'MCPI',
   'AAAP',
   'IUML',
   'ICSP',
   'APRSSP',
   'IND',
   'NOTA',
   'CPM',
   'JaSPa',
   'CPI(ML)(L)',
   'BJP',
   'sps',
   'DABAP',
   'RJD',
   'RPI(KH)',
   'RP(K)',
   'GaAP',
   'RPC(S)',
   'pjdl',
   'MaSP',
   'ILP(AP)',
   'WPOI',
   'ARPS',
   'NPT',
   'GRIP',
   'AIMIM',
   'RPI',
   'SDP',
   'STR',
   'SUCI',
   'RPS',
   'JD(U)',
   'AIFB',
   'ANC',
   'JD(S)',
   'RDHP',
   'HJP'],
  'total_votes': [435077,
   12082422,
   1184668,
   179095,
   78199,
   13171164,
   1765,
   56835,
   7099,
   63101,
   1411,
   8695,
   2214,
   293225,
   195580,
   50066,
   189130,
   6627,
   2077079,
   4323,
   7746,
   3473,
   9703,
   11778,
   5481,
   2025,
   27743,
   16298,
   6390,
   9529,
   12042,
   1455,
   2594,
   5598,
   1614,
   11393,
   6542,
   952,
   4521,
   3809,
   933,
   2565,
   888,
   4112,
   3896],
  'percent_of_vote': [1.44,
   39.94,
   3.92,
   0.59,
   0.26,
   43.54,
   0.01,
   0.19,
   0.02,
   0.21,
   0.0,
   0.03,
   0.01,
   0.97,
   0.65,
   0.17,
   0.63,
   0.02,
   6.87,
   0.01,
   0.03,
   0.01,
   0.03,
   0.04,
   0.02,
   0.01,
   0.09,
   0.05,
   0.02,
   0.03,
   0.04,
   0.0,
   0.01,
   0.02,
   0.01,
   0.04,
   0.02,
   0.0,
   0.01,
   0.01,
   0.0,
   0.01,
   0.0,
   0.01,
   0.01]},
 'Arunachal Pradesh': {'party': ['NCP',
   'AITC',
   'PPA',
   'BJP',
   'INC',
   'AAAP',
   'LB',
   'IND',
   'NOTA'],
  'total_votes': [6065, 9135, 47018, 275344, 246084, 3647, 980, 2362, 6321],
  'percent_of_vote': [1.02, 1.53, 7.88, 46.12, 41.22, 0.61, 0.16, 0.4, 1.06]},
 'Assam': {'party': ['BJP',
   'AGP',
   'AIUDF',
   'INC',
   'AAAP',
   'SUCI',
   'SP',
   'IND',
   'NOTA',
   'CPM',
   'AITC',
   'SHS',
   'JMM',
   'CPI(ML)(L)',
   'IUML',
   'BOPF',
   'LB',
   'rdsc',
   'AIFB',
   'CPI'],
  'total_votes': [5507152,
   577730,
   2237612,
   4467295,
   28613,
   37850,
   24650,
   1436900,
   147057,
   64945,
   106661,
   1922,
   9263,
   42015,
   1455,
   330106,
   4348,
   10800,
   20579,
   28930],
  'percent_of_vote': [36.51,
   3.83,
   14.83,
   29.61,
   0.19,
   0.25,
   0.16,
   9.52,
   0.97,
   0.43,
   0.71,
   0.01,
   0.06,
   0.28,
   0.01,
   2.19,
   0.03,
   0.07,
   0.14,
   0.19]},
 'Bihar': {'party': ['INC',
   'JD(U)',
   'BSP',
   'BJP',
   'BED',
   'JMM',
   'JPS',
   'AAAP',
   'CPI(ML)(L)',
   'IND',
   'NOTA',
   'CPM',
   'RJD',
   'JMBP',
   'JDR',
   'KS',
   'JKNPP',
   'SP',
   'BJKVP',
   'SKLP',
   'ravp',
   'NaLP',
   'AIFB',
   'BMUP',
   'LD',
   'SJP(R)',
   'AITC',
   'BLSP',
   'SHS',
   'JPJD',
   'AKBMP',
   'BVM',
   'VIP',
   'IUML',
   'JHP',
   'LKJP',
   'NCP',
   'BMF',
   'PSS',
   'RVNP',
   'BJJD',
   'JDP',
   'BEMP',
   'PECP',
   'SUCI',
   'RKSP',
   'PBI',
   'LJP',
   'LPSP',
   'RSMD',
   'RJJM',
   'RBCP',
   'GGP',
   'SWSP',
   'BJPARTY',
   'NADP',
   'MHD',
   'CPI',
   'BBC',
   'RND',
   'NTP',
   'SaBP',
   'NLP',
   'KVD',
   'BBMP',
   'BIP',
   'RPI(A)',
   'APCP',
   'BJKD',
   'ABJS',
   'HVD',
   'PMSP',
   'SBSP',
   'RSWD',
   'SSD',
   'RAHM',
   'MOSP'],
  'total_votes': [3021065,
   5662444,
   765758,
   10543025,
   83906,
   189265,
   33910,
   338637,
   463045,
   1533264,
   580964,
   106297,
   7224893,
   14741,
   53864,
   2946,
   2811,
   98331,
   21524,
   19253,
   38992,
   3072,
   12179,
   144964,
   13013,
   56145,
   46850,
   1078473,
   147906,
   27619,
   11221,
   45667,
   9519,
   10538,
   14754,
   10026,
   431292,
   13726,
   14572,
   4450,
   4664,
   3440,
   8729,
   9585,
   16143,
   25921,
   2271,
   2295929,
   6430,
   11075,
   7147,
   4717,
   9580,
   4016,
   6765,
   2536,
   2482,
   413347,
   3344,
   5215,
   3251,
   16078,
   2977,
   7541,
   10160,
   4600,
   15865,
   15370,
   8541,
   15745,
   7921,
   6901,
   7514,
   6994,
   6777,
   7549,
   3291],
  'percent_of_vote': [8.42,
   15.78,
   2.13,
   29.38,
   0.23,
   0.53,
   0.09,
   0.94,
   1.29,
   4.27,
   1.62,
   0.3,
   20.13,
   0.04,
   0.15,
   0.01,
   0.01,
   0.27,
   0.06,
   0.05,
   0.11,
   0.01,
   0.03,
   0.4,
   0.04,
   0.16,
   0.13,
   3.01,
   0.41,
   0.08,
   0.03,
   0.13,
   0.03,
   0.03,
   0.04,
   0.03,
   1.2,
   0.04,
   0.04,
   0.01,
   0.01,
   0.01,
   0.02,
   0.03,
   0.04,
   0.07,
   0.01,
   6.4,
   0.02,
   0.03,
   0.02,
   0.01,
   0.03,
   0.01,
   0.02,
   0.01,
   0.01,
   1.15,
   0.01,
   0.01,
   0.01,
   0.04,
   0.01,
   0.02,
   0.03,
   0.01,
   0.04,
   0.04,
   0.02,
   0.04,
   0.02,
   0.02,
   0.02,
   0.02,
   0.02,
   0.02,
   0.01]},
 'Goa': {'party': ['INC',
   'BJP',
   'CPI',
   'AAAP',
   'SJP(R)',
   'IND',
   'NOTA',
   'BMUP',
   'AITC',
   'GOA',
   'GSRP'],
  'total_votes': [298750,
   436679,
   10077,
   27103,
   3216,
   17152,
   10103,
   666,
   11941,
   530,
   783],
  'percent_of_vote': [36.57,
   53.45,
   1.23,
   3.32,
   0.39,
   2.1,
   1.24,
   0.08,
   1.46,
   0.06,
   0.1]},
 'Gujarat': {'party': ['BSP',
   'BJP',
   'INC',
   'AAAP',
   'BMUP',
   'NOTA',
   'SP',
   'IND',
   'JD(U)',
   'RPIE',
   'BNJD',
   'VHS',
   'HJP',
   'NYP',
   'LoRP',
   'ABCD(A)',
   'BSDL',
   'PAP',
   'HND',
   'LSWP',
   'RPI(KH)',
   'RPI(A)',
   'NCP',
   'RKEP',
   'YuS',
   'RSPS',
   'ADPT',
   'CPM',
   'SUCI',
   'CPI',
   'ADSP',
   'BBC',
   'VoP',
   'CPI(ML)(L)'],
  'total_votes': [243949,
   15249243,
   8486083,
   301558,
   46956,
   454885,
   24729,
   542006,
   101660,
   910,
   20209,
   2880,
   13745,
   653,
   1491,
   895,
   1723,
   698,
   3722,
   1391,
   990,
   2754,
   240466,
   1254,
   4578,
   876,
   3216,
   28958,
   2249,
   13270,
   11362,
   3853,
   1089,
   9702],
  'percent_of_vote': [0.94,
   59.05,
   32.86,
   1.17,
   0.18,
   1.76,
   0.1,
   2.1,
   0.39,
   0.0,
   0.08,
   0.01,
   0.05,
   0.0,
   0.01,
   0.0,
   0.01,
   0.0,
   0.01,
   0.01,
   0.0,
   0.01,
   0.93,
   0.0,
   0.02,
   0.0,
   0.01,
   0.11,
   0.01,
   0.05,
   0.04,
   0.01,
   0.0,
   0.04]},
 'Haryana': {'party': ['CPI',
   'BSP',
   'INLD',
   'BJP',
   'INC',
   'BSCP',
   'RAKP',
   'AAAP',
   'IND',
   'NOTA',
   'AITC',
   'NAJC',
   'IBSPK',
   'BIP',
   'RPI',
   'LD',
   'LPR',
   'CPM',
   'HJCBL',
   'BhSMP',
   'SP',
   'VIP',
   'JM',
   'BMUP',
   'RPP(LB)',
   'AIFB',
   'RPI(A)',
   'RJP(E)',
   'RVNP',
   'RBHP',
   'RJAVP',
   'PHRC',
   'SUCI',
   'RBC',
   'NLP',
   'RUC',
   'RMOP',
   'AIPF',
   'ABHKP',
   'AVIRP',
   'JD(U)',
   'ABHM',
   'RBCP',
   'hkd'],
  'total_votes': [22068,
   527013,
   2799899,
   3993527,
   2634905,
   7372,
   2096,
   487941,
   191278,
   34220,
   4198,
   2196,
   1952,
   762,
   1665,
   1092,
   4396,
   21168,
   703698,
   3672,
   7641,
   2350,
   2901,
   3428,
   1195,
   1314,
   1251,
   2654,
   1536,
   1297,
   259,
   916,
   4254,
   6265,
   2126,
   1429,
   923,
   620,
   685,
   479,
   976,
   1689,
   1084,
   2761],
  'percent_of_vote': [0.19,
   4.58,
   24.36,
   34.74,
   22.92,
   0.06,
   0.02,
   4.24,
   1.66,
   0.3,
   0.04,
   0.02,
   0.02,
   0.01,
   0.01,
   0.01,
   0.04,
   0.18,
   6.12,
   0.03,
   0.07,
   0.02,
   0.03,
   0.03,
   0.01,
   0.01,
   0.01,
   0.02,
   0.01,
   0.01,
   0.0,
   0.01,
   0.04,
   0.05,
   0.02,
   0.01,
   0.01,
   0.01,
   0.01,
   0.0,
   0.01,
   0.01,
   0.01,
   0.02]},
 'Himachal Pradesh': {'party': ['INC',
   'BSP',
   'BJP',
   'SHS',
   'SP',
   'BMUP',
   'AAAP',
   'HiSP',
   'IND',
   'NOTA',
   'CPM'],
  'total_votes': [1260477,
   22928,
   1652995,
   4709,
   8444,
   1538,
   63351,
   997,
   28507,
   29155,
   25399],
  'percent_of_vote': [40.68,
   0.74,
   53.35,
   0.15,
   0.27,
   0.05,
   2.04,
   0.03,
   0.92,
   0.94,
   0.82]},
 'Jammu & Kashmir': {'party': ['BJP',
   'JKNPP',
   'BSP',
   'JKPDP',
   'JKN',
   'GaAP',
   'PRISM',
   'JPC',
   'IND',
   'NOTA',
   'AAAP',
   'ABML(S)',
   'AIFB',
   'SP',
   'AKAKRP',
   'ASP',
   'INC',
   'JMBP',
   'AJKMP',
   'BHBP',
   'SDP'],
  'total_votes': [1154220,
   43452,
   54091,
   732644,
   396713,
   5566,
   2694,
   71154,
   223498,
   31550,
   6523,
   521,
   803,
   6843,
   1568,
   3286,
   815510,
   1809,
   4392,
   3984,
   6042],
  'percent_of_vote': [32.36,
   1.22,
   1.52,
   20.54,
   11.12,
   0.16,
   0.08,
   1.99,
   6.27,
   0.88,
   0.18,
   0.01,
   0.02,
   0.19,
   0.04,
   0.09,
   22.86,
   0.05,
   0.12,
   0.11,
   0.17]},
 'Karnataka': {'party': ['BJP',
   'BSP',
   'INC',
   'NCP',
   'JD(S)',
   'SJPA',
   'AAAP',
   'IND',
   'NOTA',
   'SP',
   'JD(U)',
   'KAP',
   'RPI(A)',
   'SUCI',
   'BHPP',
   'CPIM',
   'LSP',
   'NDEP',
   'PPOI',
   'WPOI',
   'ANC',
   'HJP',
   'RSPS',
   'BMUP',
   'BDBRAJP',
   'RKSP',
   'CPI(ML)(L)',
   'RCMP',
   'CPI',
   'VJCP',
   'JVBP',
   'CPM',
   'SDPI',
   'DPPS',
   'asdp',
   'KDC',
   'GaAP',
   'AITC',
   'KCVP',
   'AIFB'],
  'total_votes': [13350285,
   265006,
   12666530,
   42738,
   3406465,
   15474,
   254501,
   483513,
   257881,
   17582,
   11867,
   33172,
   18886,
   24118,
   4291,
   16031,
   2881,
   3618,
   9606,
   3747,
   4927,
   4728,
   2862,
   5192,
   8990,
   2129,
   7885,
   2803,
   28203,
   3972,
   4270,
   35465,
   27254,
   1342,
   1949,
   1345,
   3784,
   2276,
   707,
   586],
  'percent_of_vote': [43.01,
   0.85,
   40.81,
   0.14,
   10.97,
   0.05,
   0.82,
   1.56,
   0.83,
   0.06,
   0.04,
   0.11,
   0.06,
   0.08,
   0.01,
   0.05,
   0.01,
   0.01,
   0.03,
   0.01,
   0.02,
   0.02,
   0.01,
   0.02,
   0.03,
   0.01,
   0.03,
   0.01,
   0.09,
   0.01,
   0.01,
   0.11,
   0.09,
   0.0,
   0.01,
   0.0,
   0.01,
   0.01,
   0.0,
   0.0]},
 'Kerala': {'party': ['CPM',
   'BSP',
   'INC',
   'BJP',
   'SDPI',
   'AITC',
   'AAAP',
   'IND',
   'NOTA',
   'CPIM',
   'CPI',
   'WPOI',
   'IUML',
   'SHS',
   'SJD',
   'JD(U)',
   'igp',
   'SRP',
   'KEC(M)',
   'JD(S)',
   'SUCI',
   'RSPK(B)',
   'SLAP',
   'RSP',
   'RPI(A)',
   'RPI'],
  'total_votes': [3880655,
   71316,
   5590285,
   1856796,
   273849,
   4299,
   256662,
   2043666,
   210563,
   11070,
   1364010,
   68332,
   816226,
   10181,
   307597,
   3865,
   546,
   6512,
   424194,
   303595,
   18126,
   43051,
   682,
   408528,
   997,
   292],
  'percent_of_vote': [21.59,
   0.4,
   31.1,
   10.33,
   1.52,
   0.02,
   1.43,
   11.37,
   1.17,
   0.06,
   7.59,
   0.38,
   4.54,
   0.06,
   1.71,
   0.02,
   0.0,
   0.04,
   2.36,
   1.69,
   0.1,
   0.24,
   0.0,
   2.27,
   0.01,
   0.0]},
 'Madhya Pradesh': {'party': ['BJP',
   'INC',
   'BSP',
   'RSMD',
   'LSWP',
   'AAAP',
   'JMBP',
   'SP',
   'AITC',
   'RAHM',
   'IND',
   'NOTA',
   'BMUP',
   'BA S D',
   'AIFB',
   'CPM',
   'JND',
   'BRMD',
   'ALHP',
   'bjyp',
   'BhNaP',
   'MAHP',
   'SUCI',
   'ABHM',
   'GGP',
   'BSCP',
   'CPI',
   'PHRC',
   'SHS',
   'PECP',
   'BBPSP',
   'AD',
   'BC',
   'DaVP',
   'BSDS',
   'SAP',
   'NADP',
   'RPI(A)',
   'RsAD',
   'CPIM',
   'SamSP',
   'CSM',
   'NPEP',
   'IUML',
   'APoI',
   'BHSSP',
   'MNDP',
   'RPI(KH)',
   'PRSP',
   'SaVP',
   'PSS',
   'SDPI',
   'BMSM',
   'JD(U)',
   'AMS',
   'ABVCP',
   'SWJP'],
  'total_votes': [16015695,
   10340274,
   1124772,
   7430,
   1429,
   349488,
   7626,
   221306,
   2114,
   1724,
   548867,
   391837,
   36117,
   39629,
   15135,
   16375,
   4719,
   1607,
   1067,
   2000,
   1408,
   2101,
   2682,
   2244,
   169453,
   36913,
   96683,
   3094,
   2625,
   1484,
   1679,
   7830,
   1936,
   950,
   924,
   10422,
   2078,
   7081,
   10037,
   5842,
   16501,
   11837,
   11813,
   9053,
   19063,
   4956,
   6233,
   3250,
   21284,
   763,
   796,
   5557,
   3441,
   13116,
   8544,
   2255,
   4668],
  'percent_of_vote': [54.03,
   34.89,
   3.79,
   0.03,
   0.0,
   1.18,
   0.03,
   0.75,
   0.01,
   0.01,
   1.85,
   1.32,
   0.12,
   0.13,
   0.05,
   0.06,
   0.02,
   0.01,
   0.0,
   0.01,
   0.0,
   0.01,
   0.01,
   0.01,
   0.57,
   0.12,
   0.33,
   0.01,
   0.01,
   0.01,
   0.01,
   0.03,
   0.01,
   0.0,
   0.0,
   0.04,
   0.01,
   0.02,
   0.03,
   0.02,
   0.06,
   0.04,
   0.04,
   0.03,
   0.06,
   0.02,
   0.02,
   0.01,
   0.07,
   0.0,
   0.0,
   0.02,
   0.01,
   0.04,
   0.03,
   0.01,
   0.02]},
 'Maharashtra': {'party': ['INC',
   'BJP',
   'BSP',
   'BBM',
   'BMUP',
   'AAAP',
   'IND',
   'NOTA',
   'MPS(T)',
   'SP',
   'AwVP',
   'WPOI',
   'NCP',
   'RPI',
   'PRCP',
   'RVNP',
   'HJP',
   'MNDP',
   'AIFB',
   'SHS',
   'ARP',
   'NRSN',
   'APoI',
   'LB',
   'RPI(KH)',
   'GGP',
   'CPIM',
   'DESEP',
   'JD(U)',
   'ABMP',
   'ASP',
   'CPI',
   'AITC',
   'SP(I)',
   'RP(K)',
   'MNS',
   'MVA',
   'CPM',
   'JD(S)',
   'IUML',
   'MBT',
   'ANC',
   'RSSDP',
   'GaAP',
   'BVA',
   'PECP',
   'RBS',
   'ABJS',
   'DaP',
   'RAPa',
   'SVPP',
   'PPIS',
   'HSCP',
   'lpi',
   'HND',
   'NLP',
   'JMBP',
   'PWPI',
   'PG',
   'bns',
   'RSPS',
   'SVRP',
   'BJSP',
   'HiPPa',
   'SWP',
   'RPI(A)',
   'ABHM'],
  'total_votes': [8830190,
   13308961,
   1271680,
   360854,
   212129,
   1088997,
   1577114,
   433171,
   13339,
   73732,
   3747,
   15909,
   7782275,
   73984,
   14238,
   1917,
   8015,
   4992,
   12076,
   10050652,
   16461,
   1725,
   37301,
   8071,
   7354,
   10919,
   3795,
   1262,
   17995,
   1077,
   987,
   55533,
   13361,
   8986,
   2736,
   708010,
   3715,
   181629,
   14234,
   2865,
   4235,
   4728,
   3283,
   1201,
   293681,
   4332,
   2910,
   641,
   2175,
   3408,
   394,
   331,
   888,
   5804,
   4640,
   308,
   414,
   497721,
   7222,
   1862,
   451843,
   944,
   1337,
   8853,
   1105073,
   71808,
   1395],
  'percent_of_vote': [18.13,
   27.32,
   2.61,
   0.74,
   0.44,
   2.24,
   3.24,
   0.89,
   0.03,
   0.15,
   0.01,
   0.03,
   15.97,
   0.15,
   0.03,
   0.0,
   0.02,
   0.01,
   0.02,
   20.63,
   0.03,
   0.0,
   0.08,
   0.02,
   0.02,
   0.02,
   0.01,
   0.0,
   0.04,
   0.0,
   0.0,
   0.11,
   0.03,
   0.02,
   0.01,
   1.45,
   0.01,
   0.37,
   0.03,
   0.01,
   0.01,
   0.01,
   0.01,
   0.0,
   0.6,
   0.01,
   0.01,
   0.0,
   0.0,
   0.01,
   0.0,
   0.0,
   0.0,
   0.01,
   0.01,
   0.0,
   0.0,
   1.02,
   0.01,
   0.0,
   0.93,
   0.0,
   0.0,
   0.02,
   2.27,
   0.15,
   0.0]},
 'Manipur': {'party': ['INC',
   'CPI',
   'BJP',
   'AITC',
   'AAAP',
   'JMBP',
   'MDPF',
   'IND',
   'NOTA',
   'NCP',
   'NPF',
   'JD(U)'],
  'total_votes': [588872,
   197428,
   168272,
   52655,
   7604,
   1403,
   2005,
   43013,
   7504,
   61662,
   281133,
   1085],
  'percent_of_vote': [41.69,
   13.98,
   11.91,
   3.73,
   0.54,
   0.1,
   0.14,
   3.04,
   0.53,
   4.37,
   19.9,
   0.08]},
 'Meghalaya': {'party': ['UDP',
   'CPI',
   'BJP',
   'INC',
   'AAAP',
   'IND',
   'NOTA',
   'NPEP'],
  'total_votes': [106817, 7418, 95979, 408925, 8815, 180658, 30145, 239301],
  'percent_of_vote': [9.91, 0.69, 8.9, 37.93, 0.82, 16.76, 2.8, 22.2]},
 'Mizoram': {'party': ['INC', 'AAAP', 'IND', 'NOTA'],
  'total_votes': [210485, 11890, 204331, 6495],
  'percent_of_vote': [48.59, 2.74, 47.17, 1.5]},
 'Nagaland': {'party': ['NPF', 'INC', 'SP(I)', 'NOTA'],
  'total_votes': [713372, 313147, 9695, 2696],
  'percent_of_vote': [68.67, 30.14, 0.93, 0.26]},
 'Punjab': {'party': ['BSP',
   'INC',
   'CPI',
   'BJP',
   'MEDP',
   'AAAP',
   'BGTD',
   'CPI(ML)(L)',
   'SSPD',
   'IND',
   'NOTA',
   'DCP',
   'NBDP',
   'DBSP',
   'BSP(A)',
   'SP',
   'SAD',
   'SAD(M)',
   'aimpr',
   'SHS',
   'BhJaSP',
   'BMUP',
   'CPM',
   'BA S D',
   'JD(U)',
   'AIFB',
   'JKNPP',
   'aicp',
   'RPI(A)',
   'NCP',
   'IVD',
   'IKL',
   'RPI',
   'BhSMP',
   'JanSP',
   'ABSR',
   'PLP',
   'CPIM',
   'IUML'],
  'total_votes': [263227,
   4575879,
   54785,
   1209004,
   3645,
   3373062,
   5471,
   11605,
   6681,
   498039,
   58754,
   833,
   3109,
   5240,
   11104,
   922,
   3636148,
   35516,
   1182,
   12186,
   3336,
   11379,
   17965,
   837,
   2925,
   1168,
   7826,
   2920,
   2151,
   2149,
   1930,
   5084,
   1531,
   2689,
   944,
   4380,
   1386,
   5879,
   2261],
  'percent_of_vote': [1.9,
   33.05,
   0.4,
   8.73,
   0.03,
   24.36,
   0.04,
   0.08,
   0.05,
   3.6,
   0.42,
   0.01,
   0.02,
   0.04,
   0.08,
   0.01,
   26.26,
   0.26,
   0.01,
   0.09,
   0.02,
   0.08,
   0.13,
   0.01,
   0.02,
   0.01,
   0.06,
   0.02,
   0.02,
   0.02,
   0.01,
   0.04,
   0.01,
   0.02,
   0.01,
   0.03,
   0.01,
   0.04,
   0.02]},
 'Rajasthan': {'party': ['BJP',
   'CPM',
   'INC',
   'BMUP',
   'AITC',
   'JMBP',
   'PRCP',
   'BhSMP',
   'AAAP',
   'nuzp',
   'LD',
   'RJVP',
   'IND',
   'NOTA',
   'BSP',
   'BA S D',
   'MEDP',
   'CPI(ML)(L)',
   'ABHM',
   'bhp',
   'JGP',
   'APoI',
   'SP',
   'NPEP',
   'BNNP',
   'LS',
   'CPI',
   'RUC',
   'AIFB',
   'HJP',
   'IPGP',
   'NADP',
   'BYS',
   'SP(I)',
   'ABCD(A)',
   'RAHM',
   'AAP',
   'NCP',
   'AKBAP',
   'AVIRP',
   'JD(U)'],
  'total_votes': [14895106,
   78856,
   8230164,
   39487,
   31160,
   21641,
   5232,
   9579,
   272641,
   124990,
   5859,
   8152,
   1806700,
   327911,
   633786,
   19349,
   6845,
   9512,
   7256,
   1635,
   27624,
   8558,
   15891,
   325334,
   2533,
   3722,
   70933,
   1103,
   621,
   16377,
   3488,
   4281,
   38633,
   9707,
   566,
   699,
   4380,
   12149,
   1040,
   5382,
   21760],
  'percent_of_vote': [54.94,
   0.29,
   30.36,
   0.15,
   0.11,
   0.08,
   0.02,
   0.04,
   1.01,
   0.46,
   0.02,
   0.03,
   6.66,
   1.21,
   2.34,
   0.07,
   0.03,
   0.04,
   0.03,
   0.01,
   0.1,
   0.03,
   0.06,
   1.2,
   0.01,
   0.01,
   0.26,
   0.0,
   0.0,
   0.06,
   0.01,
   0.02,
   0.14,
   0.04,
   0.0,
   0.0,
   0.02,
   0.04,
   0.0,
   0.02,
   0.08]},
 'Sikkim': {'party': ['INC', 'BJP', 'SDF', 'AAAP', 'AITC', 'SKM', 'NOTA'],
  'total_votes': [7189, 7279, 163698, 2541, 1972, 121956, 4332],
  'percent_of_vote': [2.33, 2.36, 52.98, 0.82, 0.64, 39.47, 1.4]},
 'Tamil Nadu': {'party': ['CPI',
   'BSP',
   'DMDK',
   'ADMK',
   'INC',
   'SP',
   'AAAP',
   'VCK',
   'IND',
   'NOTA',
   'DMK',
   'CPM',
   'SUCI',
   'SDPI',
   'LSP',
   'MMKA',
   'RPI',
   'TNMC',
   'BJP',
   'NOC',
   'JD(U)',
   'APM',
   'RPI(A)',
   'CPI(ML)(L)',
   'MDMK',
   'UMK',
   'PMK',
   'IUML',
   'BDBRAJP',
   'SAP',
   'JD(S)',
   'UCPI',
   'ADSMK',
   'JMM(U)',
   'TTNC',
   'CPIM',
   'RSPS',
   'UPI',
   'ABHM',
   'MAMAK',
   'NMK',
   'DFBL',
   'ETMK',
   'JJ',
   'PT',

### Andhra Pradesh

In [80]:
Andhra_Pradesh14 = pd.DataFrame(parties_statewise14["Andhra Pradesh"]).sort_values(by="percent_of_vote", ascending=False)
Andhra_Pradesh19 = pd.DataFrame(parties_statewise19["Andhra Pradesh"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Andhra_Pradesh19, Andhra_Pradesh14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,YSRCP,15537006,49.15,13171164.0,43.54
1,TDP,12515345,39.59,12082422.0,39.94
2,JnP,1829346,5.79,NaN,NaN
3,NOTA,468822,1.48,195580.0,0.65
4,INC,406977,1.29,1184668.0,3.92
5,BJP,303985,0.96,2077079.0,6.87
6,IND,248025,0.78,293225.0,0.97
7,BSP,83613,0.26,179095.0,0.59
8,CPIM,41111,0.13,NaN,NaN
9,PPOI,27339,0.09,78199.0,0.26
10,CPI,26536,0.08,NaN,NaN
11,JAJGP,11464,0.04,NaN,NaN
13,PRSHP,9738,0.03,NaN,NaN
12,RPI(A),8614,0.03,NaN,NaN
15,SP,6753,0.02,NaN,NaN
16,IPBP,6937,0.02,NaN,NaN
17,SDPI,7293,0.02,NaN,NaN
18,SAPRP,4983,0.02,NaN,NaN
19,VCK,4864,0.02,NaN,NaN
20,MPP,7342,0.02,NaN,NaN
14,AYSRCP,5511,0.02,NaN,NaN
27,AIFB,1687,0.01,933.0,0.00
32,IUML,2387,0.01,1411.0,0.00
31,APoI,1757,0.01,NaN,NaN
30,NVSP,4286,0.01,NaN,NaN
29,AINPP,2023,0.01,NaN,NaN
28,DABAP,4444,0.01,7746.0,0.03
26,CPI(ML)(L),4440,0.01,6627.0,0.02
25,VJNP,1726,0.01,NaN,NaN
23,RKSP,3460,0.01,NaN,NaN
22,SUCI(C),2184,0.01,NaN,NaN
21,RPI(KH),1804,0.01,9703.0,0.03
24,SMFB,2107,0.01,NaN,NaN
42,NPT,1341,0.00,1455.0,0.00
50,ACP,1263,0.00,NaN,NaN
49,RPC(S),996,0.00,2025.0,0.01
48,MCPI,583,0.00,7099.0,0.02
47,NRCP,1489,0.00,NaN,NaN
46,HMRD,447,0.00,NaN,NaN
45,ILP(AP),1017,0.00,6390.0,0.02
44,NDDHP,628,0.00,NaN,NaN
43,NNKP,887,0.00,NaN,NaN
40,ANC,1510,0.00,2565.0,0.01
41,AlPP,370,0.00,NaN,NaN
39,BAHUMP,1017,0.00,NaN,NaN
38,BCUF,649,0.00,NaN,NaN
37,RRS,1229,0.00,NaN,NaN
36,ARPS,1563,0.00,12042.0,0.04
35,JPD,913,0.00,NaN,NaN
34,RD,1220,0.00,NaN,NaN
33,RDHP,368,0.00,4112.0,0.01
51,NavaP,1135,0.00,NaN,NaN

### Arunachal Pradesh

In [81]:
Arunachal_Pradesh14 = pd.DataFrame(parties_statewise14["Arunachal Pradesh"]).sort_values(by="percent_of_vote", ascending=False)
Arunachal_Pradesh19 = pd.DataFrame(parties_statewise19["Arunachal Pradesh"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Arunachal_Pradesh19, Arunachal_Pradesh14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,BJP,379679,58.22,275344.0,46.12
1,INC,134888,20.69,246084.0,41.22
2,JD(S),59878,9.18,NaN,NaN
3,PPA,27703,4.25,47018.0,7.88
4,NPEP,27119,4.16,NaN,NaN
5,IND,13439,2.06,2362.0,0.40
6,NOTA,7464,1.14,6321.0,1.06
7,AIFB,1921,0.29,NaN,NaN

### Assam

In [82]:
Assam14 = pd.DataFrame(parties_statewise14["Assam"]).sort_values(by="percent_of_vote", ascending=False)
Assam19 = pd.DataFrame(parties_statewise19["Assam"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Assam19, Assam14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,BJP,6484596,36.05,5507152.0,36.51
1,INC,6373659,35.44,4467295.0,29.61
2,AGP,1480697,8.23,577730.0,3.83
3,AIUDF,1402088,7.80,2237612.0,14.83
4,IND,868715,4.83,1436900.0,9.52
5,BOPF,446774,2.48,330106.0,2.19
6,UPPL,312435,1.74,NaN,NaN
7,NOTA,178353,0.99,147057.0,0.97
8,AITC,74522,0.41,106661.0,0.71
9,VPI,50355,0.28,NaN,NaN
10,NPEP,48689,0.27,NaN,NaN
11,CPIM,40937,0.23,NaN,NaN
12,ASDC,36915,0.21,NaN,NaN
13,CPI,31227,0.17,28930.0,0.19
16,AJM,21678,0.12,NaN,NaN
14,PUJP,22415,0.12,NaN,NaN
15,HND,22031,0.12,NaN,NaN
17,SUCI(C),16831,0.09,NaN,NaN
18,BGanP,13039,0.07,NaN,NaN
19,NCP,11010,0.06,NaN,NaN
20,RPI(A),11250,0.06,NaN,NaN
21,ADRP,8285,0.05,NaN,NaN
22,BMUP,6933,0.04,NaN,NaN
23,AIFB,5816,0.03,20579.0,0.14
24,TNRMPI,3973,0.02,NaN,NaN
25,SwaBP,4110,0.02,NaN,NaN
26,NRCong,4278,0.02,NaN,NaN
27,SP,2383,0.01,24650.0,0.16
28,BNJD,2072,0.01,NaN,NaN

### Bihar

In [83]:
Bihar14 = pd.DataFrame(parties_statewise14["Bihar"]).sort_values(by="percent_of_vote", ascending=False)
Bihar19 = pd.DataFrame(parties_statewise19["Bihar"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Bihar19, Bihar14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,BJP,9619548,23.57,10543025.0,29.38
1,JD(U),8902719,21.82,5662444.0,15.78
2,RJD,6270769,15.37,7224893.0,20.13
3,LJP,3206979,7.86,2295929.0,6.40
4,INC,3140797,7.70,3021065.0,8.42
...,...,...,...,...,...
114,RJPD,1414,0.00,NaN,NaN
115,BHAIP,1613,0.00,NaN,NaN
116,BJAZP,1814,0.00,NaN,NaN
117,JPS,1793,0.00,33910.0,0.09
118,RDU,1907,0.00,NaN,NaN

### Goa

In [84]:
Goa14 = pd.DataFrame(parties_statewise14["Goa"]).sort_values(by="percent_of_vote", ascending=False)
Goa19 = pd.DataFrame(parties_statewise19["Goa"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Goa19, Goa14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,BJP,436650,51.18,436679.0,53.45
1,INC,366158,42.92,298750.0,36.57
2,AAAP,25647,3.01,27103.0,3.32
3,NOTA,12499,1.46,10103.0,1.24
4,IND,7677,0.90,17152.0,2.10
5,RPI(KM),2809,0.33,NaN,NaN
6,SHS,1763,0.21,NaN,NaN

### Gujarat

In [85]:
Gujarat14 = pd.DataFrame(parties_statewise14["Gujarat"]).sort_values(by="percent_of_vote", ascending=False)
Gujarat19 = pd.DataFrame(parties_statewise19["Gujarat"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Gujarat19, Gujarat14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,BJP,18091275,62.21,15249243.0,59.05
1,INC,9337084,32.11,8486083.0,32.86
2,IND,626629,2.15,542006.0,2.10
3,NOTA,400932,1.38,454885.0,1.76
4,BSP,249184,0.86,243949.0,0.94
5,BTP,180260,0.62,NaN,NaN
6,NCP,27305,0.09,240466.0,0.93
7,HND,22482,0.08,3722.0,0.01
8,BMUP,20823,0.07,46956.0,0.18
9,VPP,14974,0.05,NaN,NaN
10,SVPP,13884,0.05,NaN,NaN
11,GAGUP,10469,0.04,NaN,NaN
12,YJJP,10147,0.03,NaN,NaN
14,ADPT,5682,0.02,3216.0,0.01
15,CPI,5735,0.02,13270.0,0.05
13,BNJD,5271,0.02,20209.0,0.08
24,MaNPa,1887,0.01,NaN,NaN
32,JANSAPP,3646,0.01,NaN,NaN
31,JSVP,3330,0.01,NaN,NaN
30,PPID,2163,0.01,NaN,NaN
29,RPWP,3762,0.01,NaN,NaN
28,RTORP,3577,0.01,NaN,NaN
27,aicp,3391,0.01,NaN,NaN
26,ANC,2804,0.01,NaN,NaN
25,RSPS,3016,0.01,876.0,0.00
23,NIRBHP,2449,0.01,NaN,NaN
21,GJPP,1524,0.01,NaN,NaN
20,RSP(S),3256,0.01,NaN,NaN
19,SUCI(C),1614,0.01,NaN,NaN
18,SANVP,3282,0.01,NaN,NaN
17,BARESP,1692,0.01,NaN,NaN
16,STBSP,2142,0.01,NaN,NaN
22,PPOI,1472,0.01,NaN,NaN
41,RVZP,1290,0.00,NaN,NaN
48,APoI,1055,0.00,NaN,NaN
47,SABHP,604,0.00,NaN,NaN
46,LoRP,705,0.00,1491.0,0.01
45,BAHUMP,713,0.00,NaN,NaN
44,BSDL,743,0.00,1723.0,0.01
43,ABJS,1034,0.00,NaN,NaN
42,AINHCP,1097,0.00,NaN,NaN
37,BBC,497,0.00,3853.0,0.01
40,BMFP,858,0.00,NaN,NaN
39,YuS,1296,0.00,4578.0,0.02
38,REALDP,532,0.00,NaN,NaN
36,BSCP,613,0.00,NaN,NaN
35,RNNBP,811,0.00,NaN,NaN
34,BRP,992,0.00,NaN,NaN
33,LOGAP,635,0.00,NaN,NaN
49,PAP,1346,0.00,698.0,0.00

### Haryana

In [86]:
Haryana14 = pd.DataFrame(parties_statewise14["Haryana"]).sort_values(by="percent_of_vote", ascending=False)
Haryana19 = pd.DataFrame(parties_statewise19["Haryana"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Haryana19, Haryana14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,BJP,7357347,58.02,3993527.0,34.74
1,INC,3604106,28.42,2634905.0,22.92
2,JNJP,619970,4.89,NaN,NaN
3,BSP,461273,3.64,527013.0,4.58
4,INLD,240258,1.89,2799899.0,24.36
5,IND,135637,1.07,191278.0,1.66
6,LTSP,55280,0.44,NaN,NaN
7,AAAP,45498,0.36,487941.0,4.24
8,NOTA,41781,0.33,34220.0,0.30
9,PPID,10849,0.09,NaN,NaN
10,BMUP,11162,0.09,3428.0,0.03
11,RasLP,9005,0.07,NaN,NaN
12,CPIM,9150,0.07,NaN,NaN
13,CPI,7563,0.06,22068.0,0.19
14,PSPL,8094,0.06,NaN,NaN
17,AAPP,6729,0.05,NaN,NaN
15,SUCI(C),5760,0.05,NaN,NaN
16,SHS,6761,0.05,NaN,NaN
18,BHAPRAP,4587,0.04,NaN,NaN
19,BSCP,4532,0.04,7372.0,0.06
20,SNP,5027,0.04,NaN,NaN
21,BKNP,2688,0.02,NaN,NaN
22,BHTJP,2209,0.02,NaN,NaN
23,VoP,2478,0.02,NaN,NaN
24,RPI(A),2128,0.02,1251.0,0.01
37,SPAKP,770,0.01,NaN,NaN
32,RMPOI,1851,0.01,NaN,NaN
36,JJJKP,1243,0.01,NaN,NaN
35,BJSAP,766,0.01,NaN,NaN
34,RGD,774,0.01,NaN,NaN
33,NNMP,985,0.01,NaN,NaN
26,RRP,1868,0.01,NaN,NaN
31,RABSP,1777,0.01,NaN,NaN
29,AIFB,1523,0.01,1314.0,0.01
28,RaNP,658,0.01,NaN,NaN
27,ABJS,1027,0.01,NaN,NaN
25,HCP,1192,0.01,NaN,NaN
30,ABD,716,0.01,NaN,NaN
45,RMEP,509,0.00,NaN,NaN
50,MYSP,605,0.00,NaN,NaN
49,RJAVP,535,0.00,259.0,0.00
48,DSPVAD,422,0.00,NaN,NaN
47,RPI,443,0.00,1665.0,0.01
46,DKSP,346,0.00,NaN,NaN
42,RPIE,463,0.00,NaN,NaN
44,RASAP,527,0.00,NaN,NaN
43,BAHUMP,357,0.00,NaN,NaN
41,AVIRP,471,0.00,479.0,0.00
40,ToP,330,0.00,NaN,NaN
39,RVP,477,0.00,NaN,NaN
38,LPSP,478,0.00,NaN,NaN
51,AJNSP,551,0.00,NaN,NaN

### Himachal Pradesh

In [87]:
Himachal_Pradesh14 = pd.DataFrame(parties_statewise14["Himachal Pradesh"]).sort_values(by="percent_of_vote", ascending=False)
Himachal_Pradesh19 = pd.DataFrame(parties_statewise19["Himachal Pradesh"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Himachal_Pradesh19, Himachal_Pradesh14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,BJP,2661281,69.11,1652995.0,53.35
1,INC,1051113,27.30,1260477.0,40.68
2,IND,35710,0.93,28507.0,0.92
3,NOTA,33008,0.86,29155.0,0.94
4,BSP,32780,0.85,22928.0,0.74
5,CPIM,14838,0.39,NaN,NaN
6,AIFB,7097,0.18,NaN,NaN
7,RADM,3799,0.10,NaN,NaN
8,NED,2371,0.06,NaN,NaN
9,SatBP,2319,0.06,NaN,NaN
10,SWAP,1839,0.05,NaN,NaN
11,APoI,1872,0.05,NaN,NaN
12,HIMJKP,970,0.03,NaN,NaN
13,BSCP,751,0.02,NaN,NaN
14,PPID,511,0.01,NaN,NaN
15,BMUP,473,0.01,1538.0,0.05

### Jammu & Kashmir

In [88]:
Jammu_Kashmir14 = pd.DataFrame(parties_statewise14["Jammu & Kashmir"]).sort_values(by="percent_of_vote", ascending=False)
Jammu_Kashmir19 = pd.DataFrame(parties_statewise19["Jammu & Kashmir"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Jammu_Kashmir19, Jammu_Kashmir14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,BJP,1648041,46.39,1154220.0,32.36
1,INC,1011527,28.47,815510.0,22.86
2,JKN,280356,7.89,396713.0,11.12
3,IND,226239,6.37,223498.0,6.27
4,JPC,133612,3.76,71154.0,1.99
5,JKPDP,84054,2.37,732644.0,20.54
6,PDP,36700,1.03,NaN,NaN
7,JKNPP,34044,0.96,43452.0,1.22
8,BSP,30877,0.87,54091.0,1.52
9,DSSP,26588,0.75,NaN,NaN
10,NOTA,21739,0.61,31550.0,0.88
11,AIFB,3866,0.11,803.0,0.02
12,SHS,3430,0.10,NaN,NaN
13,NRCP,2776,0.08,NaN,NaN
14,MaNPa,2184,0.06,NaN,NaN
15,INDPP,1723,0.05,NaN,NaN
16,JKPPAP,1612,0.05,NaN,NaN
17,JD(U),1250,0.04,NaN,NaN
18,HND,1281,0.04,NaN,NaN
19,PSPL,217,0.01,NaN,NaN
20,RaJPa,506,0.01,NaN,NaN

### Karnataka

In [89]:
Karnataka14 = pd.DataFrame(parties_statewise14["Karnataka"]).sort_values(by="percent_of_vote", ascending=False)
Karnataka19 = pd.DataFrame(parties_statewise19["Karnataka"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Karnataka19, Karnataka14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,BJP,18053454,51.38,13350285.0,43.01
1,INC,11203016,31.88,12666530.0,40.81
2,JD(S),3397229,9.67,3406465.0,10.97
3,IND,1367841,3.89,483513.0,1.56
4,BSP,412382,1.17,265006.0,0.85
...,...,...,...,...,...
45,DPPS,429,0.00,1342.0,0.00
44,RTBHP,811,0.00,NaN,NaN
43,VCK,540,0.00,NaN,NaN
42,BHPP,1649,0.00,4291.0,0.01
62,BMUP,645,0.00,5192.0,0.02

### Kerala

In [90]:
Kerala14 = pd.DataFrame(parties_statewise14["Kerala"]).sort_values(by="percent_of_vote", ascending=False)
Kerala19 = pd.DataFrame(parties_statewise19["Kerala"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Kerala19, Kerala14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,INC,7596610,37.27,5590285.0,31.10
1,CPIM,5270241,25.85,11070.0,0.06
2,BJP,2635810,12.93,1856796.0,10.33
3,CPI,1233886,6.05,1364010.0,7.59
4,IUML,1111697,5.45,816226.0,4.54
5,IND,817459,4.01,2043666.0,11.37
6,RSP,499677,2.45,408528.0,2.27
7,KEC(M),421046,2.07,424194.0,2.36
8,BDJS,380847,1.87,NaN,NaN
9,KEC,155135,0.76,NaN,NaN
10,NOTA,103596,0.51,210563.0,1.17
11,SDPI,80111,0.39,273849.0,1.52
12,BSP,50153,0.25,71316.0,0.40
13,SUCI(C),11527,0.06,NaN,NaN
14,APoI,3958,0.02,NaN,NaN
15,PDP,3156,0.02,NaN,NaN
16,VCK,1628,0.01,NaN,NaN
17,PNP,1695,0.01,NaN,NaN
18,NALAP,2833,0.01,NaN,NaN
19,SMFB,932,0.00,NaN,NaN
20,RSPS,379,0.00,NaN,NaN
21,MCPI,871,0.00,NaN,NaN
22,igp,320,0.00,546.0,0.00
23,SDC,804,0.00,NaN,NaN
24,AgIMK,845,0.00,NaN,NaN

### Madhya Pradesh

In [91]:
Madhya_Pradesh14 = pd.DataFrame(parties_statewise14["Madhya Pradesh"]).sort_values(by="percent_of_vote", ascending=False)
Madhya_Pradesh19 = pd.DataFrame(parties_statewise19["Madhya Pradesh"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Madhya_Pradesh19, Madhya_Pradesh14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,BJP,21406911,58.00,16015695.0,54.03
1,INC,12733074,34.50,10340274.0,34.89
2,BSP,878013,2.38,1124772.0,3.79
3,IND,699148,1.89,548867.0,1.85
4,NOTA,340984,0.92,391837.0,1.32
...,...,...,...,...,...
60,ARK,933,0.00,NaN,NaN
59,RKSP,1431,0.00,NaN,NaN
58,NATWOMP,1748,0.00,NaN,NaN
57,AVVP,1325,0.00,NaN,NaN
77,BHJMP,1055,0.00,NaN,NaN

### Maharashtra

In [92]:
Maharashtra14 = pd.DataFrame(parties_statewise14["Maharashtra"]).sort_values(by="percent_of_vote", ascending=False)
Maharashtra19 = pd.DataFrame(parties_statewise19["Maharashtra"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Maharashtra19, Maharashtra14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,BJP,14912139,27.59,13308961.0,27.32
1,SHS,12589064,23.29,10050652.0,20.63
2,INC,8792237,16.27,8830190.0,18.13
3,NCP,8387363,15.52,7782275.0,15.97
4,VBA,3743560,6.93,NaN,NaN
...,...,...,...,...,...
67,HND,2096,0.00,4640.0,0.01
68,DSPVAD,1238,0.00,NaN,NaN
70,ABEP,1006,0.00,NaN,NaN
71,RJnPty,699,0.00,NaN,NaN
94,SMFB,2134,0.00,NaN,NaN

### Manipur

In [93]:
Manipur14 = pd.DataFrame(parties_statewise14["Manipur"]).sort_values(by="percent_of_vote", ascending=False)
Manipur19 = pd.DataFrame(parties_statewise19["Manipur"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Manipur19, Manipur14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,BJP,553377,34.22,168272.0,11.91
1,INC,398387,24.63,588872.0,41.69
2,NPF,363527,22.48,281133.0,19.90
3,CPI,133813,8.27,197428.0,13.98
4,IND,85565,5.29,43013.0,3.04
5,NEINDP,37221,2.30,NaN,NaN
6,NPEP,30726,1.90,NaN,NaN
7,NOTA,5389,0.33,7504.0,0.53
8,JD(U),2987,0.18,1085.0,0.08
9,NCP,2552,0.16,61662.0,4.37
10,MPEP,1783,0.11,NaN,NaN
11,MDPF,1256,0.08,2005.0,0.14
12,RJSNP,747,0.05,NaN,NaN

### Meghalaya

In [94]:
Meghalaya14 = pd.DataFrame(parties_statewise14["Meghalaya"]).sort_values(by="percent_of_vote", ascending=False)
Meghalaya19 = pd.DataFrame(parties_statewise19["Meghalaya"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Meghalaya19, Meghalaya14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,INC,660114,48.28,408925,37.93
1,NPEP,304455,22.27,239301,22.20
2,UDP,267256,19.55,106817,9.91
3,BJP,108390,7.93,95979,8.90
4,IND,16142,1.18,180658,16.76
5,NOTA,10874,0.80,30145,2.80

### Mizoram

In [95]:
Mizoram14 = pd.DataFrame(parties_statewise14["Mizoram"]).sort_values(by="percent_of_vote", ascending=False)
Mizoram19 = pd.DataFrame(parties_statewise19["Mizoram"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Mizoram19, Mizoram19, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,IND,230796,46.19,230796,46.19
1,MNF,224286,44.89,224286,44.89
2,BJP,28707,5.75,28707,5.75
3,PRISMP,13323,2.67,13323,2.67
4,NOTA,2509,0.50,2509,0.50

### Nagaland

In [96]:
Nagaland14 = pd.DataFrame(parties_statewise14["Nagaland"]).sort_values(by="percent_of_vote", ascending=False)
Nagaland19 = pd.DataFrame(parties_statewise19["Nagaland"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Nagaland19, Nagaland14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,NDPP,500510,49.73,NaN,NaN
1,INC,484166,48.11,313147.0,30.14
2,NPEP,14997,1.49,NaN,NaN
3,IND,4620,0.46,NaN,NaN
4,NOTA,2064,0.21,2696.0,0.26

### Odisha data is not available for 2014

In [97]:
# Odisha14 = pd.DataFrame(parties_statewise14["Odisha"]).sort_values(by="percent_of_vote", ascending=False)
Odisha19 = pd.DataFrame(parties_statewise19["Odisha"]).sort_values(by="percent_of_vote", ascending=False)
# pd.merge(Odisha19, Odisha14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)
Odisha19

         party  total_votes  percent_of_vote
2          BJD     10174021            42.76
3          BJP      9130768            38.37
1          INC      3285339            13.81
5         NOTA       310824             1.31
0          BSP       181496             0.76
4          IND       160336             0.67
18         JMM       135552             0.57
31         CPI        59978             0.25
27        CPIM        56929             0.24
12        APoI        58251             0.24
15        BMUP        38217             0.16
6      SUCI(C)        38474             0.16
30  CPI(ML)(L)        28768             0.12
17        ABHM        16549             0.07
16        RAIM        10914             0.05
14        AIFB        11853             0.05
7          HND        10973             0.05
19        AITC         9576             0.04
28        KRUP         8510             0.04
23         FPI         6884             0.03
8         AAAP         6614             0.03
13         ANC         6553             0.03
32         OPD         8304             0.03
21          KS         6785             0.03
22         PBI         4470             0.02
26         skd         3877             0.02
9         PSPL         4616             0.02
29          SP         5148             0.02
25        BMFP         2914             0.01
20        PUJP         1241             0.01
10     BHAPRAP         3467             0.01
11         GGP         2699             0.01
24        JPJD         3222             0.01

### Punjab

In [98]:
Punjab14 = pd.DataFrame(parties_statewise14["Punjab"]).sort_values(by="percent_of_vote", ascending=False)
Punjab19 = pd.DataFrame(parties_statewise19["Punjab"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Punjab19, Punjab14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,INC,5523066,40.12,4575879.0,33.05
1,SAD,3778574,27.45,3636148.0,26.26
2,BJP,1325445,9.63,1209004.0,8.73
3,AAAP,1015773,7.38,3373062.0,24.36
4,BSP,479788,3.49,263227.0,1.90
5,LIP,469784,3.41,NaN,NaN
6,PUNEKP,296620,2.15,NaN,NaN
7,IND,235106,1.71,498039.0,3.60
8,NAWPP,161645,1.17,NaN,NaN
9,NOTA,154423,1.12,58754.0,0.42
10,SAD(M),52185,0.38,35516.0,0.26
11,CPI,42463,0.31,54785.0,0.40
12,HSS,21406,0.16,NaN,NaN
13,BLSD,20335,0.15,NaN,NaN
14,RMPOI,15274,0.11,NaN,NaN
15,SHS,13284,0.10,12186.0,0.09
16,JanSP,10838,0.08,944.0,0.01
17,CPI(ML)(L),10616,0.08,11605.0,0.08
18,CPIM,10665,0.08,5879.0,0.04
19,SADT,10424,0.08,NaN,NaN
20,RJSPS,6415,0.05,NaN,NaN
21,APoI,7561,0.05,NaN,NaN
22,NATJUP,6531,0.05,NaN,NaN
23,BSP(A),6490,0.05,11104.0,0.08
29,BMUP,5596,0.04,11379.0,0.08
32,BHAPRAP,4951,0.04,NaN,NaN
31,PPID,5178,0.04,NaN,NaN
30,SAKAP,6078,0.04,NaN,NaN
27,BHTJP,5001,0.04,NaN,NaN
28,NCP,5689,0.04,2149.0,0.02
25,SUCI(C),5106,0.04,NaN,NaN
24,DPIN,4913,0.04,NaN,NaN
26,IDRP,6106,0.04,NaN,NaN
33,JJJKP,3566,0.03,NaN,NaN
34,ASJP,3678,0.03,NaN,NaN
39,ANC,2400,0.02,NaN,NaN
41,RasLP,3296,0.02,NaN,NaN
40,RASAP,3160,0.02,NaN,NaN
38,JD(U),2726,0.02,2925.0,0.02
37,BSCP,2304,0.02,NaN,NaN
36,PPOI,2824,0.02,NaN,NaN
35,SBM,2917,0.02,NaN,NaN
48,HCP,902,0.01,NaN,NaN
53,RPI(A),2009,0.01,2151.0,0.02
52,PPIS,1597,0.01,NaN,NaN
51,HSP,1014,0.01,NaN,NaN
50,RSP,1733,0.01,NaN,NaN
49,SVJSP,942,0.01,NaN,NaN
42,AKBHAD,1072,0.01,NaN,NaN
47,HBP,1430,0.01,NaN,NaN
46,SLDP,984,0.01,NaN,NaN
45,RPIR,952,0.01,NaN,NaN
44,PLP,692,0.01,1386.0,0.01
43,SP(I),1406,0.01,NaN,NaN
54,DPI,499,0.00,NaN,NaN

### Rajasthan

In [99]:
Rajasthan14 = pd.DataFrame(parties_statewise14["Rajasthan"]).sort_values(by="percent_of_vote", ascending=False)
Rajasthan19 = pd.DataFrame(parties_statewise19["Rajasthan"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Rajasthan19, Rajasthan14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,BJP,18968392,58.47,14895106.0,54.94
1,INC,11107910,34.24,8230164.0,30.36
2,RLTP,660051,2.03,NaN,NaN
3,BSP,348678,1.07,633786.0,2.34
4,IND,347584,1.07,1806700.0,6.66
5,NOTA,327559,1.01,327911.0,1.21
6,BTP,315258,0.97,NaN,NaN
7,APoI,88372,0.27,8558.0,0.03
8,CPIM,78648,0.24,NaN,NaN
9,CPI,46619,0.14,70933.0,0.26
10,BMUP,28476,0.09,39487.0,0.15
12,SHS,16561,0.05,NaN,NaN
11,RTORP,16744,0.05,NaN,NaN
13,BJSTP,12416,0.04,NaN,NaN
14,RRP,12284,0.04,NaN,NaN
15,IPGP,9538,0.03,3488.0,0.01
16,RPWP,7486,0.02,NaN,NaN
17,NPSF,5798,0.02,NaN,NaN
18,SatBP,8006,0.02,NaN,NaN
25,JSVP,1774,0.01,NaN,NaN
29,HND,1745,0.01,NaN,NaN
28,BRKP(D),2880,0.01,NaN,NaN
27,DSPVAD,1862,0.01,NaN,NaN
26,PPID,2751,0.01,NaN,NaN
19,PRCP,2783,0.01,5232.0,0.02
24,PSPL,3444,0.01,NaN,NaN
23,SUCI(C),2623,0.01,NaN,NaN
22,RTKP,1892,0.01,NaN,NaN
21,IICR,2569,0.01,NaN,NaN
20,PSS,2880,0.01,NaN,NaN
30,AVIRP,891,0.00,5382.0,0.02
31,MCPI,1161,0.00,NaN,NaN
32,RKSP,1488,0.00,NaN,NaN
33,SwaBP,508,0.00,NaN,NaN
34,PHRC,626,0.00,NaN,NaN
35,RSVP,349,0.00,NaN,NaN
36,RJBP,506,0.00,NaN,NaN
37,RMGLMP,798,0.00,NaN,NaN
38,BKNP,1154,0.00,NaN,NaN

### Sikkim

In [100]:
Sikkim14 = pd.DataFrame(parties_statewise14["Sikkim"]).sort_values(by="percent_of_vote", ascending=False)
Sikkim19 = pd.DataFrame(parties_statewise19["Sikkim"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Sikkim19, Sikkim14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,SKM,166922,47.46,121956.0,39.47
1,SDF,154489,43.92,163698.0,52.98
2,BJP,16572,4.71,7279.0,2.36
3,INC,3990,1.13,7189.0,2.33
4,IND,2600,0.74,NaN,NaN
5,NOTA,2279,0.65,4332.0,1.40
6,HMSKP,1998,0.57,NaN,NaN
7,SKPP,1503,0.43,NaN,NaN
8,SUTF,614,0.17,NaN,NaN
9,AIP,396,0.11,NaN,NaN
10,JMBP,383,0.11,NaN,NaN

### Tamil Nadu

In [101]:
Tamil_Nadu14 = pd.DataFrame(parties_statewise14["Tamil Nadu"]).sort_values(by="percent_of_vote", ascending=False)
Tamil_Nadu19 = pd.DataFrame(parties_statewise19["Tamil Nadu"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Tamil_Nadu19, Tamil_Nadu14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,DMK,14363332,33.10,9570666.0,23.57
1,ADMK,8307345,19.14,17978922.0,44.28
2,INC,5405674,12.46,1750990.0,4.31
3,IND,3112954,7.17,866317.0,2.13
4,PMK,2297431,5.29,1804812.0,4.44
5,NTK,1672217,3.85,NaN,NaN
6,MNM,1575640,3.63,NaN,NaN
7,BJP,1551924,3.58,2223566.0,5.48
8,CPI,1031617,2.38,219866.0,0.54
9,CPIM,1019003,2.35,10543.0,0.03
10,DMDK,929590,2.14,2078843.0,5.12
11,NOTA,550577,1.27,581782.0,1.43
12,VCK,500229,1.15,606110.0,1.49
13,IUML,469943,1.08,205896.0,0.51
14,TMC(M),220849,0.51,NaN,NaN
15,BSP,161572,0.37,155951.0,0.38
16,TNLK,37356,0.09,NaN,NaN
17,ACDP,35277,0.08,NaN,NaN
18,SDPI,23741,0.05,42003.0,0.10
19,DMSK,12809,0.03,NaN,NaN
20,GPI,11631,0.03,NaN,NaN
21,UMK,9007,0.02,9194.0,0.02
22,PSPL,7279,0.02,NaN,NaN
31,DUUK,3337,0.01,NaN,NaN
38,AIPTMMK,2764,0.01,NaN,NaN
37,PUJP,3521,0.01,NaN,NaN
36,ETMK,5482,0.01,3023.0,0.01
35,MMKA,3599,0.01,8468.0,0.02
34,CPI(ML)(L),5303,0.01,13081.0,0.03
33,APoI,4498,0.01,NaN,NaN
32,TTNP,2516,0.01,NaN,NaN
30,RPI(A),5158,0.01,4501.0,0.01
29,MSKK,2906,0.01,NaN,NaN
27,AgIMK,4274,0.01,NaN,NaN
26,SMFB,4044,0.01,NaN,NaN
25,AMPK,5089,0.01,NaN,NaN
24,SUCI(C),5765,0.01,NaN,NaN
23,PPIS,3317,0.01,NaN,NaN
28,NIDP,2597,0.01,NaN,NaN
54,AIMAK,645,0.00,NaN,NaN
51,DAMK,719,0.00,NaN,NaN
52,APEP,1368,0.00,NaN,NaN
53,AIVP,643,0.00,NaN,NaN
57,RPI,670,0.00,257.0,0.00
55,ICF,1815,0.00,NaN,NaN
56,PPOI,1890,0.00,NaN,NaN
49,AIUUK,1999,0.00,NaN,NaN
58,MKat,1115,0.00,NaN,NaN
50,MLJK,265,0.00,NaN,NaN
46,IMK,748,0.00,NaN,NaN
48,VMMKT,1108,0.00,NaN,NaN
47,AHIMSASP,972,0.00,NaN,NaN
45,rpsn,901,0.00,NaN,NaN
44,AIDMMK,1765,0.00,NaN,NaN
43,UBM,689,0.00,NaN,NaN
42,JKNPP,1251,0.00,NaN,NaN
41,USIP,1244,0.00,NaN,NaN
40,FIP,820,0.00,NaN,NaN
39,CDF,494,0.00,NaN,NaN
59,DCLF,596,0.00,NaN,NaN

### Tripura

In [102]:
Tripura14 = pd.DataFrame(parties_statewise14["Tripura"]).sort_values(by="percent_of_vote", ascending=False)
Tripura19 = pd.DataFrame(parties_statewise19["Tripura"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Tripura19, Tripura19, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,BJP,1055658,49.03,1055658,49.03
1,INC,545679,25.34,545679,25.34
2,CPIM,372789,17.31,372789,17.31
3,IPFT,89529,4.16,89529,4.16
4,IND,34288,1.59,34288,1.59
5,NOTA,23174,1.08,23174,1.08
6,AMB,9708,0.45,9708,0.45
7,AITC,8613,0.40,8613,0.40
8,APoI,7133,0.33,7133,0.33
9,SUCI(C),4525,0.21,4525,0.21
10,TRIPP,2076,0.10,2076,0.10

### Uttar Pradesh

In [103]:
Uttar_Pradesh14 = pd.DataFrame(parties_statewise14["Punjab"]).sort_values(by="percent_of_vote", ascending=False)
Uttar_Pradesh19 = pd.DataFrame(parties_statewise19["Punjab"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Uttar_Pradesh19, Uttar_Pradesh14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,INC,5523066,40.12,4575879.0,33.05
1,SAD,3778574,27.45,3636148.0,26.26
2,BJP,1325445,9.63,1209004.0,8.73
3,AAAP,1015773,7.38,3373062.0,24.36
4,BSP,479788,3.49,263227.0,1.90
5,LIP,469784,3.41,NaN,NaN
6,PUNEKP,296620,2.15,NaN,NaN
7,IND,235106,1.71,498039.0,3.60
8,NAWPP,161645,1.17,NaN,NaN
9,NOTA,154423,1.12,58754.0,0.42
10,SAD(M),52185,0.38,35516.0,0.26
11,CPI,42463,0.31,54785.0,0.40
12,HSS,21406,0.16,NaN,NaN
13,BLSD,20335,0.15,NaN,NaN
14,RMPOI,15274,0.11,NaN,NaN
15,SHS,13284,0.10,12186.0,0.09
16,JanSP,10838,0.08,944.0,0.01
17,CPI(ML)(L),10616,0.08,11605.0,0.08
18,CPIM,10665,0.08,5879.0,0.04
19,SADT,10424,0.08,NaN,NaN
20,RJSPS,6415,0.05,NaN,NaN
21,APoI,7561,0.05,NaN,NaN
22,NATJUP,6531,0.05,NaN,NaN
23,BSP(A),6490,0.05,11104.0,0.08
29,BMUP,5596,0.04,11379.0,0.08
32,BHAPRAP,4951,0.04,NaN,NaN
31,PPID,5178,0.04,NaN,NaN
30,SAKAP,6078,0.04,NaN,NaN
27,BHTJP,5001,0.04,NaN,NaN
28,NCP,5689,0.04,2149.0,0.02
25,SUCI(C),5106,0.04,NaN,NaN
24,DPIN,4913,0.04,NaN,NaN
26,IDRP,6106,0.04,NaN,NaN
33,JJJKP,3566,0.03,NaN,NaN
34,ASJP,3678,0.03,NaN,NaN
39,ANC,2400,0.02,NaN,NaN
41,RasLP,3296,0.02,NaN,NaN
40,RASAP,3160,0.02,NaN,NaN
38,JD(U),2726,0.02,2925.0,0.02
37,BSCP,2304,0.02,NaN,NaN
36,PPOI,2824,0.02,NaN,NaN
35,SBM,2917,0.02,NaN,NaN
48,HCP,902,0.01,NaN,NaN
53,RPI(A),2009,0.01,2151.0,0.02
52,PPIS,1597,0.01,NaN,NaN
51,HSP,1014,0.01,NaN,NaN
50,RSP,1733,0.01,NaN,NaN
49,SVJSP,942,0.01,NaN,NaN
42,AKBHAD,1072,0.01,NaN,NaN
47,HBP,1430,0.01,NaN,NaN
46,SLDP,984,0.01,NaN,NaN
45,RPIR,952,0.01,NaN,NaN
44,PLP,692,0.01,1386.0,0.01
43,SP(I),1406,0.01,NaN,NaN
54,DPI,499,0.00,NaN,NaN

### West Bengal

In [104]:
West_Bengal14 = pd.DataFrame(parties_statewise14["West Bengal"]).sort_values(by="percent_of_vote", ascending=False)
West_Bengal19 = pd.DataFrame(parties_statewise19["West Bengal"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(West_Bengal19, West_Bengal19, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,AITC,24757345,43.28,24757345,43.28
1,BJP,23028517,40.25,23028517,40.25
2,CPIM,3610645,6.31,3610645,6.31
3,INC,3210491,5.61,3210491,5.61
4,NOTA,546788,0.96,546788,0.96
5,IND,541801,0.95,541801,0.95
6,AIFB,239312,0.42,239312,0.42
7,CPI,227695,0.40,227695,0.40
8,BSP,221654,0.39,221654,0.39
9,SUCI(C),217376,0.38,217376,0.38
10,RSP,208275,0.36,208275,0.36
11,SHS,52850,0.09,52850,0.09
12,RVNP,32184,0.06,32184,0.06
13,BMUP,36620,0.06,36620,0.06
14,BNARP,31308,0.05,31308,0.05
15,WPOI,23035,0.04,23035,0.04
16,RaJSP,23580,0.04,23580,0.04
17,AMB,18562,0.03,18562,0.03
18,CPI(ML)(L),15597,0.03,15597,0.03
22,BNJD,9400,0.02,9400,0.02
24,RJNP,8609,0.02,8609,0.02
23,KPPU,12666,0.02,12666,0.02
25,JMM,12936,0.02,12936,0.02
21,SDPI,11696,0.02,11696,0.02
19,PDS,12087,0.02,12087,0.02
20,JKP(N),11204,0.02,11204,0.02
32,PUJP,5917,0.01,5917,0.01
36,NDPOI,7081,0.01,7081,0.01
35,grac,2952,0.01,2952,0.01
34,APoI,3269,0.01,3269,0.01
33,AIJAP,6495,0.01,6495,0.01
37,JeSM,5885,0.01,5885,0.01
31,BHMP,6511,0.01,6511,0.01
29,AKBJHP,8484,0.01,8484,0.01
28,JHAP,4164,0.01,4164,0.01
27,MPOI,4057,0.01,4057,0.01
26,AHNP,6110,0.01,6110,0.01
30,IUC,4003,0.01,4003,0.01
44,UTSAP,2375,0.00,2375,0.00
49,IDRP,1678,0.00,1678,0.00
48,BHAPRAP,1759,0.00,1759,0.00
47,JASP,712,0.00,712,0.00
46,PPOI,965,0.00,965,0.00
45,JSVP,1301,0.00,1301,0.00
41,SWJP,1899,0.00,1899,0.00
43,STPI,730,0.00,730,0.00
42,RAJADP,1226,0.00,1226,0.00
40,JKPP,2220,0.00,2220,0.00
39,RPI(A),1803,0.00,1803,0.00
38,ALINLBP,2707,0.00,2707,0.00
50,RAHM,440,0.00,440,0.00

### Chhattisgarh data not available for 2014

In [105]:
# Chhattisgarh14 = pd.DataFrame(parties_statewise14["Chhattisgarh"]).sort_values(by="percent_of_vote", ascending=False)
Chhattisgarh19 = pd.DataFrame(parties_statewise19["Chhattisgarh"]).sort_values(by="percent_of_vote", ascending=False)
# pd.merge(Chhattisgarh19, Chhattisgarh14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)
Chhattisgarh19

      party  total_votes  percent_of_vote
2       BJP      6902477            50.70
0       INC      5569183            40.91
1       BSP       313261             2.30
9       IND       259902             1.91
10     NOTA       196265             1.44
3       GGP        86097             0.63
4      APoI        57703             0.42
7       SHS        50719             0.37
38      CPI        38395             0.28
5    RJsbhP        16902             0.12
18     BSCP        14931             0.11
33  SDP(MP)        12107             0.09
39    ABSKP         9912             0.07
8       SSD         9060             0.07
11     PSPL         8887             0.07
6      BMUP         8769             0.06
22     BKNP         7093             0.05
14     PPID         6240             0.05
20    BHBHP         5045             0.04
12      BTP         5501             0.04
29  SUCI(C)         3690             0.03
25     AVVP         2201             0.02
37     CPIM         2263             0.02
36     SSBD         2802             0.02
26   RPI(A)         2561             0.02
17    cvgrp         2187             0.02
16     SUSP         2568             0.02
24    BSHSP         1852             0.01
23     BLRP          826             0.01
27    RP(K)         1506             0.01
28     FDLP         1519             0.01
21     SWAP          966             0.01
30     IPBP          797             0.01
31  BHAPRAP          775             0.01
32      CSM         1522             0.01
19     BYPP         1986             0.01
34     BHBP         1069             0.01
35    SABHP         1210             0.01
15     RGOP         1850             0.01
13     KMSP         1854             0.01

### Jharkhand

In [106]:
Jharkhand14 = pd.DataFrame(parties_statewise14["Jharkhand"]).sort_values(by="percent_of_vote", ascending=False)
Jharkhand19 = pd.DataFrame(parties_statewise19["Jharkhand"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Jharkhand19, Jharkhand14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,BJP,7623987,50.96,5207439.0,40.11
1,INC,2338466,15.63,1724740.0,13.28
2,JMM,1722635,11.51,1205031.0,9.28
3,JVM,750799,5.02,1567655.0,12.07
4,AJSUP,648277,4.33,481667.0,3.71
5,IND,621247,4.15,426224.0,3.28
6,RJD,361478,2.42,212571.0,1.64
7,NOTA,189365,1.27,190927.0,1.47
8,BSP,166519,1.11,140141.0,1.08
9,CPI(ML)(L),73211,0.49,319222.0,2.46
10,AITC,72070,0.48,306332.0,2.36
11,CPI,70843,0.47,78029.0,0.60
12,CPIM,41283,0.28,14898.0,0.11
13,JKP,35060,0.23,203869.0,1.57
14,APoI,25819,0.17,NaN,NaN
15,BMUP,18007,0.12,39752.0,0.31
16,AIFB,15683,0.10,33873.0,0.26
18,JKPP,13975,0.09,NaN,NaN
17,BLSD,13047,0.09,NaN,NaN
19,SUCI(C),12715,0.08,NaN,NaN
20,AHNP,9786,0.07,NaN,NaN
21,AMB,8300,0.06,16045.0,0.12
22,JMM(U),8672,0.06,NaN,NaN
23,PPID,6885,0.05,NaN,NaN
24,JKP(N),7665,0.05,9062.0,0.07
25,RPI(A),7729,0.05,NaN,NaN
26,KS,5647,0.04,NaN,NaN
27,PSPU,6580,0.04,NaN,NaN
34,ANC,4121,0.03,NaN,NaN
39,ABHM,3845,0.03,5743.0,0.04
38,RJANSWP,4897,0.03,NaN,NaN
37,VSP,4490,0.03,NaN,NaN
36,JAC,3983,0.03,NaN,NaN
35,RTSGP,3895,0.03,NaN,NaN
28,JSVP,4164,0.03,NaN,NaN
33,JPJD,4998,0.03,NaN,NaN
31,VPI,5099,0.03,NaN,NaN
30,HND,4987,0.03,NaN,NaN
29,PSS,4286,0.03,NaN,NaN
32,PUJP,4483,0.03,NaN,NaN
43,BHAPRAP,3479,0.02,NaN,NaN
46,MOSP,3254,0.02,NaN,NaN
44,RTORP,2481,0.02,NaN,NaN
45,HBP,2373,0.02,NaN,NaN
42,AAM,2627,0.02,NaN,NaN
41,RSPSR,2307,0.02,NaN,NaN
40,BaSaPa,2701,0.02,NaN,NaN
47,BHAZS,1527,0.01,NaN,NaN
48,BLRP,1088,0.01,NaN,NaN
49,BMSM,1864,0.01,NaN,NaN
50,BYPP,1463,0.01,NaN,NaN
51,SP,1453,0.01,57401.0,0.44
52,BMFP,1206,0.01,NaN,NaN
53,JKPS,1244,0.01,NaN,NaN
54,UPNSE,2051,0.01,NaN,NaN
55,BJKD,1842,0.01,NaN,NaN

### Uttarakhand

In [107]:
Uttarakhand14 = pd.DataFrame(parties_statewise14["Uttarakhand"]).sort_values(by="percent_of_vote", ascending=False)
Uttarakhand19 = pd.DataFrame(parties_statewise19["Uttarakhand"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Uttarakhand19, Uttarakhand14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,BJP,2954833,61.01,2429698.0,55.32
1,INC,1520767,31.40,1494440.0,34.03
2,BSP,216755,4.48,207846.0,4.73
3,NOTA,50946,1.05,48043.0,1.09
4,IND,48003,0.99,76158.0,1.73
5,UKDD,12629,0.26,NaN,NaN
6,UKKD,8830,0.18,NaN,NaN
7,CPIM,6626,0.14,NaN,NaN
9,CPI(ML)(L),5488,0.11,11392.0,0.26
8,UPP,5351,0.11,2045.0,0.05
10,PLM,3339,0.07,NaN,NaN
11,BMUP,2856,0.06,664.0,0.02
12,SUCI(C),1437,0.03,NaN,NaN
13,UtPP,1098,0.02,NaN,NaN
14,BaSaPa,937,0.02,NaN,NaN
15,HND,897,0.02,NaN,NaN
16,PPID,738,0.02,NaN,NaN
17,SAVIPA,688,0.01,NaN,NaN
18,PSPL,707,0.01,NaN,NaN

### Telangana

In [108]:
Telangana14 = pd.DataFrame(parties_statewise14["Telangana"]).sort_values(by="percent_of_vote", ascending=False)
Telangana19 = pd.DataFrame(parties_statewise19["Telangana"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Telangana19, Telangana14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,TRS,7696848,41.29,6301193.0,34.78
1,INC,5496686,29.48,4393661.0,24.25
2,BJP,3626173,19.45,2014829.0,11.12
3,IND,586559,3.15,656441.0,3.62
4,AIMIM,517471,2.78,680132.0,3.75
5,NOTA,190798,1.02,144974.0,0.80
6,JnP,85781,0.46,NaN,NaN
7,CPIM,82191,0.44,NaN,NaN
8,CPI,73872,0.40,187702.0,1.04
9,TJS,57073,0.31,NaN,NaN
10,BSP,45494,0.24,218472.0,1.21
11,AHNP,29183,0.16,NaN,NaN
12,MCPI,18430,0.10,5920.0,0.03
13,PPOI,19089,0.10,97673.0,0.54
14,BMUP,14831,0.08,9344.0,0.05
15,BARP,13544,0.07,NaN,NaN
16,ANC,9553,0.05,NaN,NaN
17,IPBP,8323,0.04,NaN,NaN
18,APoI,6837,0.04,NaN,NaN
19,NPRP,8007,0.04,NaN,NaN
20,SMFB,5963,0.03,NaN,NaN
25,ACDP,3674,0.02,NaN,NaN
24,SDC,3501,0.02,NaN,NaN
23,SJPI,3927,0.02,NaN,NaN
22,TELYS,3407,0.02,NaN,NaN
21,PJSP,4179,0.02,NaN,NaN
34,TSP,1048,0.01,NaN,NaN
42,DABAP,1689,0.01,NaN,NaN
41,SHS,2624,0.01,1390.0,0.01
40,pjdl,1223,0.01,928.0,0.01
39,SUCI(C),2779,0.01,NaN,NaN
38,NATWOMP,2155,0.01,NaN,NaN
37,AIFB,1458,0.01,2015.0,0.01
36,IRNP,2012,0.01,NaN,NaN
35,TECPI,1660,0.01,2311.0,0.01
33,BRPPA,1008,0.01,NaN,NaN
32,RPI,1416,0.01,8609.0,0.05
31,RPI(KH),2598,0.01,1813.0,0.01
30,HBP,1895,0.01,NaN,NaN
29,RaJPa,2705,0.01,NaN,NaN
28,YSRPP,1320,0.01,NaN,NaN
27,NIP,1059,0.01,5082.0,0.03
26,JASWP,1056,0.01,NaN,NaN
43,TGPJP,521,0.00,NaN,NaN
44,ABML(S),555,0.00,809.0,0.00
45,PrStP,720,0.00,NaN,NaN

### Andaman & Nicobar Islands

In [109]:
Andaman_Nicobar_Islands14 = pd.DataFrame(parties_statewise14["Andaman & Nicobar Islands"]).sort_values(by="percent_of_vote", ascending=False)
Andaman_Nicobar_Islands19 = pd.DataFrame(parties_statewise19["Andaman & Nicobar Islands"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Andaman_Nicobar_Islands19, Andaman_Nicobar_Islands14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,INC,95308,45.98,83157.0,43.69
1,BJP,93901,45.30,90969.0,47.80
2,IND,9417,4.54,3511.0,1.84
3,AAAP,2839,1.37,3737.0,1.96
4,BSP,2486,1.20,1139.0,0.60
5,AITC,1721,0.83,2283.0,1.20
6,NOTA,1412,0.68,1564.0,0.82
7,AINHCP,212,0.10,NaN,NaN

### Chandigarh

In [110]:
Chandigarh14 = pd.DataFrame(parties_statewise14["Chandigarh"]).sort_values(by="percent_of_vote", ascending=False)
Chandigarh19 = pd.DataFrame(parties_statewise19["Chandigarh"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Chandigarh19, Chandigarh14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,BJP,231188,50.64,191362.0,42.20
1,INC,184218,40.35,121720.0,26.84
2,AAAP,13781,3.02,108679.0,23.97
3,BSP,7396,1.62,15934.0,3.51
4,IND,4714,1.03,8496.0,1.87
5,NOTA,4335,0.95,3106.0,0.68
6,CHKAP,3186,0.70,NaN,NaN
7,BMFP,1578,0.35,NaN,NaN
8,BMUP,920,0.20,550.0,0.12
9,SAKAP,658,0.14,NaN,NaN
10,BHAPRAP,531,0.12,NaN,NaN
11,JanSP,486,0.11,NaN,NaN
13,BhaRP,461,0.10,NaN,NaN
12,BJSAP,452,0.10,NaN,NaN
14,CPIM,377,0.08,NaN,NaN
15,HSS,365,0.08,NaN,NaN
16,BSP(A),312,0.07,NaN,NaN
17,BKNP,285,0.06,NaN,NaN
18,ANC,245,0.05,NaN,NaN
19,RPI(A),212,0.05,NaN,NaN
20,AKBHAD,209,0.05,NaN,NaN
21,RaJPa,194,0.04,NaN,NaN
22,AIFB,164,0.04,NaN,NaN
23,RasLP,158,0.03,NaN,NaN
24,SVJSP,143,0.03,NaN,NaN

### Dadra & Nagar Haveli

In [111]:
Dadra_Nagar_Haveli14 = pd.DataFrame(parties_statewise14["Dadra & Nagar Haveli"]).sort_values(by="percent_of_vote", ascending=False)
Dadra_Nagar_Haveli19 = pd.DataFrame(parties_statewise19["Dadra & Nagar Haveli"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Dadra_Nagar_Haveli19, Dadra_Nagar_Haveli14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,IND,97458,48.98,2786.0,1.69
1,BJP,81420,40.92,80790.0,48.88
2,INC,8608,4.33,74576.0,45.12
3,SHS,4000,2.01,378.0,0.23
4,NOTA,2950,1.48,2962.0,1.79
5,BMUP,1596,0.80,348.0,0.21
6,NSBHP,1160,0.58,NaN,NaN
7,BSP,948,0.48,982.0,0.59
8,BTP,843,0.42,NaN,NaN

### Daman & Diu

In [112]:
Daman_Diu14 = pd.DataFrame(parties_statewise14["Daman & Diu"]).sort_values(by="percent_of_vote", ascending=False)
Daman_Diu19 = pd.DataFrame(parties_statewise19["Daman & Diu"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Daman_Diu19, Daman_Diu14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,BJP,37597,42.98,46960.0,53.83
1,INC,27655,31.62,37738.0,43.26
2,IND,19938,22.79,NaN,NaN
3,NOTA,1487,1.70,1316.0,1.51
4,BSP,792,0.91,490.0,0.56

### NCT OF Delhi

In [113]:
NCT_OF_Delhi14 = pd.DataFrame(parties_statewise14["NCT OF Delhi"]).sort_values(by="percent_of_vote", ascending=False)
NCT_OF_Delhi19 = pd.DataFrame(parties_statewise19["NCT OF Delhi"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(NCT_OF_Delhi19, NCT_OF_Delhi14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,BJP,4908541,56.56,3838850.0,46.41
1,INC,1953900,22.51,1253078.0,15.15
2,AAAP,1571687,18.11,2722887.0,32.92
3,BSP,93977,1.08,101609.0,1.23
4,NOTA,45654,0.53,39690.0,0.48
5,IND,30764,0.35,261664.0,3.16
6,AAPP,6484,0.07,NaN,NaN
7,MKDVP,5017,0.06,NaN,NaN
8,PBI,4223,0.05,NaN,NaN
9,PPID,4201,0.05,NaN,NaN
10,HBP,3892,0.04,NaN,NaN
14,RTORP,2297,0.03,NaN,NaN
16,BHAPRAP,2170,0.03,NaN,NaN
15,RPI(A),2783,0.03,1317.0,0.02
11,SatBP,3029,0.03,NaN,NaN
13,RRP,2244,0.03,NaN,NaN
12,PPOI,2830,0.03,NaN,NaN
22,SUCI(C),1749,0.02,NaN,NaN
26,ANC,2148,0.02,911.0,0.01
25,PRISM,1400,0.02,NaN,NaN
24,JMBP,1537,0.02,1766.0,0.02
23,PSJP,1897,0.02,NaN,NaN
17,JPJD,1393,0.02,NaN,NaN
21,RaNP,1579,0.02,NaN,NaN
20,JNSMP,1708,0.02,NaN,NaN
19,RHSP,1648,0.02,NaN,NaN
18,BHAIP,1651,0.02,NaN,NaN
36,CHALP,958,0.01,NaN,NaN
43,UtPP,943,0.01,NaN,NaN
42,BLokSP,849,0.01,NaN,NaN
41,bjdi,435,0.01,1118.0,0.01
40,ssrd,1291,0.01,NaN,NaN
39,ESP,1270,0.01,NaN,NaN
38,SPRP,740,0.01,NaN,NaN
37,NAPt,1044,0.01,NaN,NaN
27,ARK,636,0.01,NaN,NaN
35,AnAP,1281,0.01,NaN,NaN
33,RJSPS,551,0.01,NaN,NaN
32,SoJP,805,0.01,NaN,NaN
31,BPC,724,0.01,2571.0,0.03
30,ATBP,641,0.01,2135.0,0.03
29,NYP,1053,0.01,NaN,NaN
28,JKNPP,920,0.01,3014.0,0.04
34,TNRMPI,699,0.01,NaN,NaN
49,VPI,314,0.00,NaN,NaN
53,CoAP,275,0.00,NaN,NaN
52,RJBP,249,0.00,NaN,NaN
51,KBD,369,0.00,NaN,NaN
50,ABJS,403,0.00,NaN,NaN
45,SJVP,419,0.00,NaN,NaN
48,AIFB,367,0.00,451.0,0.01
47,ABMP,405,0.00,NaN,NaN
46,SANVP,309,0.00,NaN,NaN
44,BKNP,289,0.00,NaN,NaN
54,RAJADP,370,0.00,NaN,NaN

### Lakshadweep

In [114]:
Lakshadweep14 = pd.DataFrame(parties_statewise14["Lakshadweep"]).sort_values(by="percent_of_vote", ascending=False)
Lakshadweep19 = pd.DataFrame(parties_statewise19["Lakshadweep"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Lakshadweep19, Lakshadweep14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,NCP,22851,48.61,21665.0,50.11
1,INC,22028,46.86,20130.0,46.56
2,JD(U),1342,2.85,NaN,NaN
3,CPIM,420,0.89,NaN,NaN
4,CPI,143,0.30,181.0,0.42
5,BJP,125,0.27,187.0,0.43
6,NOTA,100,0.21,123.0,0.28

### Puducherry

In [115]:
Puducherry14 = pd.DataFrame(parties_statewise14["Puducherry"]).sort_values(by="percent_of_vote", ascending=False)
Puducherry19 = pd.DataFrame(parties_statewise19["Puducherry"]).sort_values(by="percent_of_vote", ascending=False)
pd.merge(Puducherry19, Puducherry14, how="left", on=["party"], suffixes=('_2019', '_2014')).sort_values(by="percent_of_vote_2019", ascending=False)

,party,total_votes_2019,percent_of_vote_2019,total_votes_2014,percent_of_vote_2014
0,INC,444981,56.27,194972.0,26.35
1,AINRC,247956,31.36,255826.0,34.57
2,MNM,38068,4.81,NaN,NaN
3,NTK,22857,2.89,NaN,NaN
4,IND,15626,1.98,26771.0,3.62
5,NOTA,12199,1.54,22268.0,3.01
6,BSP,2689,0.34,2060.0,0.28
7,AgIMK,2201,0.28,NaN,NaN
8,PUDEP,1319,0.17,NaN,NaN
9,SUCI(C),1285,0.16,NaN,NaN
10,CPI(ML)(L),905,0.11,438.0,0.06
11,ACDP,674,0.09,NaN,NaN

# 8. List top 5 constituencies for two major national parties where they have gained vote share in 2019 as compared to 2014.

In [116]:
two_major_party14 = df14[(df14["party"]=="BJP") | (df14["party"]=="INC")]
two_major_party14

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio,state Voter Turnout Ratio,winner_pc
1,Telangana,Adilabad,NARESH,M,37.0,ST,INC,Hand,257994,1563,259557,1386282,1045839,0.754420,0.716444,1st runner
12,Telangana,Peddapalle,G. VIVEKANAND,M,56.0,SC,INC,Hand,273441,897,274338,1425355,1022184,0.717143,0.716444,1st runner
27,Telangana,Karimnagar,CHENNAMANENI VIDYA SAGAR RAO,M,73.0,GEN,BJP,Lotus,213836,992,214828,1550810,1125184,0.725546,0.716444,Not
28,Telangana,Karimnagar,PONNAM PRABHAKAR,M,47.0,GEN,INC,Hand,298386,2320,300706,1550810,1125184,0.725546,0.716444,1st runner
45,Telangana,Nizamabad,ENDALA LAKSHMINARAYANA,M,51.0,GEN,BJP,Lotus,222876,2457,225333,1496193,1033924,0.691037,0.716444,Not
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8298,NCT OF Delhi,SOUTH DELHI,RAMESH KUMAR,M,58.0,GEN,INC,Hand,125061,152,125213,1752748,1102410,0.628961,0.651991,Not
8299,NCT OF Delhi,SOUTH DELHI,RAMESH BIDHURI,M,52.0,GEN,BJP,Lotus,497151,829,497980,1752748,1102410,0.628961,0.651991,win
8320,Lakshadweep,Lakshadweep,M.P. SAYED MOHAMMED KOYA,M,60.0,ST,BJP,Lotus,187,0,187,49922,43239,0.866131,0.866131,Not
8321,Lakshadweep,Lakshadweep,HAMDULLAH SAYEED,M,31.0,ST,INC,Hand,20130,0,20130,49922,43239,0.866131,0.866131,1st runner
8328,Puducherry,Puducherry,V. NARAYANASAMY,M,66.0,GEN,INC,Hand,194873,99,194972,901357,740017,0.821003,0.821003,1st runner

In [117]:
two_major_party19 = df19[(df19["party"]=="BJP") | (df19["party"]=="INC")]
two_major_party19

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio,state Voter Turnout Ratio,winner_pc
1,Andhra Pradesh,Aruku,Dr. KOSURI KASI VISWANADHA VEERA VENKATA SATYA...,MALE,54.0,ST,BJP,Lotus,17578,289,17867,1451418,1074538,0.740337,0.803330,Not
3,Andhra Pradesh,Aruku,SHRUTI DEVI VYRICHERLA,FEMALE,46.0,ST,INC,Hand,17656,74,17730,1451418,1074538,0.740337,0.803330,Not
12,Andhra Pradesh,Srikakulam,DOLA JAGAN,MALE,53.0,GENERAL,INC,Hand,13456,289,13745,1553860,1157329,0.744809,0.803330,Not
14,Andhra Pradesh,Srikakulam,PERLA SAMBA MURTHY,MALE,58.0,GENERAL,BJP,Lotus,7357,1033,8390,1553860,1157329,0.744809,0.803330,Not
22,Andhra Pradesh,Vizianagaram,Adiraju Yedla,MALE,52.0,GENERAL,INC,Hand,15607,118,15725,1503980,1217890,0.809778,0.803330,Not
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8543,NCT OF Delhi,SOUTH DELHI,RAMESH BIDHURI,MALE,57.0,GENERAL,BJP,Lotus,685789,1225,687014,2067463,1214222,0.587300,0.605199,win
8545,NCT OF Delhi,SOUTH DELHI,VIJENDER,MALE,33.0,GENERAL,INC,Hand,164394,219,164613,2067463,1214222,0.587300,0.605199,Not
8571,Lakshadweep,Lakshadweep,ABDUL KHADER HAJI,MALE,70.0,ST,BJP,Lotus,103,22,125,55189,47009,0.851782,0.851782,Not
8575,Lakshadweep,Lakshadweep,HAMDULLAH SAYEED,MALE,36.0,ST,INC,Hand,21980,48,22028,55189,47009,0.851782,0.851782,1st runner
8580,Puducherry,Puducherry,Ve. VAITHILINGAM,MALE,68.0,GENERAL,INC,Hand,444646,335,444981,973410,790760,0.812361,0.812361,win

In [118]:
two_major_party19 = two_major_party19.drop(["candidate", "sex", "age", "category", "party_symbol", "general_votes", "postal_votes"], axis=1)
two_major_party14 = two_major_party14.drop(["candidate", "sex", "age", "category", "party_symbol", "general_votes", "postal_votes"], axis=1)

In [119]:
two_major_party14

,state,pc_name,party,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio,state Voter Turnout Ratio,winner_pc
1,Telangana,Adilabad,INC,259557,1386282,1045839,0.754420,0.716444,1st runner
12,Telangana,Peddapalle,INC,274338,1425355,1022184,0.717143,0.716444,1st runner
27,Telangana,Karimnagar,BJP,214828,1550810,1125184,0.725546,0.716444,Not
28,Telangana,Karimnagar,INC,300706,1550810,1125184,0.725546,0.716444,1st runner
45,Telangana,Nizamabad,BJP,225333,1496193,1033924,0.691037,0.716444,Not
...,...,...,...,...,...,...,...,...,...
8298,NCT OF Delhi,SOUTH DELHI,INC,125213,1752748,1102410,0.628961,0.651991,Not
8299,NCT OF Delhi,SOUTH DELHI,BJP,497980,1752748,1102410,0.628961,0.651991,win
8320,Lakshadweep,Lakshadweep,BJP,187,49922,43239,0.866131,0.866131,Not
8321,Lakshadweep,Lakshadweep,INC,20130,49922,43239,0.866131,0.866131,1st runner
8328,Puducherry,Puducherry,INC,194972,901357,740017,0.821003,0.821003,1st runner

In [120]:
two_major_party19

,state,pc_name,party,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio,state Voter Turnout Ratio,winner_pc
1,Andhra Pradesh,Aruku,BJP,17867,1451418,1074538,0.740337,0.803330,Not
3,Andhra Pradesh,Aruku,INC,17730,1451418,1074538,0.740337,0.803330,Not
12,Andhra Pradesh,Srikakulam,INC,13745,1553860,1157329,0.744809,0.803330,Not
14,Andhra Pradesh,Srikakulam,BJP,8390,1553860,1157329,0.744809,0.803330,Not
22,Andhra Pradesh,Vizianagaram,INC,15725,1503980,1217890,0.809778,0.803330,Not
...,...,...,...,...,...,...,...,...,...
8543,NCT OF Delhi,SOUTH DELHI,BJP,687014,2067463,1214222,0.587300,0.605199,win
8545,NCT OF Delhi,SOUTH DELHI,INC,164613,2067463,1214222,0.587300,0.605199,Not
8571,Lakshadweep,Lakshadweep,BJP,125,55189,47009,0.851782,0.851782,Not
8575,Lakshadweep,Lakshadweep,INC,22028,55189,47009,0.851782,0.851782,1st runner
8580,Puducherry,Puducherry,INC,444981,973410,790760,0.812361,0.812361,win

In [121]:
merge_major_party = pd.merge(two_major_party19, two_major_party14, how="left", on=['state', 'pc_name', 'party'], suffixes=('_19', '_14'))
merge_major_party

,state,pc_name,party,total_votes_19,total_electors_19,Total_vote_pc_19,Voter Turnout Ratio_19,state Voter Turnout Ratio_19,winner_pc_19,total_votes_14,total_electors_14,Total_vote_pc_14,Voter Turnout Ratio_14,state Voter Turnout Ratio_14,winner_pc_14
0,Andhra Pradesh,Aruku,BJP,17867,1451418,1074538,0.740337,0.803330,Not,NaN,NaN,NaN,NaN,NaN,NaN
1,Andhra Pradesh,Aruku,INC,17730,1451418,1074538,0.740337,0.803330,Not,52884.0,1272340.0,909614.0,0.714914,0.781288,Not
2,Andhra Pradesh,Srikakulam,INC,13745,1553860,1157329,0.744809,0.803330,Not,24171.0,1413726.0,1052115.0,0.744214,0.781288,Not
3,Andhra Pradesh,Srikakulam,BJP,8390,1553860,1157329,0.744809,0.803330,Not,NaN,NaN,NaN,NaN,NaN,NaN
4,Andhra Pradesh,Vizianagaram,INC,15725,1503980,1217890,0.809778,0.803330,Not,122487.0,1403736.0,1120316.0,0.798096,0.781288,Not
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
852,NCT OF Delhi,SOUTH DELHI,BJP,687014,2067463,1214222,0.587300,0.605199,win,497980.0,1752748.0,1102410.0,0.628961,0.651991,win
853,NCT OF Delhi,SOUTH DELHI,INC,164613,2067463,1214222,0.587300,0.605199,Not,125213.0,1752748.0,1102410.0,0.628961,0.651991,Not
854,Lakshadweep,Lakshadweep,BJP,125,55189,47009,0.851782,0.851782,Not,187.0,49922.0,43239.0,0.866131,0.866131,Not
855,Lakshadweep,Lakshadweep,INC,22028,55189,47009,0.851782,0.851782,1st runner,20130.0,49922.0,43239.0,0.866131,0.866131,1st runner
856,Puducherry,Puducherry,INC,444981,973410,790760,0.812361,0.812361,win,194972.0,901357.0,740017.0,0.821003,0.821003,1st runner

In [122]:
merge_major_party["Gain"] = merge_major_party["total_votes_19"] - merge_major_party["total_votes_14"]
merge_major_party

,state,pc_name,party,total_votes_19,total_electors_19,Total_vote_pc_19,Voter Turnout Ratio_19,state Voter Turnout Ratio_19,winner_pc_19,total_votes_14,total_electors_14,Total_vote_pc_14,Voter Turnout Ratio_14,state Voter Turnout Ratio_14,winner_pc_14,Gain
0,Andhra Pradesh,Aruku,BJP,17867,1451418,1074538,0.740337,0.803330,Not,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Andhra Pradesh,Aruku,INC,17730,1451418,1074538,0.740337,0.803330,Not,52884.0,1272340.0,909614.0,0.714914,0.781288,Not,-35154.0
2,Andhra Pradesh,Srikakulam,INC,13745,1553860,1157329,0.744809,0.803330,Not,24171.0,1413726.0,1052115.0,0.744214,0.781288,Not,-10426.0
3,Andhra Pradesh,Srikakulam,BJP,8390,1553860,1157329,0.744809,0.803330,Not,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Andhra Pradesh,Vizianagaram,INC,15725,1503980,1217890,0.809778,0.803330,Not,122487.0,1403736.0,1120316.0,0.798096,0.781288,Not,-106762.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
852,NCT OF Delhi,SOUTH DELHI,BJP,687014,2067463,1214222,0.587300,0.605199,win,497980.0,1752748.0,1102410.0,0.628961,0.651991,win,189034.0
853,NCT OF Delhi,SOUTH DELHI,INC,164613,2067463,1214222,0.587300,0.605199,Not,125213.0,1752748.0,1102410.0,0.628961,0.651991,Not,39400.0
854,Lakshadweep,Lakshadweep,BJP,125,55189,47009,0.851782,0.851782,Not,187.0,49922.0,43239.0,0.866131,0.866131,Not,-62.0
855,Lakshadweep,Lakshadweep,INC,22028,55189,47009,0.851782,0.851782,1st runner,20130.0,49922.0,43239.0,0.866131,0.866131,1st runner,1898.0
856,Puducherry,Puducherry,INC,444981,973410,790760,0.812361,0.812361,win,194972.0,901357.0,740017.0,0.821003,0.821003,1st runner,250009.0

### List top 5 constituencies for INC parties where they have gained vote share in 2019 as compared to 2014.

In [123]:
merge_major_party[merge_major_party["party"]=="INC"].sort_values(by="Gain", ascending=False).head(5).pc_name

501       Thiruvallur
505              Karur
503              Arani
502        Krishnagiri
506    Tiruchirappalli
Name: pc_name, dtype: object

### List top 5 constituencies for two BJP parties where they have gained vote share in 2019 as compared to 2014.

In [124]:
merge_major_party[merge_major_party["party"]=="BJP"].sort_values(by="Gain", ascending=False).head(5).pc_name

731         Purulia
688        Ranaghat
668      Jalpaiguri
515    Tripura West
726          Ghatal
Name: pc_name, dtype: object

# 9. List top 5 constituencies for two major national parties where they have lost vote share in 2019 as compared to 2014.

### List top 5 constituencies for INC parties where they have lost vote share in 2019 as compared to 2014.

In [125]:
merge_major_party[merge_major_party["party"]=="INC"].sort_values(by="Gain", ascending=True).head(5).pc_name

384    Ratnagiri - sindhudurg
360                Aurangabad
672                   Raiganj
805                 Nizamabad
519                Saharanpur
Name: pc_name, dtype: object

### List top 5 constituencies for BJP parties where they have lost vote share in 2019 as compared to 2014.

In [126]:
merge_major_party[merge_major_party["party"]=="BJP"].sort_values(by="Gain", ascending=True).head(5).pc_name

6      Visakhapatnam
17        Narsapuram
45         Tirupati
825         Bhongir
826         Warangal
Name: pc_name, dtype: object

# 10. Which constituency has voted the most for NOTA?

### Constituency which has voted the most for NOTA in 2014

In [127]:
df14[(df14["total_votes"]==df14[df14["party"]=="NOTA"]["total_votes"].max()) & (df14["party"]=="NOTA")]

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio,state Voter Turnout Ratio,winner_pc
5416,Tamil Nadu,Nilgiris,None of the Above,M,NaN,NaN,NOTA,NOTA,46495,64,46559,1269173,933076,0.735184,0.739686,Not

### Constituency which has voted the most for NOTA in 2019

In [128]:
df19[(df19["total_votes"]==df19[df19["party"]=="NOTA"]["total_votes"].max()) & (df19["party"]=="NOTA")]

,state,pc_name,candidate,sex,age,category,party,party_symbol,general_votes,postal_votes,total_votes,total_electors,Total_vote_pc,Voter Turnout Ratio,state Voter Turnout Ratio,winner_pc
798,Bihar,Gopalganj (SC),NOTA,NaN,NaN,NaN,NOTA,NaN,51565,95,51660,1839514,1024876,0.557145,0.575,Not

# 11. Which constituencies have elected candidates whose party has less than 10% vote share at state level in 2019?

In [129]:
df19.state.unique()

array(['Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Goa',
       'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu & Kashmir',
       'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
       'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab',
       'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Tripura', 'Uttar Pradesh',
       'West Bengal', 'Chhattisgarh', 'Jharkhand', 'Uttarakhand',
       'Telangana', 'Andaman & Nicobar Islands', 'Chandigarh',
       'Dadra & Nagar Haveli', 'Daman & Diu', 'NCT OF Delhi',
       'Lakshadweep', 'Puducherry'], dtype=object)

In [130]:
Arunachal_Pradesh19[(Arunachal_Pradesh19["percent_of_vote"]<10)].party

3    JD(S)
2      PPA
5     NPEP
6      IND
7     NOTA
4     AIFB
Name: party, dtype: object

In [131]:
df19[(df19["state"]=="Arunachal Pradesh") & (df19["party"]=="AIFB") & (df19["winner_pc"]=="win")]

Empty DataFrame
Columns: [state, pc_name, candidate, sex, age, category, party, party_symbol, general_votes, postal_votes, total_votes, total_electors, Total_vote_pc, Voter Turnout Ratio, state Voter Turnout Ratio, winner_pc]
Index: []

### Andhra Pradesh

In [132]:
res = []
for party in Andhra_Pradesh19[(Andhra_Pradesh19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Andhra Pradesh") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

[]

### Arunachal Pradesh

In [133]:
res = []
for party in Arunachal_Pradesh19[(Arunachal_Pradesh19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Arunachal Pradesh") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

[]

### Assam

In [134]:
res = []
for party in Assam19[(Assam19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Assam") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

['Dhubri', 'Kokrajhar']

### Bihar

In [135]:
res = []
for party in Bihar19[(Bihar19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Bihar") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

['Vaishali', 'Hajipur (SC)', 'Samastipur (SC)', 'Khagaria', 'Nawada', 'Jamui (SC)', 'Kishanganj']

### Goa

In [136]:
res = []
for party in Goa19[(Goa19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Goa") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

[]

### Gujarat

In [137]:
res = []
for party in Gujarat19[(Gujarat19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Gujarat") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

[]

### Haryana

In [138]:
res = []
for party in Haryana19[(Haryana19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Haryana") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

[]

### Himachal Pradesh

In [139]:
res = []
for party in Himachal_Pradesh19[(Himachal_Pradesh19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Himachal Pradesh") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

[]

### Jammu & Kashmir

In [140]:
res = []
for party in Jammu_Kashmir19[(Jammu_Kashmir19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Jammu & Kashmir") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

['Baramulla', 'Srinagar', 'Anantnag']

### Karnataka

In [141]:
res = []
for party in Karnataka19[(Karnataka19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Karnataka") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

['Hassan', 'Mandya']

### Kerala

In [142]:
res = []
for party in Kerala19[(Kerala19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Kerala") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

['Malappuram', 'Ponnani', 'Kollam', 'Kottayam']

### Madhya Pradesh

In [143]:
res = []
for party in Madhya_Pradesh19[(Madhya_Pradesh19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Madhya Pradesh") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

[]

### Maharashtra

In [144]:
res = []
for party in Maharashtra19[(Maharashtra19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Maharashtra") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

['Amravati ', 'Aurangabad']

### Manipur

In [145]:
res = []
for party in Manipur19[(Manipur19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Manipur") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

[]

### Meghalaya

In [146]:
res = []
for party in Meghalaya19[(Meghalaya19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Meghalaya") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

[]

### Mizoram

In [147]:
res = []
for party in Mizoram19[(Mizoram19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Mizoram") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

[]

### Nagaland

In [148]:
res = []
for party in Nagaland19[(Nagaland19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Nagaland") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

[]

### Odisha

In [149]:
res = []
for party in Odisha19[(Odisha19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Odisha") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

[]

### Punjab

In [150]:
res = []
for party in Punjab19[(Punjab19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Punjab") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

['Gurdaspur', 'Hoshiarpur', 'Sangrur']

### Rajasthan

In [151]:
res = []
for party in Rajasthan19[(Rajasthan19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Rajasthan") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

['Nagaur']

### Sikkim

In [152]:
res = []
for party in Sikkim19[(Sikkim19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Sikkim") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

[]

### Tamil Nadu

In [153]:
res = []
for party in Tamil_Nadu19[(Tamil_Nadu19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Tamil Nadu") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

['Tiruppur', 'Nagapattinam ', 'Coimbatore', 'Madurai', 'Chidambaram ', 'Ramanathapuram']

### Tripura

In [154]:
res = []
for party in Tripura19[(Tripura19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Tripura") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

[]

### Uttar Pradesh

In [155]:
res = []
for party in Uttar_Pradesh19[(Uttar_Pradesh19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Uttar Pradesh") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

['Kairana', 'Muzaffarnagar', 'Meerut', 'Baghpat', 'Ghaziabad', 'Gautam Buddha Nagar', 'Bulandshahr', 'Aligarh', 'Hathras', 'Mathura', 'Agra', 'Fatehpur Sikri', 'Firozabad', 'Etah', 'Badaun', 'Aonla', 'Bareilly', 'Pilibhit', 'Shahjahanpur', 'Kheri', 'Dhaurahra', 'Sitapur', 'Hardoi', 'Misrikh', 'Unnao', 'Mohanlalganj', 'Lucknow', 'Amethi', 'Sultanpur', 'Pratapgarh', 'Farrukhabad', 'Etawah', 'Kannauj', 'Kanpur', 'Akbarpur', 'Jalaun', 'Jhansi', 'Hamirpur', 'Banda', 'Fatehpur', 'Kaushambi', 'Phulpur', 'Allahabad', 'Barabanki', 'Faizabad', 'Bahraich', 'Kaiserganj', 'Gonda', 'Domariyaganj', 'Basti', 'Sant Kabir Nagar', 'Maharajganj', 'Gorakhpur', 'Kushi Nagar', 'Deoria', 'Bansgaon', 'Salempur', 'Ballia', 'Machhlishahr', 'Chandauli', 'Varanasi', 'Bhadohi', 'Saharanpur', 'Bijnor', 'Nagina', 'Amroha', 'Ambedkar Nagar', 'Shrawasti', 'Lalganj', 'Ghosi', 'Jaunpur', 'Ghazipur']

In [156]:
Uttar_Pradesh19[(Uttar_Pradesh19["percent_of_vote"]<10)]

         party  total_votes  percent_of_vote
0          BJP      1325445             9.63
2         AAAP      1015773             7.38
20         BSP       479788             3.49
35         LIP       469784             3.41
19      PUNEKP       296620             2.15
9          IND       235106             1.71
54       NAWPP       161645             1.17
10        NOTA       154423             1.12
49      SAD(M)        52185             0.38
11         CPI        42463             0.31
16         HSS        21406             0.16
31        BLSD        20335             0.15
8        RMPOI        15274             0.11
13         SHS        13284             0.10
5        JanSP        10838             0.08
3   CPI(ML)(L)        10616             0.08
26        CPIM        10665             0.08
32        SADT        10424             0.08
27       RJSPS         6415             0.05
30        APoI         7561             0.05
18      NATJUP         6531             0.05
4       BSP(A)         6490             0.05
12        DPIN         4913             0.04
48     SUCI(C)         5106             0.04
44        IDRP         6106             0.04
43       BHTJP         5001             0.04
34         NCP         5689             0.04
7         BMUP         5596             0.04
37       SAKAP         6078             0.04
22        PPID         5178             0.04
23     BHAPRAP         4951             0.04
28       JJJKP         3566             0.03
45        ASJP         3678             0.03
25         SBM         2917             0.02
33        PPOI         2824             0.02
53        BSCP         2304             0.02
52       JD(U)         2726             0.02
21         ANC         2400             0.02
38       RASAP         3160             0.02
40       RasLP         3296             0.02
46      AKBHAD         1072             0.01
51       SP(I)         1406             0.01
50         PLP          692             0.01
47        RPIR          952             0.01
17        SLDP          984             0.01
24         HBP         1430             0.01
29         HCP          902             0.01
42       SVJSP          942             0.01
41         RSP         1733             0.01
39         HSP         1014             0.01
36        PPIS         1597             0.01
14      RPI(A)         2009             0.01
6          DPI          499             0.00

### West Bengal

In [157]:
res = []
for party in West_Bengal19[(West_Bengal19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="West Bengal") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

['Maldaha Dakshin', 'Baharampur']

### Chhattisgarh

In [158]:
res = []
for party in Chhattisgarh19[(Chhattisgarh19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Chhattisgarh") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

[]

### Jharkhand

In [159]:
res = []
for party in Jharkhand19[(Jharkhand19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Jharkhand") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

['Giridih']

### Uttarakhand

In [160]:
res = []
for party in Uttarakhand19[(Uttarakhand19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Uttarakhand") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

[]

### Telangana

In [161]:
res = []
for party in Telangana19[(Telangana19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Telangana") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

['Hyderabad']

### Andaman & Nicobar Islands

In [162]:
res = []
for party in Andaman_Nicobar_Islands19[(Andaman_Nicobar_Islands19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Andaman & Nicobar Islands") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

[]

### Chandigarh

In [163]:
res = []
for party in Chandigarh19[(Chandigarh19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Chandigarh") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

[]

### Dadra & Nagar Haveli

In [164]:
res = []
for party in Dadra_Nagar_Haveli19[(Dadra_Nagar_Haveli19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Dadra & Nagar Haveli") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

[]

### Daman & Diu

In [165]:
res = []
for party in Daman_Diu19[(Daman_Diu19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Daman & Diu") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

[]

### NCT OF Delhi

In [166]:
res = []
for party in NCT_OF_Delhi19[(NCT_OF_Delhi19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="NCT OF Delhi") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

[]

### Lakshadweep

In [167]:
res = []
for party in Lakshadweep19[(Lakshadweep19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Lakshadweep") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

[]

### Puducherry

In [168]:
res = []
for party in Puducherry19[(Puducherry19["percent_of_vote"]<10)].party.unique():
    res += list(df19[(df19["state"]=="Puducherry") & (df19["party"]==party) & (df19["winner_pc"]=="win")].pc_name.unique())
print(res)

[]